Repository zeldaret/oot, pull requests merged in 2022-12, with the labels that each got.

#1225 Camera Flags
  include/functions.h
  include/z64camera.h
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/code/z_onepointdemo.c
  src/code/z_play.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Bg_Bdan_Objects/z_bg_bdan_objects.c
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_Object_Kankyo/z_object_kankyo.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs discussion, Needs lead approval

#1452 Cleanup post good scene names
  include/functions.h
  include/tables/entrance_table.h
  include/tables/scene_table.h
  include/z64scene.h
  src/code/z_scene_table.c
  src/code/z_sram.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Encount1/z_en_encount1.c
  src/overlays/actors/ovl_En_Ge1/z_en_ge1.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Tg/z_en_tg.c
  src/overlays/actors/ovl_En_Viewer/z_en_viewer.c
  src/overlays/actors/ovl_Obj_Bean/z_obj_bean.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/gamestates/ovl_select/z_select.c
  tools/namefixer.py
Labels: Needs contributor approval, Needs lead approval

#1463 Fix misc GCC compatibility issues
  include/z64camera.h
  include/z64math.h
  src/libultra/os/getmemsize.c
Labels: Needs lead approval

#1263 Some cleanup/doc on the item icons
  assets/xml/textures/icon_item_24_static.xml
  assets/xml/textures/icon_item_static.xml
  assets/xml/textures/parameter_static.xml
  include/regs.h
  include/z64interface.h
  include/z64item.h
  src/code/code_80097A00.c
  src/code/z_construct.c
  src/code/z_message_PAL.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.h
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map_PAL.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: Needs contributor approval, Needs lead approval

#1460 `z_play`: Camera Docs and Cleanup
  include/functions.h
  src/code/z_camera.c
  src/code/z_demo.c
  src/code/z_horse.c
  src/code/z_onepointdemo.c
  src/code/z_play.c
  src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo.c
  src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
  src/overlays/actors/ovl_Boss_Fd2/z_boss_fd2.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  src/overlays/actors/ovl_Boss_Ganondrof/z_boss_ganondrof.c
  src/overlays/actors/ovl_Boss_Goma/z_boss_goma.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
  src/overlays/actors/ovl_En_Bom_Bowl_Pit/z_en_bom_bowl_pit.c
  src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.c
  src/overlays/actors/ovl_En_Daiku/z_en_daiku.c
  src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Heishi2/z_en_heishi2.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Kz/z_en_kz.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1.c
  src/overlays/actors/ovl_En_fHG/z_en_fhg.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Needs contributor approval

#1458 Clean up NPC player interaction usages
  src/overlays/actors/ovl_Demo_Im/z_demo_im.c
  src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.c
  src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.h
  src/overlays/actors/ovl_En_Du/z_en_du.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.h
  src/overlays/actors/ovl_En_Guest/z_en_guest.c
  src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
  src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.h
  src/overlays/actors/ovl_En_Hy/z_en_hy.c
  src/overlays/actors/ovl_En_Hy/z_en_hy.h
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Ko/z_en_ko.c
  src/overlays/actors/ovl_En_Kz/z_en_kz.c
  src/overlays/actors/ovl_En_Ma1/z_en_ma1.c
  src/overlays/actors/ovl_En_Ma2/z_en_ma2.c
  src/overlays/actors/ovl_En_Ma3/z_en_ma3.c
  src/overlays/actors/ovl_En_Md/z_en_md.c
  src/overlays/actors/ovl_En_Mu/z_en_mu.c
  src/overlays/actors/ovl_En_Mu/z_en_mu.h
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Niw_Girl/z_en_niw_girl.c
  src/overlays/actors/ovl_En_Niw_Girl/z_en_niw_girl.h
  src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.c
  src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.h
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.h
  src/overlays/actors/ovl_En_Sa/z_en_sa.c
  src/overlays/actors/ovl_En_Tg/z_en_tg.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
  src/overlays/actors/ovl_En_Zl4/z_en_zl4.c
  src/overlays/actors/ovl_En_Zo/z_en_zo.c
Labels: Needs lead approval

#1442 `z_en_reeba` doc
  src/overlays/actors/ovl_En_Encount1/z_en_encount1.c
  src/overlays/actors/ovl_En_Reeba/z_en_reeba.c
  src/overlays/actors/ovl_En_Reeba/z_en_reeba.h
Labels: Needs contributor approval

#1459 TransitionFade docs and clean up other transitions
  assets/xml/code/fbdemo_circle.xml
  assets/xml/code/fbdemo_triforce.xml
  assets/xml/code/fbdemo_wipe1.xml
  include/functions.h
  include/regs.h
  include/z64.h
  include/z64transition.h
  src/code/z_fbdemo_circle.c
  src/code/z_fbdemo_fade.c
  src/code/z_fbdemo_triforce.c
  src/code/z_fbdemo_wipe1.c
  src/code/z_play.c
  src/overlays/actors/ovl_En_Arrow/z_en_arrow.c
  src/overlays/effects/ovl_Effect_Ss_Stone1/z_eff_ss_stone1.c
Labels: Needs lead approval

#1472 Document debug text drawing functions in z_debug.c
  include/functions.h
  include/z64camera.h
  src/code/db_camera.c
  src/code/game.c
  src/code/z_camera.c
  src/code/z_debug.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs contributor approval, Needs lead approval

#1481 document bug in eff_ss_d_fire
  src/overlays/effects/ovl_Effect_Ss_D_Fire/z_eff_ss_d_fire.c
Labels: Needs contributor approval, Needs lead approval

#1475 Split z64.h: gfxprint, message, pause, view (as new headers), +misc
  include/gfxprint.h
  include/z64.h
  include/z64message.h
  include/z64ocarina.h
  include/z64pause.h
  include/z64save.h
  include/z64transition.h
  include/z64view.h
Labels: Needs lead approval
