Repository zeldaret/oot, pull requests merged in 2022-10, with the labels that each got.

#1385 Use intptr types in more code files
  include/functions.h
  include/macros.h
  include/variables.h
  include/z64.h
  include/z64actor.h
  include/z64effect.h
  include/z64scene.h
  src/code/graph.c
  src/code/main.c
  src/code/sys_cfb.c
  src/code/z_actor.c
  src/code/z_actor_dlftbls.c
  src/code/z_construct.c
  src/code/z_effect_soft_sprite_dlftbls.c
  src/code/z_game_dlftbls.c
  src/code/z_kaleido_manager.c
  src/code/z_map_exp.c
  src/code/z_map_mark.c
  src/code/z_message_PAL.c
  src/code/z_parameter.c
  src/code/z_sample.c
  src/code/z_vr_box.c
  src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
  src/overlays/effects/ovl_Effect_Ss_Fhg_Flash/z_eff_ss_fhg_flash.c
  src/overlays/effects/ovl_Effect_Ss_Ice_Smoke/z_eff_ss_ice_smoke.c
Labels: Needs contributor approval

#1383 Various minor fixes
  include/functions.h
  include/z64.h
  spec
  src/boot/stackcheck.c
  src/boot/z_locale.c
  src/code/fault.c
  src/code/z_debug.c
  src/overlays/actors/ovl_Boss_Ganondrof/z_boss_ganondrof.c
  src/overlays/actors/ovl_En_Ge2/z_en_ge2.c
  src/overlays/actors/ovl_En_Ge3/z_en_ge3.c
  src/overlays/actors/ovl_En_Hs/z_en_hs.c
  src/overlays/actors/ovl_En_Jj/z_en_jj.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_En_Toryo/z_en_toryo.c
  src/overlays/actors/ovl_En_Viewer/z_en_viewer.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs contributor approval

#1389 Fix many missing NULLs
  src/boot/z_std_dma.c
  src/code/audio_data.c
  src/code/audio_synthesis.c
  src/code/code_800EC960.c
  src/code/code_800FC620.c
  src/code/fault.c
  src/code/z_DLF.c
  src/code/z_actor.c
  src/code/z_collision_check.c
  src/code/z_kaleido_manager.c
  src/code/z_play.c
  src/code/z_skelanime.c
  src/libultra/io/pfsfindfile.c
  src/overlays/actors/ovl_Bg_Bom_Guard/z_bg_bom_guard.c
  src/overlays/actors/ovl_Bg_Haka_Trap/z_bg_haka_trap.c
  src/overlays/actors/ovl_Bg_Jya_Kanaami/z_bg_jya_kanaami.c
  src/overlays/actors/ovl_Demo_Ec/z_demo_ec.c
  src/overlays/actors/ovl_Demo_Go/z_demo_go.c
  src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.c
  src/overlays/actors/ovl_En_Attack_Niw/z_en_attack_niw.c
  src/overlays/actors/ovl_En_Dog/z_en_dog.c
  src/overlays/actors/ovl_En_Du/z_en_du.c
  src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.c
  src/overlays/actors/ovl_En_Heishi2/z_en_heishi2.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Horse_Ganon/z_en_horse_ganon.c
  src/overlays/actors/ovl_En_Ishi/z_en_ishi.c
  src/overlays/actors/ovl_En_It/z_en_it.c
  src/overlays/actors/ovl_En_Niw/z_en_niw.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Skb/z_en_skb.c
  src/overlays/actors/ovl_En_Tr/z_en_tr.c
  src/overlays/actors/ovl_En_Tubo_Trap/z_en_tubo_trap.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_Item_Ocarina/z_item_ocarina.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/effects/ovl_Effect_Ss_G_Splash/z_eff_ss_g_splash.c
Labels: Needs contributor approval

#1386 Skip compiling C-included files during the build
  Makefile
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
  src/code/z_cheap_proc.inc.c
  src/code/z_onepointdemo.c
  src/code/z_onepointdemo_data.inc.c
  src/libultra/gu/sins.c
  src/libultra/gu/sintable.inc.c
  src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo.c
  src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo_data.inc.c
  src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
  src/overlays/actors/ovl_Boss_Fd/z_boss_fd_colchk.inc.c
  src/overlays/actors/ovl_Boss_Fd2/z_boss_fd2.c
  src/overlays/actors/ovl_Boss_Fd2/z_boss_fd2_colchk.inc.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2_data.inc.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo_colchk.inc.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst_colchk.inc.c
  src/overlays/actors/ovl_Demo_Du/z_demo_du.c
  src/overlays/actors/ovl_Demo_Du/z_demo_du_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Sa/z_demo_sa.c
  src/overlays/actors/ovl_Demo_Sa/z_demo_sa_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Jj/z_en_jj.c
  src/overlays/actors/ovl_En_Jj/z_en_jj_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Kanban/z_en_kanban.c
  src/overlays/actors/ovl_En_Kanban/z_en_kanban_gfx.inc.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Nb/z_en_nb_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1_camera_data.inc.c
  src/overlays/actors/ovl_En_Zl4/z_en_zl4.c
  src/overlays/actors/ovl_En_Zl4/z_en_zl4_cutscene_data.inc.c
Labels: Needs contributor approval

#1370 Some pause menu inputs doc
  include/regs.h
  include/z64.h
  src/code/z_construct.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: Needs contributor approval

#1358 Document Bg_Ice_Shelter (Red Ice)
  assets/xml/objects/object_ice_objects.xml
  src/overlays/actors/ovl_Bg_Ice_Shelter/z_bg_ice_shelter.c
  src/overlays/actors/ovl_Bg_Ice_Shelter/z_bg_ice_shelter.h
Labels: Needs contributor approval

#1390 Document object_bw (Torch Slug)
  assets/xml/objects/object_bw.xml
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_En_Bw/z_en_bw.c
  src/overlays/actors/ovl_En_Bw/z_en_bw.h
Labels: Needs contributor approval

#1234 Document code_800F9280.c -> audio_seqcmd.c i.e. (Audio_QueueSeqCmd)
  include/functions.h
  include/seqcmd.h
  include/sequence.h
  include/variables.h
  include/z64.h
  include/z64audio.h
  src/code/audio_external_data.c
  src/code/code_800EC960.c
  src/code/code_800F7260.c
  src/code/code_800F9280.c
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/code/z_scene.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd.c
  src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo.c
  src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
  src/overlays/actors/ovl_Boss_Fd2/z_boss_fd2.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  src/overlays/actors/ovl_Boss_Ganondrof/z_boss_ganondrof.c
  src/overlays/actors/ovl_Boss_Goma/z_boss_goma.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
  src/overlays/actors/ovl_En_Dnt_Demo/z_en_dnt_demo.c
  src/overlays/actors/ovl_En_Dnt_Jiji/z_en_dnt_jiji.c
  src/overlays/actors/ovl_En_Eg/z_en_eg.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Horse_Game_Check/z_en_horse_game_check.c
  src/overlays/actors/ovl_En_Okarina_Effect/z_en_okarina_effect.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_En_Viewer/z_en_viewer.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
  src/overlays/actors/ovl_En_fHG/z_en_fhg.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_select/z_select.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: Needs contributor approval

#1394 `PlayerActionParam` -> `PlayerItemAction`
  include/functions.h
  include/z64player.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Bg_Ydan_Sp/z_bg_ydan_sp.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  src/overlays/actors/ovl_En_Butte/z_en_butte.c
  src/overlays/actors/ovl_En_Gb/z_en_gb.c
  src/overlays/actors/ovl_En_Hy/z_en_hy.c
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_En_Torch2/z_en_torch2.c
  src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs lead approval

#1395 Document Malon's Singing
  include/functions.h
  src/code/code_800EC960.c
  src/overlays/actors/ovl_En_Ma1/z_en_ma1.c
  src/overlays/actors/ovl_En_Ma1/z_en_ma1.h
  src/overlays/actors/ovl_En_Ma2/z_en_ma2.c
  src/overlays/actors/ovl_En_Ma2/z_en_ma2.h
  src/overlays/actors/ovl_En_Ma3/z_en_ma3.c
  src/overlays/actors/ovl_En_Ma3/z_en_ma3.h
Labels: Needs lead approval

#1401 Document all non-Koume/Kotake parts of object_tw
  assets/xml/objects/object_tw.xml
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.h
Labels: Needs lead approval

#1392 Fix misc 17
  include/tables/dmadata_table_mqdbg.h
  include/tables/entrance_table.h
  include/ultra64/rdb.h
  include/ultra64/ucode.h
  include/z64.h
  include/z64audio.h
  include/z64camera.h
  include/z64environment.h
  include/z64ocarina.h
  include/z64save.h
  src/code/kanread.s
  src/code/z_bgcheck.c
  src/code/z_lights.c
  src/code/z_sram.c
  src/code/z_view.c
  src/libultra/gu/perspective.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Fz/z_en_fz.c
  src/overlays/actors/ovl_En_Heishi1/z_en_heishi1.c
  src/overlays/actors/ovl_En_Heishi2/z_en_heishi2.h
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Skj/z_en_skj.c
  src/overlays/actors/ovl_En_Zo/z_en_zo.c
  src/overlays/actors/ovl_Obj_Timeblock/z_obj_timeblock.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset_PAL.c
Labels: Needs contributor approval

#1378 [Doc] actor En_Bombf (Bombflower) - just the last unk
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.c
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.h
Labels: Needs contributor approval

#1354 `GameInfo` -> `RegEditor`
  docs/tutorial/helper_scripts.md
  include/functions.h
  include/regs.h
  include/variables.h
  include/z64.h
  src/code/game.c
  src/code/main.c
  src/code/z_construct.c
  src/code/z_debug.c
  src/code/z_play.c
  tools/regconvert.py
Labels: Needs contributor approval

#1348 Document Talon (En_Ta)
  include/z64save.h
  src/code/z_actor.c
  src/code/z_demo.c
  src/code/z_horse.c
  src/elf_message/elf_message_field.c
  src/overlays/actors/ovl_Bg_Ingate/z_bg_ingate.c
  src/overlays/actors/ovl_Bg_Spot15_Rrbox/z_bg_spot15_rrbox.c
  src/overlays/actors/ovl_Bg_Umajump/z_bg_umajump.c
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Horse_Game_Check/z_en_horse_game_check.c
  src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.c
  src/overlays/actors/ovl_En_Horse_Normal/z_en_horse_normal.c
  src/overlays/actors/ovl_En_Hy/z_en_hy.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Ma1/z_en_ma1.c
  src/overlays/actors/ovl_En_Ma2/z_en_ma2.c
  src/overlays/actors/ovl_En_Ma3/z_en_ma3.c
  src/overlays/actors/ovl_En_Niw/z_en_niw.c
  src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.h
  src/overlays/actors/ovl_En_Weather_Tag/z_en_weather_tag.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: Needs lead approval

#1406 Further ObjSwitch docs
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.c
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.h
Labels: Needs contributor approval, Needs lead approval

#1408 Improve match for `DbCamera_CalcUpFromPitchYawRoll`, add docs
  src/code/db_camera.c
Labels: Needs contributor approval

#1398 Document elf_message scripting system
  include/functions.h
  include/z64.h
  include/z64elf_message.h
  include/z64quest_hint_commands.h
  include/z64scene.h
  src/code/z_elf_message.c
  src/code/z_play.c
  src/code/z_scene.c
  src/elf_message/elf_message_field.c
  src/elf_message/elf_message_ydan.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  tools/disasm_elf_msg.py
Labels: Needs contributor approval

#1267 `gbi.h` and `ucode_disas.c` cleanups
  include/functions.h
  include/ultra64/gbi.h
  include/ultra64/types.h
  include/z64.h
  src/code/sys_matrix.c
  src/code/ucode_disas.c
Labels: Needs contributor approval

#1356 Lightweight trigonometry doc
  include/functions.h
  src/code/code_800FCE80.c
  src/code/sys_math.c
  src/code/sys_math_atan.c
  src/code/z_lib.c
  src/libultra/gu/cosf.c
  src/libultra/gu/coss.c
  src/libultra/gu/sinf.c
  src/libultra/gu/sins.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
Labels: Needs contributor approval

#1404 Enum comments on some arrays
  src/code/code_80097A00.c
  src/code/z_camera_data.inc.c
  src/code/z_sram.c
  src/overlays/actors/ovl_Item_Etcetera/z_item_etcetera.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs contributor approval

#1400 Misc Sequence Docs
  include/functions.h
  src/code/code_800EC960.c
  src/code/z_demo.c
  src/overlays/actors/ovl_Bg_Relay_Objects/z_bg_relay_objects.c
  src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs contributor approval

#1405 Some `OREG` docs (camera data regs)
  include/regs.h
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
Labels: Needs contributor approval

#1344 Rename scene lists
  include/functions.h
  include/z64.h
  include/z64scene.h
  src/code/z_actor.c
  src/code/z_path.c
  src/code/z_play.c
  src/code/z_room.c
  src/code/z_scene.c
  src/overlays/actors/ovl_Bg_Dy_Yoseizo/z_bg_dy_yoseizo.c
  src/overlays/actors/ovl_Bg_Mizu_Movebg/z_bg_mizu_movebg.c
  src/overlays/actors/ovl_Bg_Spot01_Objects2/z_bg_spot01_objects2.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Cs/z_en_cs.c
  src/overlays/actors/ovl_En_Daiku/z_en_daiku.c
  src/overlays/actors/ovl_En_Daiku_Kakariko/z_en_daiku_kakariko.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.c
  src/overlays/actors/ovl_En_Heishi1/z_en_heishi1.c
  src/overlays/actors/ovl_En_Horse_Normal/z_en_horse_normal.c
  src/overlays/actors/ovl_En_Kz/z_en_kz.c
  src/overlays/actors/ovl_En_Mb/z_en_mb.c
  src/overlays/actors/ovl_En_Md/z_en_md.c
  src/overlays/actors/ovl_En_Mm/z_en_mm.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Niw/z_en_niw.c
  src/overlays/actors/ovl_En_Niw_Girl/z_en_niw_girl.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_En_Po_Desert/z_en_po_desert.c
  src/overlays/actors/ovl_En_River_Sound/z_en_river_sound.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
  src/overlays/actors/ovl_Obj_Bean/z_obj_bean.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs contributor approval, Needs lead approval

#1413 Cleanup, Improve Matches
  src/code/z_actor.c
  src/code/z_eff_ss_dead.c
  src/code/z_lights.c
  src/code/z_map_exp.c
  src/code/z_player_lib.c
  src/code/z_scene.c
  src/overlays/actors/ovl_En_Anubice_Fire/z_en_anubice_fire.c
  src/overlays/actors/ovl_En_Changer/z_en_changer.c
  src/overlays/actors/ovl_En_Fr/z_en_fr.c
  src/overlays/actors/ovl_En_Ganon_Mant/z_en_ganon_mant.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Ik/z_en_ik.c
  src/overlays/actors/ovl_En_Karebaba/z_en_karebaba.c
  src/overlays/actors/ovl_En_Skb/z_en_skb.c
  src/overlays/actors/ovl_En_Zf/z_en_zf.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_Mir_Ray/z_mir_ray.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset_PAL.c
Labels: Needs contributor approval, Needs lead approval

#1352 Documentation pass on `DoorShutter`
  include/functions.h
  src/code/z_actor.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.h
Labels: Needs contributor approval, Needs lead approval

#1364 Doc speed_meter timers and misc. low-ish level stuff
  include/variables.h
  include/z64.h
  src/code/audioMgr.c
  src/code/graph.c
  src/code/sched.c
  src/code/speed_meter.c
  src/code/z_kankyo.c
  src/code/z_prenmi.c
Labels: Needs lead approval

#1416 Move object table from `z_scene.c` to new file `object_table.c`
  spec
  src/code/object_table.c
  src/code/z_scene.c
Labels: Needs contributor approval, Needs lead approval
