Repository zeldaret/oot, pull requests merged in 2022-11, with the labels that each got.

#1307 Some doc on env light settings
  include/functions.h
  include/regs.h
  include/z64bgcheck.h
  include/z64environment.h
  include/z64light.h
  include/z64scene.h
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/code/z_lights.c
  src/code/z_play.c
  src/code/z_room.c
  src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  src/overlays/actors/ovl_En_Weather_Tag/z_en_weather_tag.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Needs contributor approval

#1410 Objects tw and tr
  assets/xml/objects/object_tr.xml
  assets/xml/objects/object_tw.xml
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.h
  src/overlays/actors/ovl_En_Tr/z_en_tr.c
  src/overlays/actors/ovl_En_Tr/z_en_tr.h
Labels: Needs lead approval

#1412 Document Timers
  include/functions.h
  include/z64player.h
  include/z64save.h
  src/code/z_construct.c
  src/code/z_game_over.c
  src/code/z_message_PAL.c
  src/code/z_parameter.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Bg_Po_Event/z_bg_po_event.c
  src/overlays/actors/ovl_Bg_Relay_Objects/z_bg_relay_objects.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.c
  src/overlays/actors/ovl_En_Ds/z_en_ds.c
  src/overlays/actors/ovl_En_Eg/z_en_eg.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Horse_Game_Check/z_en_horse_game_check.c
  src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.c
  src/overlays/actors/ovl_En_Hs/z_en_hs.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Kz/z_en_kz.c
  src/overlays/actors/ovl_En_Ma3/z_en_ma3.c
  src/overlays/actors/ovl_En_Mk/z_en_mk.c
  src/overlays/actors/ovl_En_Mm2/z_en_mm2.c
  src/overlays/actors/ovl_En_Po_Relay/z_en_po_relay.c
  src/overlays/actors/ovl_En_Syateki_Niw/z_en_syateki_niw.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_En_Zl2/z_en_zl2.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
  src/overlays/actors/ovl_Obj_Roomtimer/z_obj_roomtimer.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
Labels: Needs lead approval

#1431 `z_en_bird` doc
  src/overlays/actors/ovl_En_Bird/z_en_bird.c
  src/overlays/actors/ovl_En_Bird/z_en_bird.h
Labels: Needs lead approval

#1429 z_shot_sun: minor doc
  src/overlays/actors/ovl_Shot_Sun/z_shot_sun.c
  src/overlays/actors/ovl_Shot_Sun/z_shot_sun.h
Labels: Needs lead approval

#1440 `z_obj_lift`: doc remaining funcs and field
  src/overlays/actors/ovl_Obj_Lift/z_obj_lift.c
  src/overlays/actors/ovl_Obj_Lift/z_obj_lift.h
Labels: Needs contributor approval

#1432 Small `Actor_UpdateAll` doc
  src/code/z_actor.c
Labels: Needs contributor approval, Needs lead approval

#1351 Document HREG debugging system
  include/regs.h
  src/code/PreRender.c
  src/code/game.c
  src/code/graph.c
  src/code/sched.c
  src/code/shrink_window.c
  src/code/z_actor.c
  src/code/z_kaleido_scope_call.c
  src/code/z_play.c
  src/code/z_rcp.c
  src/code/z_scene_table.c
  src/code/z_view.c
Labels: Needs contributor approval, Needs lead approval

#1435 Add skybox .h and cleanup, `SkyboxDraw_` -> `Skybox_`
  include/functions.h
  include/variables.h
  include/z64.h
  include/z64environment.h
  include/z64skybox.h
  src/code/z_play.c
  src/code/z_vr_box_draw.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
Labels: Needs contributor approval, Needs lead approval

#1447 Document Surface Material
  include/functions.h
  include/sfx.h
  include/z64bgcheck.h
  include/z64player.h
  src/code/z_actor.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_message_PAL.c
  src/overlays/actors/ovl_Bg_Hidan_Rock/z_bg_hidan_rock.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Ganondrof/z_boss_ganondrof.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im.c
  src/overlays/actors/ovl_En_Encount1/z_en_encount1.c
  src/overlays/actors/ovl_En_Js/z_en_js.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Sa/z_en_sa.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_En_Zl2/z_en_zl2.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_Obj_Oshihiki/z_obj_oshihiki.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs lead approval

#1448 Document Camera for Elevator Platforms (Camera_Special7)
  include/z64camera.h
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
  src/overlays/actors/ovl_Bg_Hidan_Fslift/z_bg_hidan_fslift.c
  src/overlays/actors/ovl_Bg_Hidan_Rock/z_bg_hidan_rock.c
  src/overlays/actors/ovl_Bg_Hidan_Syoku/z_bg_hidan_syoku.c
  src/overlays/actors/ovl_Bg_Jya_1flift/z_bg_jya_1flift.c
Labels: Needs contributor approval, Needs lead approval

#1434 Skelanime/Animation header cleanup
  include/functions.h
  include/macros.h
  include/z64.h
  include/z64animation.h
  include/z64animation_legacy.h
  src/code/z_skelanime.c
Labels: Needs contributor approval, Needs lead approval
