Repository zeldaret/oot, pull requests merged in 2023-01, with the labels that each got.

#1488 Fix misc 19
  include/ultra64/gbi.h
  include/z64.h
  include/z64item.h
  include/z64player.h
  src/code/code_800BB0A0.c
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
  src/code/z_message_PAL.c
  src/code/z_parameter.c
  src/code/z_player_lib.c
  src/code/z_sram.c
  src/libultra/io/sptask.c
  src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.h
  src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  src/overlays/actors/ovl_En_Gm/z_en_gm.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Skj/z_en_skj.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs contributor approval, Needs lead approval

#1482 DbCamera to DebugCamera
  include/functions.h
  include/regs.h
  include/variables.h
  include/z64camera.h
  src/code/db_camera.c
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
  src/code/z_debug.c
  src/code/z_demo.c
  src/code/z_play.c
  src/overlays/actors/ovl_En_Holl/z_en_holl.c
  src/overlays/actors/ovl_En_Ko/z_en_ko.c
  src/overlays/actors/ovl_En_Md/z_en_md.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs contributor approval

#1373 Document Bunny Hood 🐰
  src/overlays/actors/ovl_En_Mm/z_en_mm.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs lead approval

#1465 Document OnePointCutscene Init Field
  include/z64camera.h
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
  src/code/z_onepointdemo_data.inc.c
Labels: Needs contributor approval

#1490 Put comments on player's `sAgeProperties` with field name
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs contributor approval, Needs lead approval
