Repository zeldaret/oot, pull requests merged in 2024-03, with the labels that each got.

#1898 Mostly match retail bosses, part 1
  src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo.c
  src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
  src/overlays/actors/ovl_Boss_Fd2/z_boss_fd2.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
Labels: Met Review Requirements

#1824 No longer use asm-processor
  Makefile
  extract_assets.py
  include/z64cutscene.h
  include/z64cutscene_commands.h
  src/audio/general.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_1.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_2.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_3.c
  src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth_cutscene_data.c
  src/overlays/actors/ovl_Demo_Du/z_demo_du_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data1.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data2.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data3.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data4.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data5.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data6.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data7.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data8.c
  src/overlays/actors/ovl_Demo_Sa/z_demo_sa.c
  src/overlays/actors/ovl_Demo_Sa/z_demo_sa_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Jj/z_en_jj.c
  src/overlays/actors/ovl_En_Jj/z_en_jj_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Nb/z_en_nb_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag_cutscene_data.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1_cutscene_data.c
  tools/ZAPD/.github/workflows/main.yml
  tools/ZAPD/.gitrepo
  tools/ZAPD/README.md
  tools/ZAPD/ZAPD/GameConfig.cpp
  tools/ZAPD/ZAPD/GameConfig.h
  tools/ZAPD/ZAPD/Globals.h
  tools/ZAPD/ZAPD/Main.cpp
  tools/ZAPD/ZAPD/OtherStructs/CutsceneMM_Commands.cpp
  tools/ZAPD/ZAPD/OtherStructs/CutsceneMM_Commands.h
  tools/ZAPD/ZAPD/OtherStructs/CutsceneOoT_Commands.cpp
  tools/ZAPD/ZAPD/ZAPD.vcxproj
  tools/ZAPD/ZAPD/ZAPD.vcxproj.filters
  tools/ZAPD/ZAPD/ZCKeyFrame.cpp
  tools/ZAPD/ZAPD/ZCKeyFrame.h
  tools/ZAPD/ZAPD/ZCKeyFrameAnim.cpp
  tools/ZAPD/ZAPD/ZCkeyFrameAnim.h
  tools/ZAPD/ZAPD/ZCutscene.cpp
  tools/ZAPD/ZAPD/ZCutscene.h
  tools/ZAPD/ZAPD/ZResource.h
  tools/csdis.py
  tools/csdis_re.py
  tools/reencode.sh
Labels: Needs second approval

#1707 Add script to print block numbers for BSS ordering
  tools/ido_block_numbers.py
Labels: Met Review Requirements

#1730 Introduce extracted/VERSION, with text extracted there
  .gitignore
  Makefile
  assets/.gitignore
  assets/text/fra_message_data_static.c
  assets/text/ger_message_data_static.c
  assets/text/message_data.h
  assets/text/message_data_staff.h
  assets/text/nes_message_data_static.c
  docs/vscode.md
  include/message_data_static.h
  src/code/z_message_PAL.c
  tools/msgdis.py
  tools/msgenc.py
Labels: Needs second approval

#1906 Match retail EnNiw_Update
  src/overlays/actors/ovl_En_Niw/z_en_niw.c
Labels: Met Review Requirements

#1911 Build fixups: build gc-eu-mq with extracted/dbg, remove asmproc pragmas
  Makefile
  src/overlays/actors/ovl_Demo_Du/z_demo_du.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im.c
Labels: Needs second approval

#1721 Hacks for building nes_font_static and nes_message_data_static with gc-eu-mq
  Makefile
  spec
  tools/msgdis.py
Labels: Met Review Requirements

#1913 Remove reference to Cutscene_DrawDebugInfo in retail
  src/code/z_demo.c
Labels: Met Review Requirements

#1915 Match retail BossFd_DrawBody
  src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
Labels: Needs second approval

#1910 Remove 0xFF padding from uncompressed ROMs
  README.md
  baseroms/gc-eu-mq-dbg/checksum.md5
  baseroms/gc-eu-mq/checksum.md5
  tools/decompress_baserom.py
  tools/elf2rom.c
Labels: Met Review Requirements

#1905 Match retail z_fishing.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  tools/disasm/disasm.py
Labels: Met Review Requirements

#1909 Make distclean delete build artifacts for all versions
  Makefile
Labels: Met Review Requirements

#1916 Move baserom segments to extracted/
  Makefile
  extract_assets.py
  tools/csdis.py
  tools/csdis_re.py
  tools/msgdis.py
  tools/overlayhelpers/colliderinit.py
  tools/overlayhelpers/damage_table.py
  tools/overlayhelpers/lmapmark.py
  tools/overlayhelpers/mapmark.py
Labels: Met Review Requirements

#1919 mkldscript: Capture more special rodata sections for GCC
  tools/mkldscript.c
Labels: Met Review Requirements

#1920 Make BSS ordering script check ordering for all sections
  tools/check_ordering.py
Labels: Needs first approval, Needs second approval

#1924 Update fado
  tools/fado/.gitrepo
  tools/fado/Makefile
  tools/fado/include/mips_elf.h
  tools/fado/lib/fairy/fairy_print.c
  tools/fado/src/fado.c
  tools/fado/src/version.inc
Labels: Needs second approval

#1928 Document Player's Face and z_actor FaceChange functions
  assets/xml/objects/object_link_boy.xml
  assets/xml/objects/object_link_child.xml
  include/face_change.h
  include/functions.h
  include/z64actor.h
  include/z64player.h
  src/code/z_actor.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/gc-eu-mq/functions.txt
Labels: Met Review Requirements

#1929 More retail data fixes
  src/audio/general.c
  src/code/code_800FC620.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im.c
  src/overlays/actors/ovl_Demo_Sa/z_demo_sa.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
Labels: Met Review Requirements

#1930 Extract unused scene headers
  assets/xml/scenes/dungeons/ganon_tou.xml
  assets/xml/scenes/dungeons/jyasinzou.xml
  assets/xml/scenes/indoors/daiyousei_izumi.xml
  assets/xml/scenes/indoors/hairal_niwa.xml
  assets/xml/scenes/misc/hiral_demo.xml
  assets/xml/scenes/overworld/spot00.xml
  assets/xml/scenes/overworld/spot15.xml
  assets/xml/scenes/overworld/spot16.xml
  include/z64cutscene_commands.h
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_1.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_2.c
  src/overlays/actors/ovl_Demo_Du/z_demo_du_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Nb/z_en_nb_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2_cutscene_data.inc.c
  tools/ZAPD/.github/workflows/main.yml
  tools/ZAPD/.gitrepo
  tools/ZAPD/ZAPD/OtherStructs/CutsceneOoT_Commands.cpp
  tools/ZAPD/ZAPD/ZCutscene.cpp
  tools/csdis.py
Labels: Met Review Requirements

#1931 Match retail ovl_kaleido_scope
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map_PAL.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
  src/overlays/misc/ovl_kaleido_scope/z_lmap_mark.c
Labels: Met Review Requirements

#1932 Rework rom_header.s
  src/makerom/rom_header.h
  src/makerom/rom_header.s
Labels: Met Review Requirements

#1933 Player: targetActor -> talkActor
  include/z64player.h
  src/code/z_actor.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: Met Review Requirements

#1935 Use `gcc -E` instead of `cpp` to fix macOS build
  Makefile
Labels: Met Review Requirements

#1918 Line up code segment for gc-eu-mq
  spec
  tools/mkldscript.c
Labels: Met Review Requirements

#1921 Fix various data issues in gc-eu-mq
  src/audio/general.c
  src/code/graph.c
  src/code/z_message_PAL.c
  src/code/z_play.c
Labels: Met Review Requirements

#1934 Document en_ba damage bug
  src/overlays/actors/ovl_En_Ba/z_en_ba.c
Labels: Needs second approval

#1917 Match retail camera
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
Labels: Met Review Requirements
