Repository zeldaret/oot, pull requests merged in 2024-01, with the labels that each got.

#1591 Create separate build directories based on version
  Jenkinsfile
  Makefile
  README.md
  checksum.md5
  diff_settings.py
  docs/tutorial/beginning_decomp.md
  docs/tutorial/data.md
  docs/tutorial/merging.md
  docs/tutorial/object_decomp.md
  docs/tutorial/object_decomp_example.md
  docs/vscode.md
  first_diff.py
  format.py
  progress.py
  spec
  sym_info.py
  tools/assist.py
  tools/find_unused_asm.sh
Labels: Needs second approval

#1586 Introduce Face Reaction Enum
  include/functions.h
  include/z64message.h
  src/code/z_face_reaction.c
  src/overlays/actors/ovl_En_Ani/z_en_ani.c
  src/overlays/actors/ovl_En_Cs/z_en_cs.c
  src/overlays/actors/ovl_En_Daiku_Kakariko/z_en_daiku_kakariko.c
  src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.c
  src/overlays/actors/ovl_En_Du/z_en_du.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/actors/ovl_En_Ge1/z_en_ge1.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Heishi2/z_en_heishi2.c
  src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
  src/overlays/actors/ovl_En_Hs2/z_en_hs2.c
  src/overlays/actors/ovl_En_Hy/z_en_hy.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Ko/z_en_ko.c
  src/overlays/actors/ovl_En_Kz/z_en_kz.c
  src/overlays/actors/ovl_En_Ma1/z_en_ma1.c
  src/overlays/actors/ovl_En_Ma2/z_en_ma2.c
  src/overlays/actors/ovl_En_Md/z_en_md.c
  src/overlays/actors/ovl_En_Mk/z_en_mk.c
  src/overlays/actors/ovl_En_Mm/z_en_mm.c
  src/overlays/actors/ovl_En_Ms/z_en_ms.c
  src/overlays/actors/ovl_En_Mu/z_en_mu.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Sa/z_en_sa.c
  src/overlays/actors/ovl_En_Skj/z_en_skj.c
  src/overlays/actors/ovl_En_Ssh/z_en_ssh.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_En_Tg/z_en_tg.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_En_Toryo/z_en_toryo.c
  src/overlays/actors/ovl_En_Zl4/z_en_zl4.c
  src/overlays/actors/ovl_En_Zo/z_en_zo.c
Labels: Met Review Requirements

#1608 Makefile: Change `EMULATOR :=` to `N64_EMULATOR ?=`
  Makefile
Labels: Needs second approval

#1607 Add `OOT_DEBUG` define to `vscode.md`
  docs/vscode.md
Labels: Needs second approval

#1602 Removed unused imports and other minor improvements
  first_diff.py
  format.py
  progress.py
  sym_info.py
  tools/convert_chars.py
  tools/decompile_data.py
  tools/ichaindis.py
  tools/overlayhelpers/colliderinit.py
  tools/overlayhelpers/damage_table.py
  tools/overlayhelpers/filemap.py
  tools/overlayhelpers/lmapmark.py
  tools/overlayhelpers/mapmark.py
  tools/sfxconvert.py
  tools/vt_fmt.py
Labels: Needs first approval, Needs second approval

#1583 Name actor flags 1: `ACTOR_FLAG_REACT_TO_LENS`, `ACTOR_FLAG_IGNORE_POINT_LIGHTS`
  include/z64actor.h
  src/code/z_actor.c
  src/overlays/actors/ovl_Bg_Bombwall/z_bg_bombwall.c
  src/overlays/actors/ovl_Bg_Gnd_Darkmeiro/z_bg_gnd_darkmeiro.c
  src/overlays/actors/ovl_Bg_Gnd_Nisekabe/z_bg_gnd_nisekabe.c
  src/overlays/actors/ovl_Bg_Haka_Gate/z_bg_haka_gate.c
  src/overlays/actors/ovl_Bg_Haka_Megane/z_bg_haka_megane.c
  src/overlays/actors/ovl_Bg_Haka_MeganeBG/z_bg_haka_meganebg.c
  src/overlays/actors/ovl_Bg_Haka_Sgami/z_bg_haka_sgami.c
  src/overlays/actors/ovl_Bg_Menkuri_Nisekabe/z_bg_menkuri_nisekabe.c
  src/overlays/actors/ovl_Bg_Spot02_Objects/z_bg_spot02_objects.c
  src/overlays/actors/ovl_Bg_Spot08_Bakudankabe/z_bg_spot08_bakudankabe.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_En_Box/z_en_box.c
  src/overlays/actors/ovl_En_Dh/z_en_dh.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Po_Desert/z_en_po_desert.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_En_St/z_en_st.c
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_Obj_Bean/z_obj_bean.c
Labels: Needs second approval

#1610 Create debug macros for LogUtils functions
  include/macros.h
  src/code/PreRender.c
  src/code/game.c
  src/code/gamealloc.c
  src/code/irqmgr.c
  src/code/mtxuty-cvt.c
  src/code/padmgr.c
  src/code/sched.c
  src/code/speed_meter.c
  src/code/z_kaleido_manager.c
  src/code/z_map_mark.c
  src/code/z_view.c
Labels: Met Review Requirements

#1611 Remove actor padding in non-debug versions
  include/z64actor.h
Labels: Met Review Requirements

#1612 Test for __sgi instead of __GNUC__ for PRINTF macro
  include/macros.h
Labels: Met Review Requirements

#1433 Small `Math_Vec3f_Yaw` doc
  include/functions.h
  src/code/z_actor.c
  src/code/z_lib.c
  src/code/z_onepointdemo.c
Labels: Met Review Requirements

#1614 Setup rom decompression and compression
  .gitignore
  Jenkinsfile
  Makefile
  README.md
  baseroms/gc-eu-mq-dbg/checksum-compressed.md5
  baseroms/gc-eu-mq-dbg/checksum.md5
  data/audio_tables.rodata.s
  data/rsp.rodata.s
  data/rsp.text.s
  data/rsp_boot.text.s
  data/z_text.data.s
  diff_settings.py
  docs/tutorial/beginning_decomp.md
  docs/tutorial/data.md
  docs/vscode.md
  extract_assets.py
  extract_baserom.py
  first_diff.py
  fixbaserom.py
  requirements.txt
  spec
  src/makerom/ipl3.s
  tools/assist.py
  tools/compress.py
  tools/csdis.py
  tools/decompress_baserom.py
  tools/disasm_elf_msg.py
  tools/dmadata_range.sh
  tools/mkdmadata.c
  tools/msgdis.py
  tools/overlayhelpers/colliderinit.py
  tools/overlayhelpers/damage_table.py
  tools/overlayhelpers/lmapmark.py
  tools/overlayhelpers/mapmark.py
  tools/spec.c
  tools/spec.h
Labels: Needs second approval

#1617 Fix mkdmadata usage
  tools/mkdmadata.c
Labels: Met Review Requirements

#1618 Suggest pip install -U -r requirements.txt
  README.md
Labels: Needs second approval

#1619 Use virtualenv in Makefile for python dependencies
  Jenkinsfile
  Makefile
  README.md
  docs/tutorial/helper_scripts.md
Labels: Met Review Requirements

#1622 Delete venv if venv creation fails
  Makefile
Labels: Needs first approval, Needs second approval

#1613 Set up disassembly for gc-eu-mq
  Makefile
  baseroms/gc-eu-mq/checksum-compressed.md5
  baseroms/gc-eu-mq/checksum.md5
  diff_settings.py
  docs/retail_versions.md
  first_diff.py
  include/macro.inc
  requirements.txt
  retail_progress.py
  sym_info.py
  tools/decompress_baserom.py
  tools/disasm/disasm.py
  tools/disasm/file_addresses.py
  tools/disasm/gc-eu-mq/file_addresses.csv
  tools/disasm/gc-eu-mq/files_boot.csv
  tools/disasm/gc-eu-mq/files_code.csv
  tools/disasm/gc-eu-mq/files_ovl_file_choose.csv
  tools/disasm/gc-eu-mq/files_ovl_kaleido_scope.csv
  tools/disasm/gc-eu-mq/functions.txt
  tools/disasm/gc-eu-mq/variables.txt
  tools/disasm/list_generated_files.py
Labels: Met Review Requirements

#1639 z_en_bom.c OK
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
Labels: Met Review Requirements

#1640 z_en_dodongo.c OK
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
Labels: Met Review Requirements

#1645 Match ``main.c`` - OK
  src/code/main.c
Labels: Needs second approval

#1649 `z_parameter` retail OK
  src/code/z_collision_check.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_En_Honotrap/z_en_honotrap.c
Labels: Needs second approval

#1643 idle.c OK
  src/boot/idle.c
Labels: Needs first approval, Needs second approval

#1647 Tweak OPTFLAGS for some files for retail
  Makefile
Labels: Needs first approval, Needs second approval

#1641 is_debug.c and boot_main.c OK
  include/functions.h
  src/boot/boot_main.c
  src/boot/is_debug.c
Labels: Needs second approval

#1644 Match ``game.c`` - OK
  include/functions.h
  include/macros.h
  src/code/game.c
Labels: Met Review Requirements

#1658 Define OOT_DEBUG=0 in retail builds
  Makefile
  docs/retail_versions.md
  include/functions.h
  include/macros.h
  include/ultra64/gbi.h
  include/z64actor.h
  src/boot/boot_main.c
  src/boot/idle.c
  src/boot/is_debug.c
  src/code/game.c
  src/code/main.c
  src/code/sys_matrix.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
Labels: Needs first approval, Needs second approval

#1664 subrepo and update asm-differ
  diff.py
  tools/asm-differ/.github/workflows/black.yml
  tools/asm-differ/.github/workflows/check-poetry-lock.yml
  tools/asm-differ/.github/workflows/unit-tests.yml
  tools/asm-differ/.gitignore
  tools/asm-differ/.gitrepo
  tools/asm-differ/.pre-commit-config.yaml
  tools/asm-differ/LICENSE
  tools/asm-differ/README.md
  tools/asm-differ/diff-stylesheet.css
  tools/asm-differ/diff.py
  tools/asm-differ/diff_settings.py
  tools/asm-differ/mypy.ini
  tools/asm-differ/poetry.lock
  tools/asm-differ/pyproject.toml
  tools/asm-differ/screenshot.png
  tools/asm-differ/test.py
Labels: Met Review Requirements

#1650 Audio retail OK
  include/sfx.h
  src/audio/debug.inc.c
  src/audio/general.c
  src/audio/sequence.c
  src/audio/sfx.c
Labels: Met Review Requirements

#1655 z_demo retail code matched
  include/z64save.h
  src/code/z_demo.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd.c
Labels: Needs second approval

#1669 Fixup vscode settings
  docs/vscode.md
Labels: Needs second approval

#1662 Overlay_Relocate and Overlay_Load retail OK
  Makefile
  include/functions.h
  include/ultra64/libc.h
  src/code/load.c
  src/code/relocation.c
Labels: Met Review Requirements

#1642 z_collision_check.c OK
  include/functions.h
  src/code/z_actor.c
  src/code/z_bgcheck.c
  src/code/z_collision_check.c
Labels: Met Review Requirements

#1665 Match retail z_std_dma.c
  include/z64dma.h
  src/boot/z_std_dma.c
Labels: Met Review Requirements

#1672 Remove double #endif in PRINTF macro definition
  include/macros.h
Labels: Met Review Requirements

#1670 z_actor retail OK
  include/regs.h
  include/z64actor.h
  src/code/z_actor.c
Labels: Met Review Requirements

#1674 Match retail sys_math3d.c
  src/code/sys_math3d.c
Labels: Met Review Requirements

#1673 Only check formatting on modified files
  Jenkinsfile
  format.py
  tools/check_format.sh
Labels: Met Review Requirements

#1680 Check format: only check modified files, v2
  Jenkinsfile
  format.py
  tools/check_format.py
  tools/check_format.sh
Labels: Needs first approval, Needs second approval

#1399 Document Audio Thread Commands
  include/audiothread_cmd.h
  include/functions.h
  include/seqcmd.h
  include/sfx.h
  include/variables.h
  include/z64.h
  include/z64audio.h
  src/audio/debug.inc.c
  src/audio/general.c
  src/audio/lib/effects.c
  src/audio/lib/heap.c
  src/audio/lib/load.c
  src/audio/lib/playback.c
  src/audio/lib/seqplayer.c
  src/audio/lib/synthesis.c
  src/audio/lib/thread.c
  src/audio/sequence.c
  src/audio/session_config.c
  src/audio/sfx.c
  src/code/audio_thread_manager.c
  src/code/game.c
  src/code/graph.c
  src/code/speed_meter.c
  tools/disasm/gc-eu-mq/functions.txt
  tools/disasm/gc-eu-mq/variables.txt
Labels: Met Review Requirements
