Repository zeldaret/oot, pull requests merged in 2024-12, with the labels that each got.

#2308 Minor Cleanup
  include/z64player.h
  src/overlays/actors/ovl_En_Torch2/z_en_torch2.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2311 More descriptive names for CS_BEGIN_CUTSCENE and CS_END
  include/z64cutscene.h
  include/z64cutscene_commands.h
  src/code/z_demo.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_1.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_2.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_3.c
  src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth_cutscene_data.c
  src/overlays/actors/ovl_Demo_Du/z_demo_du_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data1.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data2.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data3.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data4.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data5.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data6.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data7.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo_cutscene_data8.c
  src/overlays/actors/ovl_Demo_Sa/z_demo_sa_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Jj/z_en_jj_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Nb/z_en_nb_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag_cutscene_data.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1_cutscene_data.c
  tools/ZAPD/.gitrepo
  tools/ZAPD/ZAPD/ZCKeyFrame.cpp
  tools/ZAPD/ZAPD/ZCutscene.cpp
  tools/ZAPDConfigs/EnumData.xml
  tools/csdis.py
Labels: Met Review Requirements

#2317 Name missing actor cue lists command types in actor cutscenes
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_3.c
  src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth_cutscene_data.c
  src/overlays/actors/ovl_Demo_Du/z_demo_du_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Sa/z_demo_sa_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Jj/z_en_jj_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Nb/z_en_nb_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag_cutscene_data.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1_cutscene_data.c
Labels: Needs second approval

#2288 Rename and document Adult Ruto functions
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.h
  src/overlays/actors/ovl_En_Ru2/z_en_ru2_cutscene_data.inc.c
  tools/csdis_re.py
Labels: Needs second approval

#2316 Name asset extraction tools more consistently
  Makefile
  tools/extract_assets.py
  tools/extract_audio.py
  tools/extract_text.py
Labels: Met Review Requirements

#2323 Ru2 fixes
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.h
Labels: Needs first approval, Needs second approval

#2321 Name some scene cutscenes (Hyrule Field and Kakariko Village)
  assets/xml/scenes/overworld/spot00.xml
  assets/xml/scenes/overworld/spot00_pal_n64.xml
  assets/xml/scenes/overworld/spot01.xml
  assets/xml/scenes/overworld/spot01_pal_n64.xml
Labels: Met Review Requirements

#2325 Renamed EVENTCHKINF_3A
  include/z64save.h
  src/overlays/actors/ovl_En_Jj/z_en_jj.c
Labels: Met Review Requirements

#2322 Rename EVENTCHKINF_02
  include/z64save.h
  src/code/z_actor.c
  src/overlays/actors/ovl_En_Md/z_en_md.c
  src/overlays/actors/ovl_En_Sa/z_en_sa.c
Labels: Met Review Requirements

#2327 Replaced EVENTCHKINF_4E
  include/z64save.h
  src/overlays/actors/ovl_En_Heishi1/z_en_heishi1.c
  src/overlays/actors/ovl_En_Heishi3/z_en_heishi3.c
Labels: Met Review Requirements

#2328 Renamed EVENTCHKINF_4B
  include/z64save.h
  src/overlays/actors/ovl_Bg_Toki_Hikari/z_bg_toki_hikari.c
  src/overlays/actors/ovl_Demo_Effect/z_demo_effect.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_Door_Toki/z_door_toki.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
Labels: Met Review Requirements

#2320 Name Sleeping Waterfall state machine function
  src/overlays/actors/ovl_Bg_Spot03_Taki/z_bg_spot03_taki.c
Labels: Met Review Requirements

#2307 Document Player Params
  include/z64actor.h
  include/z64player.h
  src/code/z_actor.c
  src/code/z_play.c
  src/overlays/actors/ovl_Door_Ana/z_door_ana.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs second approval

#2312 Use MM decomp names for some unnamed code files
  docs/libu64.md
  spec
  src/code/z_bg_collect.c
  src/code/z_bg_item.c
  src/code/z_env_flags.c
  src/code/z_inventory.c
  src/libu64/system_heap.c
Labels: Met Review Requirements

#2313 Rename code_800BB0A0.c -> z_cutscene_spline.c
  spec
  src/code/z_cutscene_spline.c
Labels: Met Review Requirements

#2314 Rename code_80069420.c -> z_memory_utils.c
  spec
  src/code/z_memory_utils.c
Labels: Met Review Requirements

#2315 Split code_800D31A0.c into sys_freeze.c and sys_debug_controller.c
  spec
  src/code/code_800D31A0.c
  src/code/sys_debug_controller.c
  src/code/sys_freeze.c
Labels: Met Review Requirements

#2319 Add names for Medallion cutscene data
  src/overlays/actors/ovl_Demo_Du/z_demo_du.c
  src/overlays/actors/ovl_Demo_Du/z_demo_du_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im.c
  src/overlays/actors/ovl_Demo_Im/z_demo_im_cutscene_data.inc.c
  src/overlays/actors/ovl_Demo_Sa/z_demo_sa.c
  src/overlays/actors/ovl_Demo_Sa/z_demo_sa_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Nb/z_en_nb_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2_cutscene_data.inc.c
  tools/csdis_re.py
Labels: Met Review Requirements

#2329 Rename EVENTCHKINF_4D
  include/z64save.h
  src/overlays/actors/ovl_Bg_Gjyo_Bridge/z_bg_gjyo_bridge.c
Labels: Met Review Requirements

#2326 Renamed EVENTCHKINF_33
  include/z64save.h
  src/code/z_actor.c
  src/elf_message/elf_message_field.c
  src/overlays/actors/ovl_En_Kz/z_en_kz.c
  src/overlays/actors/ovl_En_Zo/z_en_zo.c
Labels: Met Review Requirements

#2332 Rename symbols related to Kakariko Well being drained
  include/z64cutscene.h
  include/z64save.h
  src/code/z_demo.c
  src/overlays/actors/ovl_Bg_Spot01_Idomizu/z_bg_spot01_idomizu.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  tools/ZAPDConfigs/EnumData.xml
  tools/csdis.py
Labels: Met Review Requirements

#2335 Rename "temp" variables in Adult Ruto functions
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
Labels: Met Review Requirements

#2324 Renamed EVENTCHKINF_3C
  include/z64save.h
  src/overlays/actors/ovl_En_Ik/z_en_ik.c
Labels: Met Review Requirements

#2330 Rename EVENTCHKINF_69
  include/z64cutscene.h
  include/z64save.h
  src/code/z_demo.c
  src/code/z_scene_table.c
  src/overlays/actors/ovl_Bg_Spot06_Objects/z_bg_spot06_objects.c
  tools/ZAPDConfigs/EnumData.xml
  tools/csdis.py
Labels: Needs second approval

#2333 Rename item get flags for Forest Stage upgrades
  include/z64save.h
  src/code/z_parameter.c
  src/overlays/actors/ovl_En_Dnt_Demo/z_en_dnt_demo.c
  src/overlays/actors/ovl_En_Dnt_Jiji/z_en_dnt_jiji.c
Labels: Needs first approval, Needs second approval

#2338 Name Kokiri Forest cutscenes (and related ones)
  assets/xml/scenes/dungeons/jyasinzou.xml
  assets/xml/scenes/dungeons/jyasinzou_mq.xml
  assets/xml/scenes/misc/hiral_demo.xml
  assets/xml/scenes/misc/hiral_demo_pal_n64.xml
  assets/xml/scenes/overworld/spot04.xml
  assets/xml/scenes/overworld/spot04_pal_n64.xml
  assets/xml/scenes/overworld/spot09.xml
  assets/xml/scenes/overworld/spot09_pal_n64.xml
  src/code/z_demo.c
  src/overlays/actors/ovl_En_Sa/z_en_sa.c
Labels: Needs second approval

#2331 Rename EVENTCHKINF flags for payments to Happy Mask salesman
  include/z64save.h
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
Labels: Met Review Requirements

#2356 Naming some cutscenes 4 (Gerudo Fortress, Death Mountain Crater and Goron City)
  assets/xml/scenes/overworld/spot12.xml
  assets/xml/scenes/overworld/spot12_pal_n64.xml
  assets/xml/scenes/overworld/spot17.xml
  assets/xml/scenes/overworld/spot17_pal_n64.xml
  assets/xml/scenes/overworld/spot18.xml
  assets/xml/scenes/overworld/spot18_pal_n64.xml
  src/overlays/actors/ovl_En_Du/z_en_du.c
Labels: Needs second approval

#2355 Name some cutscenes 3 (Zora's Domain, Zora's Fountain, Lost Woods and Desert Colossus)
  assets/xml/scenes/overworld/spot07.xml
  assets/xml/scenes/overworld/spot07_pal_n64.xml
  assets/xml/scenes/overworld/spot08.xml
  assets/xml/scenes/overworld/spot10.xml
  assets/xml/scenes/overworld/spot11.xml
  assets/xml/scenes/overworld/spot11_pal_n64.xml
Labels: Met Review Requirements

#2359 Naming cutscenes from Lon-Lon Ranch
  assets/xml/scenes/overworld/spot20.xml
  assets/xml/scenes/overworld/spot20_pal.xml
  include/z64cutscene.h
  src/code/z_demo.c
  tools/ZAPDConfigs/EnumData.xml
  tools/csdis.py
Labels: Met Review Requirements

#2337 [Audio 10/10] Loose ends
  Makefile
  docs/audio/Samplebank_XML.md
  docs/audio/Soundfont_XML.md
  docs/audio/build_flowchart.png
  include/audio/aseq.h
  include/libc/assert.h
  include/sfx.h
  linker_scripts/soundfont.ld
  src/audio/session_config.c
  src/boot/z_std_dma.c
  src/code/fault_gc.c
  src/code/graph.c
  src/code/main.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_debug.c
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/audio/.gitignore
  tools/audio/Makefile
  tools/audio/README.md
  tools/audio/afile_sizes.c
  tools/audio/aifc.c
  tools/audio/audio_tablegen.c
  tools/audio/extraction/disassemble_sequence.py
  tools/audio/extraction/extraction_xml.py
  tools/audio/samplebank_compiler.c
  tools/audio/sampleconv/Makefile
  tools/audio/sampleconv/src/codec/vadpcm.c
  tools/audio/sampleconv/src/codec/vadpcm_tabledesign.c
  tools/audio/sampleconv/src/container/aiff.c
  tools/audio/sampleconv/src/container/wav.c
  tools/audio/soundfont_compiler.c
  tools/audio/util.c
Labels: Met Review Requirements

#2353 Move build.c definitions to the makefile, introduce and use libultra version defines in libultra instead of PLATFORM defines
  Makefile
  format.py
  include/ultra64.h
  include/ultra64/version.h
  src/boot/build.c
  src/libultra/gu/rotate.c
  src/libultra/os/exceptasm.s
  src/libultra/os/initialize.c
  src/libultra/os/settimer.c
  src/libultra/os/timerintr.c
  src/makerom/rom_header.h
  src/makerom/rom_header.s
Labels: Met Review Requirements

#2361 Name cutscenes from dungeons (Spirit Boss Room, Jabu-Jabu's Belly and Ganon)
  assets/xml/scenes/dungeons/bdan.xml
  assets/xml/scenes/dungeons/bdan_mq.xml
  assets/xml/scenes/dungeons/ganon_demo.xml
  assets/xml/scenes/dungeons/jyasinboss.xml
  src/code/z_demo.c
Labels: Met Review Requirements

#2362 Name indoors cutscenes (Chamber of Sages, Courtyard, Link's House and Shooting Gallery)
  assets/xml/scenes/indoors/kenjyanoma.xml
  assets/xml/scenes/indoors/link_home.xml
  assets/xml/scenes/indoors/nakaniwa.xml
  assets/xml/scenes/indoors/syatekijyou.xml
Labels: Met Review Requirements

#2358 rename `func_8002F368`, a getter for `struct Player -> exchangeItemId`
  include/z64actor.h
  src/code/z_actor.c
  src/overlays/actors/ovl_En_Ds/z_en_ds.c
  src/overlays/actors/ovl_En_Gb/z_en_gb.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Heishi2/z_en_heishi2.c
  src/overlays/actors/ovl_En_Hs/z_en_hs.c
  src/overlays/actors/ovl_En_Hy/z_en_hy.c
  src/overlays/actors/ovl_En_Ko/z_en_ko.c
  src/overlays/actors/ovl_En_Kz/z_en_kz.c
  src/overlays/actors/ovl_En_Mk/z_en_mk.c
  src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_En_Toryo/z_en_toryo.c
  src/overlays/actors/ovl_Obj_Bean/z_obj_bean.c
Labels: Needs first approval, Needs second approval

#2339 Name some scene cutscenes 2 (Graveyard, Meadow and Lake Hylia)
  assets/xml/scenes/overworld/spot02.xml
  assets/xml/scenes/overworld/spot05.xml
  assets/xml/scenes/overworld/spot05_pal_n64.xml
  assets/xml/scenes/overworld/spot06.xml
  assets/xml/scenes/overworld/spot06_pal_n64.xml
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
  src/overlays/actors/ovl_En_Sa/z_en_sa.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
Labels: Met Review Requirements

#2357 Name cutscenes from Death Mountain Trail
  assets/xml/scenes/overworld/spot16.xml
  assets/xml/scenes/overworld/spot16_pal_n64.xml
  assets/xml/scenes/overworld/spot16_v2.xml
Labels: Met Review Requirements

#2365 Add macros for line number differences
  include/line_numbers.h
  src/boot/z_locale.c
  src/boot/z_std_dma.c
  src/code/game.c
  src/code/graph.c
  src/code/padmgr.c
  src/code/sys_cfb.c
  src/code/z_bgcheck.c
  src/code/z_play.c
  src/code/z_room.c
  src/n64dd/z_n64dd.c
  src/overlays/actors/ovl_En_Horse_Game_Check/z_en_horse_game_check.c
  src/overlays/effects/ovl_Effect_Ss_Kakera/z_eff_ss_kakera.c
Labels: Met Review Requirements

#2370 Fix macOS build
  Makefile
Labels: Met Review Requirements

#2371 Remove ‾ character from source files
  assets/text/charmap.txt
  src/code/PreRender.c
  src/code/z_message.c
  src/overlays/actors/ovl_Bg_Gnd_Iceblock/z_bg_gnd_iceblock.c
  tools/extract_text.py
Labels: Met Review Requirements

#2366 Name cutscenes of remaining actors
  assets/xml/scenes/dungeons/bdan.xml
  assets/xml/scenes/dungeons/bdan_mq.xml
  src/overlays/actors/ovl_En_Jj/z_en_jj.c
  src/overlays/actors/ovl_En_Jj/z_en_jj_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag_cutscene_data.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1_cutscene_data.inc.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1_cutscene_data.c
Labels: Met Review Requirements

#2372 Dockerfile Update
  Dockerfile
Labels: Met Review Requirements

#2373 Docker Build Change Proposal
  Dockerfile
  docker-compose.yml
  docs/BUILDING_DOCKER.md
Labels: Met Review Requirements

#2364 Name cutscenes from the Master Sword and Deku Tree Mouth actors
  include/z64save.h
  src/code/z_demo.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_1.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_2.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd_cutscene_data_3.c
  src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth.c
  src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth_cutscene_data.c
Labels: Needs second approval

#2368 Fix inverted cutscene offsets in `kenjyanoma.xml`
  assets/xml/scenes/indoors/kenjyanoma.xml
Labels: Needs second approval

#2376 Rename event check flags for boss battles
  include/z64save.h
  src/overlays/actors/ovl_Boss_Dodongo/z_boss_dodongo.c
  src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Goma/z_boss_goma.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_fHG/z_en_fhg.c
Labels: Needs second approval

#2377 Reformat item00 drop tables
  src/code/z_en_item00.c
Labels: Needs second approval

#2278 Document z_horse.c and related actors
  include/functions.h
  include/regs.h
  include/z64actor.h
  include/z64horse.h
  include/z64save.h
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_horse.c
  src/code/z_message.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/overlays/actors/ovl_Bg_Ingate/z_bg_ingate.c
  src/overlays/actors/ovl_Bg_Umajump/z_bg_umajump.c
  src/overlays/actors/ovl_En_Ge1/z_en_ge1.c
  src/overlays/actors/ovl_En_Ge2/z_en_ge2.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.h
  src/overlays/actors/ovl_En_Horse_Game_Check/z_en_horse_game_check.c
  src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.c
  src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.h
  src/overlays/actors/ovl_En_Horse_Normal/z_en_horse_normal.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_Oceff_Spot/z_oceff_spot.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2381 Split some data from src/audio/session_config.c into src/audio/session_init.c
  Makefile
  include/variables.h
  spec
  src/audio/lib/load.c
  src/audio/session_config.c
  src/audio/session_init.c
Labels: Met Review Requirements

#2380 Restructure event flags in z64save.h (1/?)
  include/z64save.h
  src/code/z_inventory.c
  src/code/z_map_exp.c
  src/code/z_parameter.c
  src/code/z_sram.c
  src/overlays/actors/ovl_Bg_Dy_Yoseizo/z_bg_dy_yoseizo.c
  src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c
  src/overlays/actors/ovl_En_Daiku/z_en_daiku.c
  src/overlays/actors/ovl_En_Fr/z_en_fr.c
  src/overlays/actors/ovl_En_Ge2/z_en_ge2.c
  src/overlays/actors/ovl_En_Hy/z_en_hy.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Mu/z_en_mu.c
  src/overlays/actors/ovl_En_Niw/z_en_niw.c
  src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.c
  src/overlays/actors/ovl_En_Sth/z_en_sth.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
Labels: Needs second approval

#2379 Fix editing PATH in macOS build instructions
  docs/BUILDING_MACOS.md
Labels: Needs second approval

#2387 Move D_80134488 from system_heap.c to fp.s
  include/libc/math.h
  src/code/sys_math3d.c
  src/libc64/fp.s
  src/libu64/system_heap.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2383 iQue text extraction
  Makefile
  assets/text/charmap.chn.txt
  assets/text/charmap.jpn.txt
  assets/text/charmap.nes.txt
  assets/text/charmap.txt
  assets/xml/textures/nes_font_static_ique_cn.xml
  baseroms/ique-cn/config.yml
  tools/extract_text.py
  tools/msgenc.py
Labels: Met Review Requirements

#2386 Fix iQue audio and line numbers
  assets/audio/sequences/seq_109.prg.seq
  include/line_numbers.h
  src/audio/general.c
  src/audio/lib/seqplayer.c
  src/audio/lib/synthesis.c
  src/audio/lib/thread.c
  src/audio/session_init.c
  src/audio/sfx.c
  src/boot/z_locale.c
  src/code/game.c
  src/code/graph.c
  src/code/sys_cfb.c
  src/code/z_eff_ss_dead.c
  src/code/z_room.c
Labels: Needs second approval

#2389 Match iQue compression
  Makefile
  requirements.txt
  tools/compress.py
Labels: Met Review Requirements

#2385 Restructure event flags in z64save.h (2/?): Carpenters
  include/z64save.h
  src/code/z_map_exp.c
  src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c
  src/overlays/actors/ovl_En_Daiku/z_en_daiku.c
  src/overlays/actors/ovl_En_Daiku/z_en_daiku.h
  src/overlays/actors/ovl_En_Ge1/z_en_ge1.c
  src/overlays/actors/ovl_En_Ge2/z_en_ge2.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Mm2/z_en_mm2.c
  src/overlays/actors/ovl_En_Toryo/z_en_toryo.c
Labels: Met Review Requirements, wait

#2390 Use IDO for assembling handwritten asm files in src
  Makefile
  include/ultra64/R4300.h
  include/ultra64/asm.h
  include/ultra64/exception.h
  include/ultra64/message.h
  include/ultra64/rcp.h
  include/ultra64/regdef.h
  include/ultra64/thread.h
  src/boot/mio0.s
  src/code/kanread.s
  src/code/z_vimode.c
  src/libc/absf.s
  src/libc/sqrt.s
  src/libc64/fp.s
  src/libleo/api/getaadr.s
  src/libleo/api/getaadr2.s
  src/libleo/api/getkadr.s
  src/libultra/gu/libm_vals.s
  src/libultra/io/vimodefpallan1.c
  src/libultra/io/vimodempallan1.c
  src/libultra/io/vimodentsclan1.c
  src/libultra/io/vimodepallan1.c
  src/libultra/libc/bcmp.s
  src/libultra/libc/bcopy.s
  src/libultra/libc/bzero.s
  src/libultra/mgu/mtxf2l.s
  src/libultra/mgu/mtxident.s
  src/libultra/mgu/mtxidentf.s
  src/libultra/mgu/mtxl2f.s
  src/libultra/mgu/normalize.s
  src/libultra/mgu/scale.s
  src/libultra/mgu/translate.s
  src/libultra/os/exceptasm.s
  src/libultra/os/getcause.s
  src/libultra/os/getcount.s
  src/libultra/os/getfpccsr.s
  src/libultra/os/getintmask.s
  src/libultra/os/getsr.s
  src/libultra/os/interrupt.s
  src/libultra/os/invaldcache.s
  src/libultra/os/invalicache.s
  src/libultra/os/maptlbrdb.s
  src/libultra/os/parameters.s
  src/libultra/os/probetlb.s
  src/libultra/os/setcompare.s
  src/libultra/os/setfpccsr.s
  src/libultra/os/setintmask.s
  src/libultra/os/setsr.s
  src/libultra/os/setwatchlo.s
  src/libultra/os/unmaptlball.s
  src/libultra/os/writebackdcache.s
  src/libultra/os/writebackdcacheall.s
  src/makerom/entry.s
  src/makerom/ipl3.s
Labels: Met Review Requirements

#2393 Add missing vimode splits in iQue disassembly
  src/libultra/io/vimodefpalhaf1.c
  src/libultra/io/vimodefpalhan1.c
  src/libultra/io/vimodefpalhpf1.c
  src/libultra/io/vimodefpalhpf2.c
  src/libultra/io/vimodefpalhpn1.c
  src/libultra/io/vimodefpalhpn2.c
  src/libultra/io/vimodefpallaf1.c
  src/libultra/io/vimodefpallaf2.c
  src/libultra/io/vimodefpallan2.c
  src/libultra/io/vimodefpallpf2.c
  src/libultra/io/vimodefpallpn2.c
  tools/disasm/ique-cn/files_code.csv
Labels: Met Review Requirements

#2392 Restructure event flags in z64save.h (3/?): Cursed Family Rewards
  include/z64save.h
  src/overlays/actors/ovl_En_Sth/z_en_sth.c
Labels: Met Review Requirements

#2391 Download EGCS binutils and gcc for iQue
  tools/.gitignore
  tools/Makefile
Labels: Met Review Requirements
