Repository zeldaret/oot, pull requests merged in 2024-06, with the labels that each got.

#1939 Change linker script so gGameOverTimer can be in z_game_over.c
  spec
  src/code/z_game_over.c
  src/code/z_message_PAL.c
  tools/mkldscript.c
  tools/spec.c
  tools/spec.h
Labels: Met Review Requirements

#1960 Check buffers segment in check_ordering.py
  tools/check_ordering.py
Labels: Met Review Requirements

#1959 Delete unused yaz0tool
  tools/Makefile
  tools/yaz0.c
  tools/yaz0.h
  tools/yaz0tool.c
Labels: Met Review Requirements

#1941 Revamp "AnimationContext" Docs, now called "AnimTaskQueue"
  include/z64.h
  include/z64animation.h
  src/code/z_play.c
  src/code/z_skelanime.c
  src/overlays/actors/ovl_Demo_Ec/z_demo_ec.c
  src/overlays/actors/ovl_Demo_Ik/z_demo_ik.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1.c
  src/overlays/actors/ovl_En_Zl4/z_en_zl4.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs first approval, Needs second approval

#1956 Experiment: remove global.h dependency from sys_math, sys_math3d, z_lib
  Makefile
  include/fp_math.h
  include/functions.h
  include/ichain.h
  include/libc/math.h
  include/macros.h
  include/rand.h
  include/regs.h
  include/sfx.h
  include/sys_math.h
  include/sys_math3d.h
  include/ultra64/gu.h
  include/variables.h
  include/z64.h
  include/z64camera.h
  include/z64math.h
  include/z_lib.h
  spec
  src/code/code_80069420.c
  src/code/fault.c
  src/code/fmodf.c
  src/code/fp_math.c
  src/code/rand.c
  src/code/sys_math.c
  src/code/sys_math3d.c
  src/code/sys_math3d_draw.c
  src/code/sys_math_atan.c
  src/code/z_collision_check.c
  src/code/z_kankyo.c
  src/code/z_lib.c
  src/code/z_olib.c
  src/libultra/gu/coss.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#1961 Fix check_ordering.py checking for shifted/nonmatching-besides-relocs
  tools/check_ordering.py
Labels: Met Review Requirements

#1963 Run CC_CHECK with the correct CPP defines
  Makefile
Labels: Met Review Requirements

#1957 Introduce version-specific YAML config
  Makefile
  baseroms/gc-eu-mq-dbg/config.yml
  baseroms/gc-eu-mq-dbg/dmadata_names.txt
  baseroms/gc-eu-mq-dbg/dmadata_start.txt
  baseroms/gc-eu-mq-dbg/segments.csv
  baseroms/gc-eu-mq/config.yml
  baseroms/gc-eu-mq/dmadata_names.txt
  baseroms/gc-eu-mq/dmadata_start.txt
  baseroms/gc-eu-mq/segments.csv
  baseroms/gc-eu/config.yml
  baseroms/gc-eu/dmadata_names.txt
  baseroms/gc-eu/dmadata_start.txt
  baseroms/gc-eu/segments.csv
  requirements.txt
  tools/decompress_baserom.py
  tools/extract_baserom.py
  tools/msgdis.py
  tools/version_config.py
Labels: Met Review Requirements

#1962 Add point lighting gbi features
  include/ultra64/gbi.h
  src/code/sys_math3d.c
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Needs first approval, Needs second approval

#1964 Rename `ANIM_FLAG_0` to `ANIM_FLAG_UPDATE_XZ`
  include/z64animation.h
  src/code/z_player_lib.c
  src/code/z_skelanime.c
  src/overlays/actors/ovl_Demo_Ec/z_demo_ec.c
  src/overlays/actors/ovl_Demo_Ik/z_demo_ik.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1.c
  src/overlays/actors/ovl_En_Zl4/z_en_zl4.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#1968 Sync gbi.h with MM, move ucode defines to makefile
  Makefile
  include/ultra64/gbi.h
Labels: Met Review Requirements

#1970 Automatically find end of staff message table
  baseroms/gc-eu-mq-dbg/config.yml
  baseroms/gc-eu-mq/config.yml
  baseroms/gc-eu/config.yml
  tools/msgdis.py
Labels: Met Review Requirements

#1974 Rename gTitleZeldaShieldLogoMQTex -> gTitleZeldaShieldLogoTex
  assets/xml/objects/object_mag.xml
  assets/xml/objects/object_mag_mq.xml
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
Labels: Met Review Requirements

#1971 Fix misc 22
  include/audiothread_cmd.h
  include/z64animation.h
  include/z64player.h
  include/z64transition_instances.h
  src/code/PreRender.c
  src/code/fault.c
  src/code/graph.c
  src/code/z_player_lib.c
  src/code/z_view.c
  src/overlays/actors/ovl_Bg_Spot06_Objects/z_bg_spot06_objects.c
  src/overlays/actors/ovl_Eff_Dust/z_eff_dust.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Brob/z_en_brob.c
  src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
  src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.h
  src/overlays/actors/ovl_En_Nwc/z_en_nwc.c
  src/overlays/actors/ovl_En_Tp/z_en_tp.c
  src/overlays/actors/ovl_En_fHG/z_en_fhg.c
  src/overlays/actors/ovl_Fishing/z_fishing.h
Labels: Met Review Requirements

#1966 Move `PlayState` to a new `z64play.h`
  include/color.h
  include/functions.h
  include/macros.h
  include/padmgr.h
  include/variables.h
  include/z64.h
  include/z64actor.h
  include/z64collision_check.h
  include/z64frame_advance.h
  include/z64game_over.h
  include/z64play.h
  include/z64scene.h
  include/z64sfx_source.h
  include/z64vis.h
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_demo.c
  src/code/z_effect.c
  src/code/z_effect_soft_sprite.c
  src/code/z_frame_advance.c
  src/code/z_game_over.c
  src/code/z_kankyo.c
  src/code/z_play.c
  src/code/z_scene.c
  src/code/z_scene_table.c
  src/code/z_sfx_source.c
  src/overlays/actors/ovl_Demo_Gt/z_demo_gt.c
  src/overlays/actors/ovl_En_Okarina_Effect/z_en_okarina_effect.c
  src/overlays/actors/ovl_En_Wonder_Item/z_en_wonder_item.c
  src/overlays/actors/ovl_En_Zl2/z_en_zl2.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#1969 Rename ANIM_FLAG_PLAYER_7 to ANIM_FLAG_OVERRIDE_MOVEMENT
  include/z64animation.h
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#1977 Remove global.h from z_fishing
  include/z64actor.h
  include/z64bgcheck.h
  include/z64camera.h
  include/z64cutscene.h
  include/z64math.h
  src/code/sys_math3d.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_Fishing/z_fishing.h
Labels: Met Review Requirements

#1978 Fix extract_assets.py -s modification check
  extract_assets.py
Labels: Needs second approval

#1979 CC_CHECK: Add -Werror=implicit-function-declaration
  Makefile
Labels: Met Review Requirements
