Repository zeldaret/oot, pull requests merged in 2024-07, with the labels that each got.

#1896 Clean up custom LoadTextureBlock in z_map_mark.c and z_lmap_mark.c
  src/code/gDPLoadTextureBlock_Runtime.inc.c
  src/code/z_map_mark.c
  src/overlays/misc/ovl_kaleido_scope/z_lmap_mark.c
Labels: Met Review Requirements

#1984 Handle messages with different box types/positions between JPN/NES
  tools/msgdis.py
Labels: Needs second approval

#1985 Fix extract_assets.py error message
  extract_assets.py
Labels: Met Review Requirements

#1986 Create FILENAME_ macros for NTSC filename encoding
  include/z64message.h
  src/code/z_message.c
  src/code/z_sram.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset.c
Labels: Met Review Requirements

#1987 Match NTSC z_parameter.c and z_construct.c
  assets/xml/textures/icon_item_static.xml
  assets/xml/textures/icon_item_static_pal.xml
  assets/xml/textures/parameter_static.xml
  include/regs.h
  src/code/z_construct.c
  src/code/z_kaleido_setup.c
  src/code/z_parameter.c
Labels: Met Review Requirements

#1989 Match NTSC z_en_mag.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
Labels: Met Review Requirements

#1991 make format.py clean up extra whitespace, also in .h files
  format.py
  include/z64actor.h
  tools/check_format.py
Labels: Met Review Requirements

#1994 Fix a couple of render modes
  src/code/PreRender.c
  src/code/z_vismono.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_En_Box/z_en_box.c
Labels: Met Review Requirements

#1995 Promote the warnings `implicit-int`, `int-conversion`, `incompatible-pointer-types` to errors
  Makefile
Labels: Met Review Requirements

#1996 Nicer AudioSeq_SequenceChannelProcessScript match
  src/audio/lib/seqplayer.c
Labels: Met Review Requirements

#1999 Small cleanup of cleararena (bootclear)
  src/boot/boot_main.c
Labels: Met Review Requirements

#1981 Rename `ANIM_FLAG_NO_MOVE` to `ANIM_FLAG_ADJUST_STARTING_POS`
  include/z64animation.h
  src/code/z_skelanime.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs second approval

#1997 Match NTSC z_kanfont.c and z_message.c
  include/functions.h
  include/message_data_fmt.h
  include/z64message.h
  src/code/z_kanfont.c
  src/code/z_message.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  tools/disasm/gc-us/functions.txt
Labels: Needs second approval

#2002 Restore makefile rules for building asset files out of the assets directory
  Makefile
Labels: Needs second approval

#1992 Detect shifted .bss sections in check_ordering.py
  tools/check_ordering.py
Labels: Needs second approval

#2000 Document bottle color bug
  src/code/z_player_lib.c
Labels: Needs second approval

#2001 Document `ANIM_FLAG_PLAYER_2` as `ANIM_FLAG_DISABLE_CHILD_ROOT_ADJUSTMENT`
  include/z64animation.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs second approval

#2004 Match NTSC loose ends
  src/code/z_actor.c
  src/code/z_common_data.c
  src/code/z_play.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs second approval

#2005 Configure incbins in version config instead of using the Debug ROM
  Makefile
  baseroms/gc-eu-mq-dbg/config.yml
  baseroms/gc-eu-mq/config.yml
  baseroms/gc-eu/config.yml
  baseroms/gc-us/config.yml
  data/audio_tables.rodata.s
  data/rsp.rodata.s
  data/rsp.text.s
  data/rsp_boot.text.s
  data/unk_800093F0.data.s
  data/unk_80009410.data.s
  data/unk_8012ABC0.data.s
  data/z_text.data.s
  docs/tutorial/data.md
  src/makerom/ipl3.s
  tools/extract_incbins.py
  tools/version_config.py
Labels: Needs second approval

#2003 Introduce OOT_VERSION and OOT_REGION defines for build info and ROM header
  Makefile
  include/macros.h
  include/region.h
  include/z64.h
  src/boot/build.c
  src/boot/z_locale.c
  src/makerom/rom_header.s
Labels: Needs first approval, Needs second approval

#2006 Fix Makefile performance regression with OOT_VERSION define
  Makefile
Labels: Needs second approval

#2007 Create build directories for committed assets
  Makefile
Labels: Needs second approval
