Repository zeldaret/oot, pull requests merged in 2024-08, with the labels that each got.

#2010 Update vs code config and provide c_cpp_properties.json with all supported versions
  docs/c_cpp_properties.json
  docs/vscode.md
Labels: Needs first approval, Needs second approval

#2012 Clean up gitignore
  .gitignore
Labels: Needs first approval, Needs second approval

#2009 Automate fixing BSS ordering
  Makefile
  src/boot/idle.c
  src/code/fault.c
  src/code/main.c
  src/code/sys_math3d.c
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_common_data.c
  src/code/z_demo.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kankyo.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_En_Wonder_Item/z_en_wonder_item.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/check_ordering.py
  tools/fix_bss.py
  tools/ido_block_numbers.py
  tools/preprocess.py
Labels: Met Review Requirements

#2013 Remove tutorial, link to the latest zeldaret/oot:main revision with it
  docs/decompiling_tutorial.md
  docs/tutorial/beginning_decomp.md
  docs/tutorial/contents.md
  docs/tutorial/data.md
  docs/tutorial/draw_functions.md
  docs/tutorial/helper_scripts.md
  docs/tutorial/images/changing_init_prototype.png
  docs/tutorial/images/ctx.png
  docs/tutorial/images/data_inserted_commented_out.png
  docs/tutorial/images/fresh_actor_data.png
  docs/tutorial/images/fresh_actor_file.png
  docs/tutorial/images/fresh_actor_file_annotated.png
  docs/tutorial/images/fresh_actor_header.png
  docs/tutorial/images/func_80A87B1C_diff1.png
  docs/tutorial/images/func_80A87B1C_diff2.png
  docs/tutorial/images/func_80A87B9C_diff1.png
  docs/tutorial/images/func_80A87B9C_diff2.png
  docs/tutorial/images/init_after_replace_actorthis.png
  docs/tutorial/images/init_asm.png
  docs/tutorial/images/init_diff1.png
  docs/tutorial/images/init_diff2.png
  docs/tutorial/images/init_diff3top.png
  docs/tutorial/images/permuter_console_output.png
  docs/tutorial/images/vbindiff_data_1.png
  docs/tutorial/images/vbindiff_data_2.png
  docs/tutorial/introduction.md
  docs/tutorial/merging.md
  docs/tutorial/object_decomp.md
  docs/tutorial/object_decomp_example.md
  docs/tutorial/other_functions.md
  docs/tutorial/pre-decomp.md
  docs/tutorial/types_structs_padding.md
Labels: Met Review Requirements

#2016 Add make_options.mk
  .gitignore
  Makefile
Labels: Met Review Requirements

#1988 Match NTSC z_kaleido_scope.c
  assets/xml/textures/icon_item_jpn_static.xml
  include/regs.h
  src/code/z_construct.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Met Review Requirements

#2008 [Audio 1/?] Extract Samplebanks and Soundfonts to XML
  Makefile
  assets/xml/audio/samplebanks/SampleBank_0.xml
  assets/xml/audio/samplebanks/SampleBank_2.xml
  assets/xml/audio/samplebanks/SampleBank_3.xml
  assets/xml/audio/samplebanks/SampleBank_4.xml
  assets/xml/audio/samplebanks/SampleBank_5.xml
  assets/xml/audio/samplebanks/SampleBank_6.xml
  assets/xml/audio/soundfonts/Soundfont_0.xml
  assets/xml/audio/soundfonts/Soundfont_1.xml
  assets/xml/audio/soundfonts/Soundfont_10.xml
  assets/xml/audio/soundfonts/Soundfont_11.xml
  assets/xml/audio/soundfonts/Soundfont_12.xml
  assets/xml/audio/soundfonts/Soundfont_13.xml
  assets/xml/audio/soundfonts/Soundfont_14.xml
  assets/xml/audio/soundfonts/Soundfont_15.xml
  assets/xml/audio/soundfonts/Soundfont_16.xml
  assets/xml/audio/soundfonts/Soundfont_17.xml
  assets/xml/audio/soundfonts/Soundfont_18.xml
  assets/xml/audio/soundfonts/Soundfont_19.xml
  assets/xml/audio/soundfonts/Soundfont_2.xml
  assets/xml/audio/soundfonts/Soundfont_20.xml
  assets/xml/audio/soundfonts/Soundfont_21.xml
  assets/xml/audio/soundfonts/Soundfont_22.xml
  assets/xml/audio/soundfonts/Soundfont_23.xml
  assets/xml/audio/soundfonts/Soundfont_24.xml
  assets/xml/audio/soundfonts/Soundfont_25.xml
  assets/xml/audio/soundfonts/Soundfont_26.xml
  assets/xml/audio/soundfonts/Soundfont_27.xml
  assets/xml/audio/soundfonts/Soundfont_28.xml
  assets/xml/audio/soundfonts/Soundfont_29.xml
  assets/xml/audio/soundfonts/Soundfont_3.xml
  assets/xml/audio/soundfonts/Soundfont_30.xml
  assets/xml/audio/soundfonts/Soundfont_31.xml
  assets/xml/audio/soundfonts/Soundfont_32.xml
  assets/xml/audio/soundfonts/Soundfont_33.xml
  assets/xml/audio/soundfonts/Soundfont_34.xml
  assets/xml/audio/soundfonts/Soundfont_35.xml
  assets/xml/audio/soundfonts/Soundfont_36.xml
  assets/xml/audio/soundfonts/Soundfont_37.xml
  assets/xml/audio/soundfonts/Soundfont_4.xml
  assets/xml/audio/soundfonts/Soundfont_5.xml
  assets/xml/audio/soundfonts/Soundfont_6.xml
  assets/xml/audio/soundfonts/Soundfont_7.xml
  assets/xml/audio/soundfonts/Soundfont_8.xml
  assets/xml/audio/soundfonts/Soundfont_9.xml
  baseroms/gc-eu-mq-dbg/config.yml
  baseroms/gc-eu-mq/config.yml
  baseroms/gc-eu/config.yml
  baseroms/gc-us/config.yml
  tools/audio/extraction/audio_extract.py
  tools/audio/extraction/audio_tables.py
  tools/audio/extraction/audiobank_file.py
  tools/audio/extraction/audiobank_structs.py
  tools/audio/extraction/audiotable.py
  tools/audio/extraction/envelope.py
  tools/audio/extraction/tuning.py
  tools/audio/extraction/util.py
  tools/audio_extraction.py
Labels: Met Review Requirements

#1998 Match NTSC file select
  assets/xml/overlays/ovl_file_choose.xml
  assets/xml/overlays/ovl_file_choose_pal.xml
  baseroms/gc-eu-mq-dbg/config.yml
  baseroms/gc-eu-mq/config.yml
  baseroms/gc-eu/config.yml
  baseroms/gc-us/config.yml
  extract_assets.py
  include/macros.h
  include/z64.h
  src/code/z_sram.c
  src/overlays/gamestates/ovl_file_choose/file_select.h
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset_data.c
  tools/disasm/gc-us/functions.txt
Labels: Met Review Requirements

#2018 gc-us OK
  Makefile
  src/boot/idle.c
  src/code/fault.c
  src/code/main.c
  src/code/sys_math3d.c
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_common_data.c
  src/code/z_demo.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kankyo.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_En_Wonder_Item/z_en_wonder_item.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/gc-us/file_addresses.csv
  tools/disasm/gc-us/files_code.csv
  tools/disasm/gc-us/files_ovl_file_choose.csv
  tools/disasm/gc-us/files_ovl_kaleido_scope.csv
  tools/disasm/gc-us/functions.txt
  tools/disasm/gc-us/variables.txt
Labels: Needs second approval

#2022 Add -DF3DEX_GBI_2 to format.py flags
  format.py
Labels: Met Review Requirements

#2023 Handle multiline `#pragma increment_block_number`
  tools/fix_bss.py
  tools/preprocess.py
Labels: Met Review Requirements

#2019 Match remaining GC retail versions
  Makefile
  assets/xml/objects/object_mag_v2.xml
  assets/xml/objects/object_mag_v2_mq.xml
  assets/xml/objects/object_mag_v3.xml
  assets/xml/objects/object_mag_v3_mq.xml
  assets/xml/textures/nes_font_static.xml
  assets/xml/textures/nes_font_static_v2.xml
  baseroms/gc-eu-mq-dbg/config.yml
  baseroms/gc-eu-mq/config.yml
  baseroms/gc-eu/config.yml
  baseroms/gc-jp-ce/checksum-compressed.md5
  baseroms/gc-jp-ce/checksum.md5
  baseroms/gc-jp-ce/config.yml
  baseroms/gc-jp-ce/segments.csv
  baseroms/gc-jp-mq/checksum-compressed.md5
  baseroms/gc-jp-mq/checksum.md5
  baseroms/gc-jp-mq/config.yml
  baseroms/gc-jp-mq/segments.csv
  baseroms/gc-jp/checksum-compressed.md5
  baseroms/gc-jp/checksum.md5
  baseroms/gc-jp/config.yml
  baseroms/gc-jp/segments.csv
  baseroms/gc-us-mq/checksum-compressed.md5
  baseroms/gc-us-mq/checksum.md5
  baseroms/gc-us-mq/config.yml
  baseroms/gc-us-mq/segments.csv
  baseroms/gc-us/config.yml
  include/variables.h
  src/boot/build.c
  src/boot/idle.c
  src/boot/z_locale.c
  src/code/fault.c
  src/code/main.c
  src/code/sys_math3d.c
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_common_data.c
  src/code/z_demo.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/code/z_play.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/actors/ovl_En_Wonder_Item/z_en_wonder_item.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_title/z_title.c
  tools/ZAPDConfigs/gc-jp-ce/Config.xml
  tools/ZAPDConfigs/gc-jp-ce/SymbolMap.txt
  tools/ZAPDConfigs/gc-jp-mq/Config.xml
  tools/ZAPDConfigs/gc-jp-mq/SymbolMap.txt
  tools/ZAPDConfigs/gc-jp/Config.xml
  tools/ZAPDConfigs/gc-jp/SymbolMap.txt
  tools/ZAPDConfigs/gc-us-mq/Config.xml
  tools/ZAPDConfigs/gc-us-mq/SymbolMap.txt
Labels: Met Review Requirements

#2025 Add "do {} while (0);" to CLOSE_DISPS
  include/macros.h
  src/code/game.c
  src/code/graph.c
  src/code/z_debug.c
  src/code/z_demo.c
  src/code/z_draw.c
  src/code/z_eff_blure.c
  src/code/z_eff_ss_dead.c
  src/code/z_fcurve_data_skelanime.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/code/z_scene_table.c
  src/overlays/actors/ovl_Bg_Haka_Gate/z_bg_haka_gate.c
  src/overlays/actors/ovl_Bg_Haka_Tubo/z_bg_haka_tubo.c
  src/overlays/actors/ovl_Bg_Jya_Bigmirror/z_bg_jya_bigmirror.c
  src/overlays/actors/ovl_Bg_Mizu_Bwall/z_bg_mizu_bwall.c
  src/overlays/actors/ovl_Bg_Mizu_Movebg/z_bg_mizu_movebg.c
  src/overlays/actors/ovl_Bg_Spot03_Taki/z_bg_spot03_taki.c
  src/overlays/actors/ovl_Bg_Spot16_Doughnut/z_bg_spot16_doughnut.c
  src/overlays/actors/ovl_Bg_Spot17_Bakudankabe/z_bg_spot17_bakudankabe.c
  src/overlays/actors/ovl_Bg_Spot17_Funen/z_bg_spot17_funen.c
  src/overlays/actors/ovl_Bg_Ydan_Sp/z_bg_ydan_sp.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  src/overlays/actors/ovl_Boss_Ganondrof/z_boss_ganondrof.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_Demo_Shd/z_demo_shd.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.c
  src/overlays/actors/ovl_En_Boom/z_en_boom.c
  src/overlays/actors/ovl_En_Bubble/z_en_bubble.c
  src/overlays/actors/ovl_En_Bw/z_en_bw.c
  src/overlays/actors/ovl_En_Daiku/z_en_daiku.c
  src/overlays/actors/ovl_En_Daiku_Kakariko/z_en_daiku_kakariko.c
  src/overlays/actors/ovl_En_Dekubaba/z_en_dekubaba.c
  src/overlays/actors/ovl_En_Fd_Fire/z_en_fd_fire.c
  src/overlays/actors/ovl_En_Fz/z_en_fz.c
  src/overlays/actors/ovl_En_GeldB/z_en_geldb.c
  src/overlays/actors/ovl_En_Hy/z_en_hy.c
  src/overlays/actors/ovl_En_Mm/z_en_mm.c
  src/overlays/actors/ovl_En_Po_Field/z_en_po_field.c
  src/overlays/actors/ovl_En_Po_Relay/z_en_po_relay.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_En_Rr/z_en_rr.c
  src/overlays/actors/ovl_En_Siofuki/z_en_siofuki.c
  src/overlays/actors/ovl_En_Wallmas/z_en_wallmas.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.c
  src/overlays/actors/ovl_Object_Kankyo/z_object_kankyo.c
  src/overlays/actors/ovl_Oceff_Wipe/z_oceff_wipe.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/effects/ovl_Effect_Ss_Bomb2/z_eff_ss_bomb2.c
  src/overlays/effects/ovl_Effect_Ss_G_Spk/z_eff_ss_g_spk.c
Labels: Met Review Requirements

#2026 [Doc] Docs for BgHaka gravestone actor (tiny)
  src/overlays/actors/ovl_Bg_Haka/z_bg_haka.c
Labels: Met Review Requirements

#2021 Set up build system and disassembly for ntsc-1.2
  Makefile
  assets/xml/objects/object_mag.xml
  baseroms/ntsc-1.2/checksum-compressed.md5
  baseroms/ntsc-1.2/checksum.md5
  baseroms/ntsc-1.2/config.yml
  baseroms/ntsc-1.2/segments.csv
  docs/retail_versions.md
  include/macros.h
  retail_progress.py
  src/boot/build.c
  src/boot/cic6105.c
  src/code/code_n64dd_800AD410.c
  src/code/code_n64dd_800AD4C0.c
  src/libultra/gu/mtxutil.c
  src/libultra/os/getintmask.s
  src/libultra/os/settime.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  tools/ZAPDConfigs/ntsc-1.2/Config.xml
  tools/ZAPDConfigs/ntsc-1.2/SymbolMap.txt
  tools/disasm/disasm.py
  tools/disasm/ntsc-1.2/file_addresses.csv
  tools/disasm/ntsc-1.2/files_boot.csv
  tools/disasm/ntsc-1.2/files_code.csv
  tools/disasm/ntsc-1.2/files_makerom.csv
  tools/disasm/ntsc-1.2/files_ovl_file_choose.csv
  tools/disasm/ntsc-1.2/files_ovl_kaleido_scope.csv
  tools/disasm/ntsc-1.2/functions.txt
  tools/disasm/ntsc-1.2/variables.txt
Labels: Met Review Requirements, wait

#2024 [Audio 3/?] Set up building samples
  Makefile
Labels: Met Review Requirements

#2029 [Doc] name function func_8002DBD0 to Actor_WorldToActorCoords
  include/functions.h
  src/code/z_actor.c
  src/overlays/actors/ovl_Bg_Haka/z_bg_haka.c
  src/overlays/actors/ovl_Bg_Haka_Trap/z_bg_haka_trap.c
  src/overlays/actors/ovl_Bg_Hidan_Firewall/z_bg_hidan_firewall.c
  src/overlays/actors/ovl_Bg_Hidan_Fwbig/z_bg_hidan_fwbig.c
  src/overlays/actors/ovl_Bg_Ydan_Sp/z_bg_ydan_sp.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Door_Gerudo/z_door_gerudo.c
  src/overlays/actors/ovl_Door_Killer/z_door_killer.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Box/z_en_box.c
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Holl/z_en_holl.c
  src/overlays/actors/ovl_En_River_Sound/z_en_river_sound.c
  src/overlays/actors/ovl_Obj_Timeblock/z_obj_timeblock.c
  src/overlays/actors/ovl_Obj_Warp2block/z_obj_warp2block.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2033 Update c_cpp_properties.json for VSCode
  docs/c_cpp_properties.json
  docs/vscode.md
Labels: Needs first approval, Needs second approval

#2031 Match ``z_fbdemo.c`` and ``z_fbdemo_fade.c`` for NTSC-1.2
  src/code/z_fbdemo.c
  src/code/z_fbdemo_fade.c
Labels: Met Review Requirements

#2034 Match a bunch of overlay draw functions
  src/overlays/actors/ovl_Bg_Gjyo_Bridge/z_bg_gjyo_bridge.c
  src/overlays/actors/ovl_Bg_Hidan_Sima/z_bg_hidan_sima.c
  src/overlays/actors/ovl_Bg_Mori_Hashigo/z_bg_mori_hashigo.c
  src/overlays/actors/ovl_Bg_Mori_Hineri/z_bg_mori_hineri.c
  src/overlays/actors/ovl_Bg_Toki_Hikari/z_bg_toki_hikari.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Demo_Gt/z_demo_gt.c
  src/overlays/actors/ovl_Demo_Gt/z_demo_gt.h
  src/overlays/actors/ovl_En_Ba/z_en_ba.c
  src/overlays/actors/ovl_En_Bubble/z_en_bubble.c
  src/overlays/actors/ovl_En_Fd/z_en_fd.c
  src/overlays/actors/ovl_En_Fd_Fire/z_en_fd_fire.c
  src/overlays/actors/ovl_En_G_Switch/z_en_g_switch.c
  src/overlays/actors/ovl_En_Goma/z_en_goma.c
  src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
  src/overlays/actors/ovl_En_Zo/z_en_zo.c
  src/overlays/actors/ovl_Magic_Dark/z_magic_dark.c
  src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.c
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.h
  src/overlays/effects/ovl_Effect_Ss_Ice_Smoke/z_eff_ss_ice_smoke.c
  src/overlays/effects/ovl_Effect_Ss_Stone1/z_eff_ss_stone1.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset.c
Labels: Met Review Requirements

#2035 Rewrite preprocess.py with bash and C
  Makefile
  tools/.gitignore
  tools/Makefile
  tools/preprocess.py
  tools/preprocess.sh
  tools/preprocess_pragmas.c
Labels: Met Review Requirements

#2036 Fix a few function names in disassembly
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2038 Fix preprocess_pragmas and add tests
  tools/preprocess_pragmas.c
  tools/tests/README
  tools/tests/test_preprocess_pragmas.py
Labels: Needs second approval

#2030 Checksums for ntsc 1.2 JP and US, accept both as baserom for ntsc-1.2
  Makefile
  baseroms/ntsc-1.2/checksum-JP-compressed.md5
  baseroms/ntsc-1.2/checksum-JP.md5
  baseroms/ntsc-1.2/checksum-US-compressed.md5
  baseroms/ntsc-1.2/checksum-US.md5
  baseroms/ntsc-1.2/config.yml
  tools/decompress_baserom.py
  tools/version_config.py
Labels: Met Review Requirements

#2039 [ntsc-1.2] Match z_construct.c, z_draw.c, z_kaleido_setup.c and partially z_actor.c
  include/n64dd.h
  include/z64interface.h
  spec
  src/code/code_n64dd_800AD4C0.c
  src/code/z_actor.c
  src/code/z_construct.c
  src/code/z_draw.c
  src/code/z_kaleido_setup.c
Labels: Met Review Requirements

#2040 [ntsc-1.2] padutils.c, some line numbers
  src/boot/z_std_dma.c
  src/code/graph.c
  src/code/padmgr.c
  src/code/padutils.c
Labels: Met Review Requirements

#2027 Build all GC retail ROMs in Jenkins
  Jenkinsfile
  progress.py
Labels: Met Review Requirements

#2041 Match ntsc-1.2 z_skelanime.c, z_view.c, z_viszbuf.c
  src/code/z_skelanime.c
  src/code/z_view.c
  src/code/z_viszbuf.c
Labels: Met Review Requirements

#2043 Update links in readme
  README.md
Labels: Needs first approval, Needs second approval

#2042 Decompile N64 anti-piracy checks in overlays
  include/cic6105.h
  include/variables.h
  spec
  src/boot/cic6105.c
  src/overlays/actors/ovl_Bg_Zg/z_bg_zg.c
  src/overlays/actors/ovl_En_Zl2/z_en_zl2.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  tools/disasm/ntsc-1.2/files_boot.csv
Labels: Met Review Requirements

#2049 Fixup printf args fake matches
  src/code/game.c
  src/code/z_map_exp.c
  src/code/z_skin_matrix.c
  src/overlays/actors/ovl_Bg_Bdan_Objects/z_bg_bdan_objects.c
  src/overlays/actors/ovl_Bg_Jya_Ironobj/z_bg_jya_ironobj.c
  src/overlays/actors/ovl_Demo_Gj/z_demo_gj.c
  src/overlays/actors/ovl_En_Ex_Item/z_en_ex_item.c
  src/overlays/actors/ovl_En_Honotrap/z_en_honotrap.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
Labels: Met Review Requirements

#2044 [Audio 5/?] Build the Samplebank Table
  Makefile
  baseroms/gc-eu-mq-dbg/config.yml
  baseroms/gc-eu-mq/config.yml
  baseroms/gc-eu/config.yml
  baseroms/gc-jp-ce/config.yml
  baseroms/gc-jp-mq/config.yml
  baseroms/gc-jp/config.yml
  baseroms/gc-us-mq/config.yml
  baseroms/gc-us/config.yml
  baseroms/ntsc-1.2/config.yml
  data/audio_tables.rodata.s
  include/attributes.h
  include/variables.h
  include/z64audio.h
  linker_scripts/audio_table_rodata.ld
  spec
  src/audio/lib/heap.c
  src/audio/lib/load.c
  src/audio/tables/samplebank_table.c
  src/code/z_play.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  tools/audio/.gitignore
  tools/audio/Makefile
  tools/audio/audio_tablegen.c
Labels: Met Review Requirements, wait

#2045 Use BSS section start from map file in fix_bss.py instead of guessing
  tools/fix_bss.py
Labels: Met Review Requirements

#2047 Add DEG_TO_BINANG2/RAD_TO_BINANG2 to match ntsc-1.2 z_en_gs.c, z_en_mm.c, z_en_toryo.c
  include/z64math.h
  src/overlays/actors/ovl_Bg_Haka_Gate/z_bg_haka_gate.c
  src/overlays/actors/ovl_Bg_Mori_Kaitenkabe/z_bg_mori_kaitenkabe.c
  src/overlays/actors/ovl_En_Fd/z_en_fd.c
  src/overlays/actors/ovl_En_Gs/z_en_gs.c
  src/overlays/actors/ovl_En_Mm/z_en_mm.c
  src/overlays/actors/ovl_En_Toryo/z_en_toryo.c
  src/overlays/actors/ovl_En_Vali/z_en_vali.c
Labels: Met Review Requirements

#2048 Miscellaneous N64 actor changes
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
Labels: Met Review Requirements

#2050 Match ntsc-1.2 z_scene_table.c
  include/n64dd.h
  include/z64interface.h
  include/z64scene.h
  src/code/z_play.c
  src/code/z_player_lib.c
  src/code/z_scene_table.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2051 Use incremental link for z_message/z_game_over data shenanigans
  Makefile
  linker_scripts/audio_table_rodata.ld
  linker_scripts/data_with_rodata.ld
  spec
  tools/mkldscript.c
  tools/spec.c
  tools/spec.h
Labels: Met Review Requirements

#2053 [ntsc-1.2] Match boot_main.c, logutils.c, z_locale.c (text)
  Makefile
  include/cic6105.h
  include/functions.h
  src/boot/boot_main.c
  src/boot/logutils.c
  src/boot/z_locale.c
  tools/disasm/ntsc-1.2/functions.txt
  undefined_syms.txt
Labels: Met Review Requirements

#2052 Allow building the Debug ROM without debug features
  include/segment_symbols.h
  src/code/main.c
  src/code/z_actor.c
  src/code/z_demo.c
  src/code/z_message.c
  src/code/z_play.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2054 Add "disasm sym_info.py" script
  requirements.txt
  tools/disasm/disasm.py
  tools/disasm/sym_info.py
Labels: Met Review Requirements

#2055 Move non-libultra libc functions to src/libc/
  Makefile
  include/functions.h
  spec
  src/code/__osMalloc.c
  src/code/code_80069420.c
  src/code/z_camera.c
  src/code/z_lib.c
  src/code/z_quake.c
  src/code/z_view.c
  src/gcc_fix/missing_gcc_functions.c
  src/libc/absf.s
  src/libc/fmodf.c
  src/libc/memmove.c
  src/libc/memset.c
  src/libc/sqrt.s
  src/libultra/libc/absf.c
  src/libultra/libc/sqrt.c
  tools/disasm/ntsc-1.2/files_code.csv
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2061 Match more ntsc-1.2 overlay draw functions
  include/functions.h
  src/code/z_actor.c
  src/overlays/actors/ovl_Bg_Hidan_Sekizou/z_bg_hidan_sekizou.c
  src/overlays/actors/ovl_Bg_Toki_Hikari/z_bg_toki_hikari.c
  src/overlays/actors/ovl_Boss_Fd/z_boss_fd.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Demo_6K/z_demo_6k.c
  src/overlays/actors/ovl_Demo_Ext/z_demo_ext.c
  src/overlays/actors/ovl_En_Ganon_Organ/z_en_ganon_organ.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_Mir_Ray/z_mir_ray.c
  src/overlays/effects/ovl_Effect_Ss_En_Fire/z_eff_ss_en_fire.c
Labels: Needs second approval

#2060 Add versions.h
  include/macros.h
  include/versions.h
  src/boot/build.c
  src/code/z_common_data.c
  src/code/z_message.c
  src/code/z_play.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_title/z_title.c
Labels: Met Review Requirements

#2058 Match n64dd text in code
  include/n64dd.h
  spec
  src/code/code_n64dd_800AD410.c
  src/code/code_n64dd_800AD4C0.c
  tools/disasm/ntsc-1.2/functions.txt
  tools/disasm/ntsc-1.2/variables.txt
  undefined_syms.txt
Labels: Met Review Requirements

#2057 Document `z_player` AnimSfxType and related functions
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2066 Grab bag of fix_bss.py bugfixes
  tools/fix_bss.py
Labels: Met Review Requirements

#2065 Pause docs: page backgrounds vertices and quads
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2064 Add T macro for translated debug strings
  include/macros.h
  src/boot/z_std_dma.c
  src/code/__osMalloc.c
  src/code/audio_thread_manager.c
  src/code/game.c
  src/code/graph.c
  src/code/main.c
  src/code/padmgr.c
  src/code/sys_cfb.c
  src/code/system_malloc.c
  src/code/title_setup.c
  src/code/z_DLF.c
  src/code/z_construct.c
  src/code/z_kaleido_manager.c
Labels: Met Review Requirements

#2067 Add NO_SQRTF_INTRINSIC for z_rumble.c and audio/general.c
  Makefile
  include/libc/math.h
Labels: Met Review Requirements

#2074 Convert z_std_dma.c translations to full string rather than inserted string
  src/boot/z_std_dma.c
Labels: Met Review Requirements

#2073 T() macro 2
  src/boot/idle.c
  src/boot/z_locale.c
  src/code/irqmgr.c
  src/code/padmgr.c
  src/code/z_bgcheck.c
  src/code/z_scene.c
  src/code/z_sram.c
Labels: Met Review Requirements

#2075 [ntsc-1.2] Match z_title.c
  include/z64.h
  src/overlays/gamestates/ovl_title/z_title.c
  undefined_syms.txt
Labels: Met Review Requirements

#2076 [ntsc-1.2] Match z_select.c
  src/overlays/gamestates/ovl_select/z_select.c
Labels: Met Review Requirements

#2070 [ntsc-1.2] Match kaleido_collect.c, kaleido_scope.c
  include/n64dd.h
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  tools/disasm/ntsc-1.2/variables.txt
Labels: Met Review Requirements

#2077 [ntsc-1.2] Match z_kaleido_debug.c, z_lmap_mark.c
  include/n64dd.h
  src/code/code_n64dd_800AD4C0.c
  src/code/z_kaleido_setup.c
  src/code/z_scene_table.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_debug.c
  src/overlays/misc/ovl_kaleido_scope/z_lmap_mark.c
Labels: Met Review Requirements

#2071 Pause: doc generating page vtx/quads (part 1)
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: Met Review Requirements

#2087 Fix build ntsc-1.2: define n64dd_SetDiskVersion
  undefined_syms.txt
Labels: Needs first approval, Needs second approval

#2084 T() macro 4
  src/code/z_demo.c
  src/code/z_effect.c
  src/code/z_kankyo.c
  src/code/z_sram.c
  src/overlays/actors/ovl_En_Encount1/z_en_encount1.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Wonder_Item/z_en_wonder_item.c
Labels: Met Review Requirements

#2082 [ntsc-1.2] Match z_std_dma.c
  include/n64dd.h
  src/boot/z_std_dma.c
  src/code/code_n64dd_800AD410.c
Labels: Met Review Requirements

#2086 Add clangd files to .gitignore
  .gitignore
Labels: Met Review Requirements

#2072 Have fix_bss.py deal with symbols referenced in .data or .rodata
  tools/fix_bss.py
  tools/ido_block_numbers.py
Labels: Needs second approval

#2068 [ntsc-1.2] Decompile cic6105.c, main.c
  include/cic6105.h
  include/variables.h
  src/boot/boot_main.c
  src/boot/cic6105.c
  src/boot/yaz0.c
  src/boot/z_std_dma.c
  src/code/game.c
  src/code/graph.c
  src/code/main.c
  src/code/sched.c
  src/code/speed_meter.c
  src/code/sys_cfb.c
  src/code/sys_matrix.c
  src/code/z_debug.c
  src/code/z_player_call.c
  src/code/z_skin.c
  tools/disasm/ntsc-1.2/functions.txt
  tools/disasm/ntsc-1.2/variables.txt
  undefined_syms.txt
Labels: Met Review Requirements

#2085 In fix_bss.py, always use BSS section start from map file
  src/audio/data.c
  src/audio/session_config.c
  tools/fix_bss.py
Labels: Met Review Requirements

#2079 [ntsc-1.2] Partially match z_en_mag
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  undefined_syms.txt
Labels: Met Review Requirements

#2095 Add all N64 version defines
  Makefile
  docs/c_cpp_properties.json
  docs/vscode.md
  include/versions.h
  src/boot/build.c
  src/code/z_common_data.c
  src/code/z_message.c
  src/code/z_play.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_title/z_title.c
Labels: Met Review Requirements

#2091 [ntsc-1.2] Match z_vismono.c
  src/code/z_vismono.c
Labels: Met Review Requirements

#2093 [ntsc-1.2] Match `PreRender_CopyImageRegionImpl`
  src/code/PreRender.c
Labels: Met Review Requirements

#2090 T() macro 6
  src/code/z_eff_blure.c
  src/code/z_eff_spark.c
  src/code/z_effect_soft_sprite.c
  src/code/z_horse.c
  src/code/z_jpeg.c
  src/code/z_malloc.c
  src/code/z_play.c
  src/code/z_skelanime.c
Labels: Met Review Requirements

#2100 [ntsc-1.2] Match functions using gDPSetTileCustom
  include/macros.h
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
Labels: Met Review Requirements

#2056 [Audio 6/?] Build Soundfonts and the Soundfont Table
  Makefile
  baseroms/gc-eu-mq-dbg/config.yml
  baseroms/gc-eu-mq/config.yml
  baseroms/gc-eu/config.yml
  baseroms/gc-jp-ce/config.yml
  baseroms/gc-jp-mq/config.yml
  baseroms/gc-jp/config.yml
  baseroms/gc-us-mq/config.yml
  baseroms/gc-us/config.yml
  baseroms/ntsc-1.2/config.yml
  data/audio_tables.rodata.s
  include/attributes.h
  include/audio/soundfont_file.h
  include/variables.h
  include/z64audio.h
  linker_scripts/soundfont.ld
  spec
  src/audio/lib/heap.c
  src/audio/lib/load.c
  src/audio/lib/seqplayer.c
  src/audio/lib/synthesis.c
  src/audio/lib/thread.c
  src/audio/tables/soundfont_table.c
  src/code/graph.c
  src/code/speed_meter.c
  src/code/z_collision_check.c
  src/code/z_play.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  tools/audio/.gitignore
  tools/audio/Makefile
  tools/audio/aifc.c
  tools/audio/aifc.h
  tools/audio/audio_tablegen.c
  tools/audio/elf32.h
  tools/audio/sampleconv/src/codec/vadpcm.c
  tools/audio/sampleconv/src/container/aiff.c
  tools/audio/sfpatch.c
  tools/audio/soundfont.c
  tools/audio/soundfont.h
  tools/audio/soundfont_compiler.c
Labels: Met Review Requirements, wait

#2046 [ntsc-1.2] Decompile fault.c
  Makefile
  include/fault.h
  include/padmgr.h
  include/variables.h
  include/versions.h
  include/z64.h
  spec
  src/boot/assert.c
  src/boot/logutils.c
  src/boot/z_std_dma.c
  src/code/__osMalloc.c
  src/code/code_n64dd_800AD4C0.c
  src/code/fault_gc.c
  src/code/fault_gc_drawer.c
  src/code/fault_n64.c
  src/code/game.c
  src/code/graph.c
  src/code/main.c
  src/code/padmgr.c
  src/code/sched.c
  src/code/sys_matrix.c
  src/code/z_actor.c
  src/code/z_actor_dlftbls.c
  src/code/z_collision_check.c
  src/code/z_message.c
  src/code/z_play.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/ntsc-1.2/files_code.csv
  tools/disasm/ntsc-1.2/functions.txt
  tools/disasm/ntsc-1.2/variables.txt
  tools/m2ctx.py
  undefined_syms.txt
Labels: Met Review Requirements

#2069 Check disasm metadata for missed renames
  Jenkinsfile
  tools/check_disasm_metadata_unksyms.py
  tools/disasm/ntsc-1.2/functions.txt
  tools/disasm/ntsc-1.2/variables.txt
Labels: Met Review Requirements

#2102 T() macro 7
  src/boot/logutils.c
  src/boot/stackcheck.c
  src/code/code_800430A0.c
  src/code/debug_malloc.c
  src/code/sched.c
  src/code/z_eff_shield_particle.c
  src/code/z_jpeg.c
  src/code/z_kanfont.c
  src/code/z_map_mark.c
  src/code/z_skin_matrix.c
Labels: Met Review Requirements

#2081 [ntsc-1.2] Match N64 libultra
  Makefile
  include/functions.h
  include/ultra64/gu.h
  spec
  src/code/mtxuty-cvt.c
  src/code/sys_matrix.c
  src/libultra/gu/lookat.c
  src/libultra/gu/lookathil.c
  src/libultra/gu/mtxutil.c
  src/libultra/gu/normalize.c
  src/libultra/gu/ortho.c
  src/libultra/gu/perspective.c
  src/libultra/gu/position.c
  src/libultra/gu/rotate.c
  src/libultra/gu/scale.c
  src/libultra/gu/translate.c
  src/libultra/io/contsetch.c
  src/libultra/io/epidma.c
  src/libultra/io/sptaskyielded.c
  src/libultra/libc/xldtob.c
  src/libultra/libc/xprintf.c
  src/libultra/os/exceptasm.s
  src/libultra/os/getintmask.s
  src/libultra/os/initialize.c
  src/libultra/os/setintmask.s
  src/libultra/os/settime.c
  src/libultra/os/settimer.c
  src/libultra/os/timerintr.c
  tools/check_disasm_metadata_unksyms.py
  tools/disasm/ntsc-1.2/files_code.csv
  undefined_syms.txt
Labels: Needs second approval

#2103 [ntsc-1.2] Fix some data / disassembly / undefined_syms
  src/boot/cic6105.c
  src/code/fault_n64.c
  tools/disasm/ntsc-1.2/files_code.csv
  undefined_syms.txt
Labels: Met Review Requirements

#2105 [ntsc-1.2] Move driverominit and sprintf to src/boot/
  Makefile
  spec
  src/boot/driverominit.c
  src/boot/sprintf.c
  tools/disasm/ntsc-1.2/files_boot.csv
  tools/disasm/ntsc-1.2/files_code.csv
Labels: Met Review Requirements

#2096 [ntsc-1.2] Match z_demo.c, z_eff_blure.c, z_eff_spark.c
  include/n64dd.h
  src/code/z_demo.c
  src/code/z_eff_blure.c
  src/code/z_eff_spark.c
Labels: Met Review Requirements

#2097 [ntsc-1.2] Match rand.c
  include/rand.h
  include/versions.h
  src/code/rand.c
Labels: Met Review Requirements

#2110 Target Docs [1/?]
  include/z64actor.h
  src/code/z_actor.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements
