Repository zeldaret/oot, pull requests merged in 2024-09, with the labels that each got.

#2115 Document Target_Draw [Target Docs 2/?]
  include/functions.h
  include/z64actor.h
  src/code/z_actor.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Needs second approval

#2120 Target System Docs: Actor Searching [3/?]
  include/functions.h
  src/code/z_actor.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Needs first approval, Needs second approval

#2118 [ntsc-1.2] LoadFragment2 OK
  Makefile
  spec
  src/code/load_gc.c
  src/code/loadfragment2_gc.c
  src/code/loadfragment2_n64.c
  src/code/logseverity_gc.c
  src/code/relocation_gc.c
  tools/disasm/ntsc-1.2/files_code.csv
Labels: Met Review Requirements

#2122 [ntsc-1.2] Match audio
  include/functions.h
  src/audio/general.c
  src/audio/lib/seqplayer.c
  src/audio/lib/synthesis.c
  src/audio/lib/thread.c
  src/audio/sfx.c
  tools/disasm/ntsc-1.2/files_code.csv
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2123 Document Target_Update [Target Docs 4/?]
  include/z64actor.h
  src/code/z_actor.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2107 [ntsc-1.2] Match stackcheck.c
  include/functions.h
  src/boot/stackcheck.c
Labels: Met Review Requirements

#2111 [ntsc-1.2] Match padmgr.c, sys_cfb.c, rcp_utils.c
  src/code/padmgr.c
  src/code/rcp_utils.c
  src/code/sys_cfb.c
Labels: Met Review Requirements

#2112 [ntsc-1.2] Match z_camera.c
  src/code/z_camera.c
Labels: Met Review Requirements

#2113 Rename FaultDrawer_ functions to Fault_
  include/fault.h
  src/boot/cic6105.c
  src/code/__osMalloc.c
  src/code/code_n64dd_800AD4C0.c
  src/code/fault_gc.c
  src/code/fault_gc_drawer.c
  src/code/game.c
  src/code/z_actor.c
  src/code/z_actor_dlftbls.c
Labels: Met Review Requirements

#2114 [ntsc-1.2] Update spec for boot and code
  Makefile
  spec
  src/boot/sleep.c
  tools/disasm/ntsc-1.2/files_boot.csv
Labels: Met Review Requirements

#2116 [ntsc-1.2] Match fp.c and fp_math.c
  include/libc/math.h
  src/code/fp.s
  src/code/fp_math.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2117 [ntsc-1.2] Match game.c, z_play.c, z_room.c
  include/macros.h
  include/n64dd.h
  src/code/code_n64dd_800AD4C0.c
  src/code/game.c
  src/code/z_play.c
  src/code/z_room.c
  tools/disasm/ntsc-1.2/functions.txt
  undefined_syms.txt
Labels: Met Review Requirements

#2125 [ntsc-1.2] Match KaleidoScope_DrawEquipment and KaleidoScope_DrawItemSelect
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
Labels: Met Review Requirements

#2121 Reorganize z_std_dma.c unused strings
  src/boot/z_std_dma.c
Labels: Met Review Requirements

#2109 Run CC_CHECK in CI
  Jenkinsfile
  include/n64dd.h
Labels: Met Review Requirements

#2088 Pause: Name temps in `KaleidoScope_SetVertices`
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Met Review Requirements

#2106 [ntsc-1.2] Match __osMalloc.c and code_800FC620.c (new/delete)
  Makefile
  include/fault.h
  include/functions.h
  include/padmgr.h
  include/rand.h
  include/variables.h
  include/versions.h
  include/z64.h
  osMalloc.h
  spec
  src/boot/sprintf.c
  src/code/__osMalloc_gc.c
  src/code/__osMalloc_n64.c
  src/code/code_800FC620.c
  src/code/debug_malloc.c
  src/code/fault_gc.c
  src/code/fault_gc_drawer.c
  src/code/fault_n64.c
  src/code/game.c
  src/code/rand.c
  src/code/system_malloc.c
  src/code/z_malloc.c
  tools/disasm/ntsc-1.2/files_code.csv
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2101 [ntsc-1.2] Partially match gfxprint.c
  include/gfxprint.h
  src/code/gfxprint.c
Labels: Met Review Requirements

#2128 Jenkinsfile: `make -j` -> `make -j$(nproc)`
  Jenkinsfile
Labels: Met Review Requirements

#2126 unk_664 -> focusActor [Target Docs 5/?]
  include/z64player.h
  src/code/z_actor.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Zf/z_en_zf.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2017 Cleanup: Pass all paths to tools rather than tools constructing them
  Makefile
  diff_settings.py
  extract_assets.py
  first_diff.py
  retail_progress.py
  sym_info.py
  tools/check_disasm_metadata_unksyms.py
  tools/disasm/sym_info.py
  tools/extract_baserom.py
  tools/extract_incbins.py
  tools/fix_bss.py
  tools/ido_block_numbers.py
  tools/m2ctx.py
  tools/msgdis.py
Labels: Met Review Requirements

#2129 Pause doc: drawing the world map image
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: Met Review Requirements

#2127 [ntsc-1.2] Organize n64dd declarations and convert to 1.0 addresses
  data/cic6105.text.s
  include/cic6105.h
  include/functions.h
  include/n64dd.h
  include/segment_symbols.h
  include/ultra64/exception.h
  include/ultra64/ucode.h
  spec
  src/boot/cic6105.c
  src/boot/z_std_dma.c
  src/code/code_n64dd_800AD410.c
  src/code/code_n64dd_800AD4C0.c
  src/code/game.c
  src/code/main.c
  src/code/sys_math3d.c
  src/code/z_collision_check.c
  src/code/z_demo.c
  src/code/z_kaleido_setup.c
  src/code/z_play.c
  src/code/z_room.c
  src/code/z_scene_table.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/gamestates/ovl_select/z_select.c
  src/overlays/gamestates/ovl_title/z_title.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_lmap_mark.c
  tools/disasm/ntsc-1.2/files_boot.csv
  tools/disasm/ntsc-1.2/functions.txt
  tools/disasm/ntsc-1.2/variables.txt
  undefined_syms.txt
Labels: Met Review Requirements

#2098 [ntsc-1.2] Match z_message.c
  include/n64dd.h
  src/code/z_message.c
Labels: Met Review Requirements

#2131 Fix merge issue between z_message.c match and n64dd renames
  src/code/z_message.c
Labels: Needs first approval, Needs second approval

#2130 Pause docs: `WorldMapArea` enum and related data
  assets/xml/textures/icon_item_field_static.xml
  include/z64save.h
  src/code/sys_cfb.c
  src/code/sys_matrix.c
  src/code/z_play.c
  src/code/z_scene.c
  src/code/z_skin.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Needs first approval, Needs second approval

#2132 isTargeted -> isLockedOn [Target Docs 6/?]
  include/functions.h
  include/z64actor.h
  src/code/z_actor.c
  src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth.c
  src/overlays/actors/ovl_En_Dns/z_en_dns.c
  src/overlays/actors/ovl_En_GeldB/z_en_geldb.c
  src/overlays/actors/ovl_En_Hintnuts/z_en_hintnuts.c
  src/overlays/actors/ovl_En_Ko/z_en_ko.c
  src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
  src/overlays/actors/ovl_En_Poh/z_en_poh.c
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_En_Torch2/z_en_torch2.c
  src/overlays/actors/ovl_En_Wf/z_en_wf.c
  src/overlays/actors/ovl_En_Zf/z_en_zf.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2015 Update Room Documentation
  include/functions.h
  include/z64play.h
  include/z64scene.h
  src/code/fault_gc.c
  src/code/fault_gc_drawer.c
  src/code/main.c
  src/code/z_actor.c
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/code/z_play.c
  src/code/z_room.c
  src/code/z_scene.c
  src/code/z_scene_table.c
  src/overlays/actors/ovl_Bg_Dodoago/z_bg_dodoago.c
  src/overlays/actors/ovl_Bg_Mizu_Water/z_bg_mizu_water.c
  src/overlays/actors/ovl_Bg_Toki_Hikari/z_bg_toki_hikari.c
  src/overlays/actors/ovl_Bg_Toki_Swd/z_bg_toki_swd.c
  src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Holl/z_en_holl.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2124 Naming a function
  include/sfx.h
  src/audio/sfx.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2135 Document `Target_ShouldReleaseLockOn` [Target Docs 8/8]
  include/functions.h
  src/code/z_actor.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2138 Move button macros to include/controller.h
  include/controller.h
  include/macros.h
  include/ultra64/controller.h
  include/z64.h
  src/audio/general.c
  src/code/fault_n64.c
  src/code/z_debug.c
  src/code/z_frame_advance.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2134 Clean up uses of !PLATFORM_N64 vs PLATFORM_GC
  include/fault.h
  include/gfxprint.h
  include/libc/math.h
  include/rand.h
  include/z64interface.h
  osMalloc.h
  src/audio/general.c
  src/audio/sfx.c
  src/boot/stackcheck.c
  src/code/fp.s
  src/code/fp_math.c
  src/code/gfxprint.c
  src/code/rand.c
  src/code/z_eff_ss_dead.c
  src/code/z_message.c
  src/code/z_scene_table.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Met Review Requirements

#2139 Miscellaneous libultra header fixes
  include/ultra64/convert.h
  include/ultra64/rcp.h
  include/variables.h
  include/z64math.h
  src/code/fault_gc.c
  src/code/game.c
  src/code/graph.c
  src/code/irqmgr.c
  src/code/rand.c
  src/code/sys_math3d.c
  src/code/z_camera.c
  src/code/z_vimode.c
  src/libultra/io/vimodefpallan1.c
  src/libultra/io/vimodempallan1.c
  src/libultra/io/vimodentsclan1.c
  src/libultra/io/vimodepallan1.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2143 [ntsc-1.2] Fix size of leoDiskStack
  include/ultra64/leodrive.h
  src/libleo/api/cacreateleomanager.c
  src/libleo/api/cjcreateleomanager.c
  src/libleo/leo/leointerrupt.c
Labels: Met Review Requirements

#2144 [ntsc-1.2] Match z_actor_dlftbls.c
  include/fault.h
  src/code/fault_n64.c
  src/code/z_actor_dlftbls.c
Labels: Met Review Requirements

#2142 T() macro 8
  src/code/fault_gc.c
  src/code/fault_n64.c
  src/code/game.c
  src/code/gfxprint.c
  src/code/ucode_disas.c
  src/code/z_actor.c
  src/code/z_message.c
Labels: Met Review Requirements

#2145 [ntsc-1.2] Match more draw functions
  src/code/z_actor.c
  src/code/z_lights.c
  src/code/z_player_lib.c
  src/code/z_vr_box.c
Labels: Met Review Requirements

#2146 [ntsc-1.2] Match z_file_choose.c and z_boss_tw.c
  src/code/z_eff_blure.c
  src/code/z_eff_spark.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset.c
  tools/disasm/ntsc-1.2/files_ovl_file_choose.csv
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2150 [headers 7] Add sys_matrix.h
  include/functions.h
  include/macros.h
  include/sys_matrix.h
  include/variables.h
  include/z64.h
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2148 [headers 6] collision_check functions and structs
  include/functions.h
  include/z64actor.h
  include/z64collision_check.h
  src/code/z_collision_check.c
Labels: Met Review Requirements

#2141 Pause doc: World map points
  assets/xml/textures/map_name_static.xml
  assets/xml/textures/map_name_static_pal.xml
  include/z64pause.h
  src/code/fault_gc.c
  src/code/z_camera.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: Met Review Requirements

#2140 [ntsc-1.2] Match z_map_exp.c, z_map_mark.c
  include/n64dd.h
  src/code/z_map_exp.c
  src/code/z_map_mark.c
Labels: Met Review Requirements

#2152 Move audio/general.c debug bss with the rest of bss
  src/audio/debug.inc.c
  src/audio/general.c
Labels: Met Review Requirements

#1976 Move `Graph_Alloc` and open/close Disps to `gfx.h`
  include/functions.h
  include/gfx.h
  include/macros.h
  src/code/sys_math3d.c
  src/code/z_collision_check.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2154 Freeze SFX IDs in msgdis.py
  tools/msgdis.py
Labels: Met Review Requirements

#2155 [ntsc-1.2] Fix some boot and code data
  baseroms/ntsc-1.2/config.yml
  data/rsp.rodata.s
  data/rsp.text.s
  data/unk_80009410.data.s
  spec
  src/boot/z_std_dma.c
  src/code/code_800FC620.c
Labels: Met Review Requirements

#2156 [ntsc-1.2] Match more GC button colors
  src/code/z_message.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Met Review Requirements

#2157 [ntsc-1.2] Match N64 ROM header
  src/makerom/rom_header.s
Labels: Met Review Requirements

#2136 [ntsc-1.2] Import n64dd code from Decompollaborate/n64dd
  assets/xml/n64dd/error_textures.xml
  baseroms/ntsc-1.2/config.yml
  extract_assets.py
  include/functions.h
  include/n64dd.h
  include/variables.h
  include/z64.h
  spec
  src/n64dd/n64dd_801C8000.c
  src/n64dd/n64dd_801C8940.c
  src/n64dd/n64dd_801C9440.c
  src/n64dd/n64dd_801C9B70.c
  src/n64dd/n64dd_801CA0B0.c
  src/n64dd/n64dd_data_buffer.c
  src/n64dd/n64dd_error_bodies.c
  src/n64dd/n64dd_error_headers.c
  src/n64dd/n64dd_error_textures.c
  src/n64dd/z_n64dd.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  tools/disasm/ntsc-1.2/variables.txt
  tools/fix_bss.py
  undefined_syms.txt
Labels: Met Review Requirements

#2158 Pause doc: Trade quest marker
  include/z64pause.h
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: Met Review Requirements

#2160 Rename gBuildTeam to gBuildCreator
  include/variables.h
  src/boot/build.c
  src/boot/cic6105.c
  src/boot/idle.c
  src/overlays/gamestates/ovl_title/z_title.c
  tools/disasm/ntsc-1.2/variables.txt
Labels: Met Review Requirements

#2151 [headers 8] Add `main.h`, `segmented_address.h`, and changes for `main.c` symbols
  include/macros.h
  include/main.h
  include/padmgr.h
  include/sched.h
  include/segmented_address.h
  include/variables.h
  include/z64.h
  src/code/fault_gc.c
  src/code/main.c
  src/code/sys_math3d.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2147 [headers 5] Misc small headers untangling
  include/color.h
  include/functions.h
  include/seqcmd.h
  include/sequence.h
  include/variables.h
  include/z64environment.h
  include/z64play.h
  include/z64save.h
  src/overlays/actors/ovl_En_Kanban/z_en_kanban.c
  src/overlays/actors/ovl_En_Kanban/z_en_kanban.h
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Needs second approval

#2166 [headers 10] Move some function declarations to `z64{interface,light,message}.h`
  include/functions.h
  include/z64interface.h
  include/z64light.h
  include/z64message.h
Labels: Met Review Requirements

#2159 Pause doc: Cursor drawing
  include/z64pause.h
  src/code/z_parameter.c
  src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
  tools/disasm/ntsc-1.2/functions.txt
Labels: Met Review Requirements

#2167 Player Docs - Parallel
  include/z64player.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/ntsc-1.2/functions.txt
Labels: Needs second approval

#2163 [ntsc-1.2] Reorder spec segments for N64 versions
  spec
Labels: Met Review Requirements

#2169 fix_bss.py: Subtract addend for relocations against global symbols
  tools/fix_bss.py
Labels: Met Review Requirements

#2171 [headers 11] stackcheck.h, jpeg functions
  include/functions.h
  include/jpeg.h
  include/stack.h
  include/stackcheck.h
  include/z64.h
  src/code/fault_gc.c
  src/code/jpegdecoder.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2164 [headers 9] Add src/libc64/ and new "z64" rand.h
  Makefile
  include/functions.h
  include/libc64/qrand.h
  include/rand.h
  include/z64.h
  spec
  src/code/z_actor.c
  src/libc64/__osMalloc_gc.c
  src/libc64/__osMalloc_n64.c
  src/libc64/aprintf.c
  src/libc64/fp.s
  src/libc64/malloc.c
  src/libc64/math64.c
  src/libc64/qrand.c
  src/libc64/sleep.c
  src/libc64/sprintf.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  tools/disasm/ntsc-1.2/files_boot.csv
  tools/disasm/ntsc-1.2/files_code.csv
Labels: Met Review Requirements

#2173 Name `PLAYER_STATE1_ACTOR_CARRY`
  include/z64player.h
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Bg_Spot16_Bombstone/z_bg_spot16_bombstone.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.c
  src/overlays/actors/ovl_En_Dnt_Jiji/z_en_dnt_jiji.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2175 [headers 13] osMalloc.h -> include/libc64/os_malloc.h
  include/libc64/os_malloc.h
  include/variables.h
  src/code/code_800FC620.c
  src/code/debug_malloc.c
  src/code/fault_n64.c
  src/code/game.c
  src/code/z_malloc.c
  src/libc64/__osMalloc_gc.c
  src/libc64/__osMalloc_n64.c
  src/libc64/malloc.c
Labels: Met Review Requirements

#2168 Run fix_bss.py in Jenkins and generate a patch
  Jenkinsfile
  tools/fix_bss.py
  tools/generate_patch_from_jenkins.sh
Labels: Met Review Requirements

#2172 [Player ZTarget] Some func_80836BEC docs
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2179 fix_bss.py: Restore z_locale special case
  tools/fix_bss.py
Labels: Needs first approval, Needs second approval

#2180 Boomerang related state flags
  include/z64player.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_En_Boom/z_en_boom.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs first approval, Needs second approval

#2181 Added eye texture offsets for extraction for object_oE5.xml
  assets/xml/objects/object_oE5.xml
Labels: Met Review Requirements

#2184 More target related state flags
  include/z64player.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs first approval, Needs second approval

#2174 [headers 12] Add kaleido_manager.h, move various protos to headers
  include/functions.h
  include/gfxprint.h
  include/kaleido_manager.h
  include/libc/string.h
  include/variables.h
  include/z64.h
  include/z64interface.h
  include/z64pause.h
  src/code/z_kankyo.c
  src/libc/memmove.c
  src/libc/memset.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2183 [ntsc-1.2] Match N64 audio tables
  include/tables/sfx/enemybank_table.h
  include/tables/sfx/environmentbank_table.h
  include/tables/sfx/itembank_table.h
  src/audio/general.c
  src/audio/session_config.c
Labels: Met Review Requirements

#2185 Extract scripts make their own directories
  Makefile
  extract_assets.py
  tools/msgdis.py
Labels: Met Review Requirements

#2170 Pause doc: Prompt page and save prompt state
  include/regs.h
  include/z64pause.h
  src/code/fault_gc.c
  src/code/z_construct.c
  src/code/z_kaleido_scope_call.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_prompt.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: Met Review Requirements

#2188 Add OOT_PAL_N64 and move other shorthands to versions.h
  Makefile
  assets/text/nes_message_data_static.c
  docs/c_cpp_properties.json
  docs/vscode.md
  include/macros.h
  include/message_data_static.h
  include/regs.h
  include/segment_symbols.h
  include/versions.h
  include/z64.h
  include/z64message.h
  include/z64save.h
  src/code/z_actor.c
  src/code/z_construct.c
  src/code/z_kanfont.c
  src/code/z_parameter.c
  src/code/z_scene_table.c
  src/code/z_sram.c
  src/n64dd/n64dd_801C9440.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset.c
Labels: Met Review Requirements

#2187 [ntsc-1.2] Match ntsc-1.2 BSS and add to CI
  Jenkinsfile
  Makefile
  include/fault.h
  src/audio/general.c
  src/boot/boot_main.c
  src/boot/cic6105.c
  src/boot/idle.c
  src/boot/yaz0.c
  src/boot/z_std_dma.c
  src/code/fault_n64.c
  src/code/graph.c
  src/code/main.c
  src/code/speed_meter.c
  src/code/sys_math3d.c
  src/code/z_actor.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_common_data.c
  src/code/z_debug.c
  src/code/z_demo.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/code/z_player_call.c
  src/n64dd/z_n64dd.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  tools/disasm/ntsc-1.2/variables.txt
Labels: Met Review Requirements

#2178 Delete disassembly data for ntsc-1.2
  tools/disasm/ntsc-1.2/file_addresses.csv
  tools/disasm/ntsc-1.2/files_boot.csv
  tools/disasm/ntsc-1.2/files_code.csv
  tools/disasm/ntsc-1.2/files_makerom.csv
  tools/disasm/ntsc-1.2/files_ovl_file_choose.csv
  tools/disasm/ntsc-1.2/files_ovl_kaleido_scope.csv
  tools/disasm/ntsc-1.2/functions.txt
  tools/disasm/ntsc-1.2/variables.txt
Labels: Needs second approval

#2192 Ignore nonexistent extracted/VERSION/assets dir in Makefile
  Makefile
Labels: Met Review Requirements

#2193 Hostile Lock-On
  include/functions.h
  include/z64player.h
  src/code/z_actor.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_En_Zf/z_en_zf.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2196 More Player Z Target documentation
  include/z64player.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2137 [Audio 8/?] Check-in handwritten sequences, build sequences, automate various sfx arrays
  .gitattributes
  Makefile
  assets/audio/sequences/seq_0.prg.seq
  assets/audio/sequences/seq_1.prg.seq
  assets/audio/sequences/seq_109.prg.seq
  assets/audio/sequences/seq_2.prg.seq
  baseroms/gc-eu-mq-dbg/config.yml
  baseroms/gc-eu-mq/config.yml
  baseroms/gc-eu/config.yml
  baseroms/gc-jp-ce/config.yml
  baseroms/gc-jp-mq/config.yml
  baseroms/gc-jp/config.yml
  baseroms/gc-us-mq/config.yml
  baseroms/gc-us/config.yml
  baseroms/ntsc-1.2/config.yml
  data/audio_tables.rodata.s
  include/audio/aseq.h
  include/sequence.h
  include/sfx.h
  include/tables/sequence_table.h
  include/tables/sfx/enemybank_table.h
  include/tables/sfx/environmentbank_table.h
  include/tables/sfx/itembank_table.h
  include/tables/sfx/ocarinabank_table.h
  include/tables/sfx/playerbank_table.h
  include/tables/sfx/systembank_table.h
  include/tables/sfx/voicebank_table.h
  spec
  src/audio/general.c
  src/audio/sfx_params.c
  src/audio/tables/sequence_table.c
  tools/audio/audio_tablegen.c
  tools/audio/extraction/audio_extract.py
  tools/audio/extraction/disassemble_sequence.py
Labels: Met Review Requirements, wait

#2200 Document `zTargetActiveTimer`
  include/z64player.h
  src/code/z_actor.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs second approval

#2197 [PAL N64] Rename file select assets
  assets/xml/overlays/ovl_file_choose.xml
  assets/xml/overlays/ovl_file_choose_pal.xml
  assets/xml/textures/title_static.xml
  assets/xml/textures/title_static_pal.xml
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset.c
Labels: Needs second approval

#2203 Name `PLAYER_STATE1_CHARGING_SPIN_ATTACK`
  include/z64player.h
  src/code/z_actor.c
  src/code/z_camera.c
  src/overlays/actors/ovl_Eff_Dust/z_eff_dust.c
  src/overlays/actors/ovl_En_M_Thunder/z_en_m_thunder.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2198 [PAL N64] Match VI mode setup
  spec
  src/boot/idle.c
Labels: Needs second approval

#2204 `PLAYER_STATE1_DEAD`
  include/z64player.h
  src/code/z_actor.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Bg_Haka_Sgami/z_bg_haka_sgami.c
  src/overlays/actors/ovl_Bg_Jya_Goroiwa/z_bg_jya_goroiwa.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.c
  src/overlays/actors/ovl_En_Nutsball/z_en_nutsball.c
  src/overlays/actors/ovl_En_Okuta/z_en_okuta.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2199 Consistently use "OOT_VERSION <" and "OOT_VERSION >="
  Makefile
  spec
  src/n64dd/n64dd_801C8000.c
  src/n64dd/z_n64dd.c
Labels: Met Review Requirements

#2208 [PAL N64] Match actor changes that aren't in NTSC 1.2 or GC releases
  src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
  src/overlays/actors/ovl_En_Dnt_Nomal/z_en_dnt_nomal.c
  src/overlays/actors/ovl_En_Heishi3/z_en_heishi3.c
  src/overlays/actors/ovl_En_Ik/z_en_ik.c
  src/overlays/actors/ovl_En_Ma3/z_en_ma3.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
Labels: Met Review Requirements

#2206 [PAL N64] Create macros for 50-Hz-related values
  include/macros.h
  src/audio/general.c
  src/audio/lib/heap.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Demo_Effect/z_demo_effect.c
  src/overlays/actors/ovl_End_Title/z_end_title.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2209 [headers] z64inventory.h, move savectx/inventory macros to z64save.h
  include/functions.h
  include/macros.h
  include/variables.h
  include/z64.h
  include/z64inventory.h
  include/z64save.h
  src/boot/z_std_dma.c
  src/code/graph.c
  src/code/main.c
  src/code/z_camera.c
  src/code/z_common_data.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2210 [PAL N64] Match handwritten audio sequences
  Makefile
  assets/audio/sequences/seq_0.prg.seq
  assets/audio/sequences/seq_109.prg.seq
  include/macros.h
  include/versions.h
Labels: Met Review Requirements

#2212 Document `autoLockOnActor`
  include/functions.h
  include/z64player.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_En_Dh/z_en_dh.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2213 `PLAYER_STATE1_ACTOR_CARRY` -> `PLAYER_STATE1_CARRYING_ACTOR`
  include/z64player.h
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Bg_Spot16_Bombstone/z_bg_spot16_bombstone.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.c
  src/overlays/actors/ovl_En_Dnt_Jiji/z_en_dnt_jiji.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2092 Partially document idle animations
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2214 Standardize "ActorMovement" over "ActorMove"
  include/z64animation.h
  src/code/z_player_lib.c
  src/code/z_skelanime.c
  src/overlays/actors/ovl_Demo_Ec/z_demo_ec.c
  src/overlays/actors/ovl_Demo_Ik/z_demo_ik.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_En_Zl1/z_en_zl1.c
  src/overlays/actors/ovl_En_Zl4/z_en_zl4.c
  src/overlays/actors/ovl_Obj_Hsblock/z_obj_hsblock.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2216 [headers] Move z_actor functions to z64actor.h
  include/functions.h
  include/z64actor.h
  src/boot/z_std_dma.c
  src/code/main.c
  src/code/z_camera.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2211 [PAL N64] Miscellaneous changes
  src/audio/lib/load.c
  src/code/z_play.c
  src/code/z_scene.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Needs second approval

#2217 Z-Targeting Loose Ends
  include/functions.h
  src/code/z_actor.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs second approval

#2215 Pause doc: `KaleidoScope_DrawQuestStatus` (partial)
  include/regs.h
  src/code/z_construct.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
Labels: Met Review Requirements

#2222 create ucode_disas.h
  include/functions.h
  include/gfx.h
  include/ucode_disas.h
  src/boot/z_std_dma.c
  src/code/graph.c
  src/code/main.c
  src/code/ucode_disas.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_common_data.c
  src/code/z_kankyo.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2221 [headers] gfx_setupdl.h and z64skin_matrix.h
  include/functions.h
  include/gfx.h
  include/gfx_setupdl.h
  include/z64.h
  include/z64skin_matrix.h
  src/boot/z_std_dma.c
  src/code/main.c
  src/code/z_camera.c
  src/overlays/actors/ovl_En_Po_Field/z_en_po_field.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2220 Pause docs: Songs playback
  include/regs.h
  include/z64pause.h
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Needs first approval, Needs second approval

#2223 [headers] audio functions to z64audio.h and z64ocarina.h
  include/functions.h
  include/z64audio.h
  include/z64ocarina.h
  src/code/main.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2219 Player: ActionChange -> ActionHandler
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2225 [headers] Create letterbox.h, move more protos from functions.h
  include/functions.h
  include/letterbox.h
  include/z64.h
  include/z64camera.h
  include/z64cutscene.h
  include/z64environment.h
  src/boot/z_std_dma.c
  src/code/main.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_common_data.c
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#1949 Player Docs: `Player_ActionChange_6`, Rolling and Put Away
  include/z64player.h
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2202 [PAL N64] Match z_message.c
  include/n64dd.h
  src/code/z_message.c
Labels: Met Review Requirements

#2226 Player: `Player_ActionHandler_Talk`
  include/z64player.h
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2224 Pause docs: Quest quads
  include/z64item.h
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: Met Review Requirements

#2227 [ntsc-1.0/1.1] Match actor changes introduced in PAL 1.0
  src/overlays/actors/ovl_Bg_Hidan_Hamstep/z_bg_hidan_hamstep.c
  src/overlays/actors/ovl_Bg_Mori_Hineri/z_bg_mori_hineri.c
  src/overlays/actors/ovl_Bg_Treemouth/z_bg_treemouth.c
  src/overlays/actors/ovl_Demo_Effect/z_demo_effect.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_En_Bw/z_en_bw.c
  src/overlays/actors/ovl_En_Dha/z_en_dha.c
  src/overlays/actors/ovl_En_Dnt_Nomal/z_en_dnt_nomal.c
  src/overlays/actors/ovl_En_Go2/z_en_go2.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Kz/z_en_kz.c
  src/overlays/actors/ovl_En_Ma3/z_en_ma3.c
  src/overlays/actors/ovl_En_Mb/z_en_mb.c
  src/overlays/actors/ovl_En_Okarina_Effect/z_en_okarina_effect.c
  src/overlays/actors/ovl_En_Weather_Tag/z_en_weather_tag.c
  src/overlays/actors/ovl_En_Wf/z_en_wf.c
Labels: Met Review Requirements

#2228 [ntsc-1.0/1.1] Match z_boss_ganon.c and z_boss_ganon2.c changes from PAL 1.0
  assets/xml/overlays/ovl_Boss_Ganon2.xml
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2_data.inc.c
Labels: Met Review Requirements

#2229 Fix typos found by codespell
  extract_assets.py
  include/padmgr.h
  include/regs.h
  include/z64actor.h
  include/z64animation.h
  include/z64camera.h
  include/z64player.h
  src/code/main.c
  src/code/title_setup.c
  src/code/z_camera.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_Demo_Effect/z_demo_effect.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Boom/z_en_boom.c
  src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.c
  src/overlays/actors/ovl_En_Daiku_Kakariko/z_en_daiku_kakariko.c
  src/overlays/actors/ovl_En_Fd/z_en_fd.c
  src/overlays/actors/ovl_En_Fr/z_en_fr.c
  src/overlays/actors/ovl_En_Ganon_Mant/z_en_ganon_mant.c
  src/overlays/actors/ovl_En_Ishi/z_en_ishi.h
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_En_St/z_en_st.c
  src/overlays/actors/ovl_En_St/z_en_st.h
  src/overlays/actors/ovl_En_Syateki_Niw/z_en_syateki_niw.h
  src/overlays/actors/ovl_En_Toryo/z_en_toryo.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/audio/soundfont_compiler.c
  tools/check_format.py
  tools/disasm/sym_info.py
  tools/namefixer.py
  tools/preprocess.sh
Labels: Met Review Requirements

#2234 [headers] Move libultra protos to ultra64.h (as a temporary measure)
  include/functions.h
  include/ultra64.h
  src/boot/z_std_dma.c
  src/code/main.c
  src/code/sys_math3d.c
  src/code/z_camera.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kankyo.c
  src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2235 [includes] Explicit global.h includes for z_player
  src/overlays/actors/ovl_Bg_Heavy_Block/z_bg_heavy_block.c
  src/overlays/actors/ovl_Bg_Heavy_Block/z_bg_heavy_block.h
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.h
  src/overlays/actors/ovl_Elf_Msg/z_elf_msg.c
  src/overlays/actors/ovl_Elf_Msg/z_elf_msg.h
  src/overlays/actors/ovl_En_Arrow/z_en_arrow.c
  src/overlays/actors/ovl_En_Arrow/z_en_arrow.h
  src/overlays/actors/ovl_En_Boom/z_en_boom.c
  src/overlays/actors/ovl_En_Boom/z_en_boom.h
  src/overlays/actors/ovl_En_Box/z_en_box.c
  src/overlays/actors/ovl_En_Box/z_en_box.h
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Door/z_en_door.h
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.h
  src/overlays/actors/ovl_En_Fish/z_en_fish.c
  src/overlays/actors/ovl_En_Fish/z_en_fish.h
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.h
  src/overlays/actors/ovl_En_Insect/z_en_insect.c
  src/overlays/actors/ovl_En_Insect/z_en_insect.h
  src/overlays/actors/ovl_Obj_Makekinsuta/z_obj_makekinsuta.c
  src/overlays/actors/ovl_Obj_Makekinsuta/z_obj_makekinsuta.h
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/effects/ovl_Effect_Ss_Fhg_Flash/z_eff_ss_fhg_flash.h
Labels: Met Review Requirements

#2232 [ntsc-1.0/1.1] Match z_player.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2236 Pause doc: Quest page cursor movement
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
Labels: Met Review Requirements

#2233 [headers] Create `gfxalloc.h`, `map.h`, move protos to `gfx.h`, `z64{player,view}.h`
  include/functions.h
  include/gfx.h
  include/gfxalloc.h
  include/macros.h
  include/map.h
  include/z64.h
  include/z64actor.h
  include/z64player.h
  include/z64view.h
  src/boot/z_std_dma.c
  src/code/main.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_en_item00.c
  src/code/z_kaleido_scope_call.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Needs second approval

#2242 [includes] z_fishing
  src/overlays/actors/ovl_Fishing/z_fishing.c
Labels: Met Review Requirements

#2231 [ntsc-1.0/1.1] Match PAL 1.0 viconfig changes
  data/unk_80009410.data.s
  include/gfx.h
  include/sched.h
  spec
  src/boot/carthandle.c
  src/boot/idle.c
  src/boot/viconfig.c
  src/boot/z_locale.c
  src/code/game.c
  src/code/graph.c
  src/code/sched.c
  src/code/z_prenmi.c
Labels: Met Review Requirements

#2238 Pause doc: Item page quads
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: Met Review Requirements

#2246 [PAL N64] Completely match pal-1.0 and pal-1.1 and add to CI
  Jenkinsfile
  Makefile
  src/boot/yaz0.c
  src/boot/z_std_dma.c
  src/code/fault_n64.c
  src/code/graph.c
  src/code/main.c
  src/code/speed_meter.c
  src/code/sys_cfb.c
  src/code/sys_math3d.c
  src/code/sys_matrix.c
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_common_data.c
  src/code/z_debug.c
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/code/z_player_call.c
  src/code/z_skin.c
  src/n64dd/z_n64dd.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  tools/fix_bss.py
Labels: Met Review Requirements

#2230 Name Talking Related Actor Flags
  include/z64actor.h
  src/code/z_message.c
  src/overlays/actors/ovl_Elf_Msg2/z_elf_msg2.c
  src/overlays/actors/ovl_En_Cow/z_en_cow.c
  src/overlays/actors/ovl_En_Dns/z_en_dns.c
  src/overlays/actors/ovl_En_Ds/z_en_ds.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/actors/ovl_En_Ge1/z_en_ge1.c
  src/overlays/actors/ovl_En_Ge2/z_en_ge2.c
  src/overlays/actors/ovl_En_Ge3/z_en_ge3.c
  src/overlays/actors/ovl_En_Heishi2/z_en_heishi2.c
  src/overlays/actors/ovl_En_Hintnuts/z_en_hintnuts.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Js/z_en_js.c
  src/overlays/actors/ovl_En_Ma1/z_en_ma1.c
  src/overlays/actors/ovl_En_Ma2/z_en_ma2.c
  src/overlays/actors/ovl_En_Ma3/z_en_ma3.c
  src/overlays/actors/ovl_En_Mk/z_en_mk.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Po_Field/z_en_po_field.c
  src/overlays/actors/ovl_En_Po_Relay/z_en_po_relay.c
  src/overlays/actors/ovl_En_Poh/z_en_poh.c
  src/overlays/actors/ovl_En_Ta/z_en_ta.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2244 [ntsc-1.0/1.1] Match "game engine" files
  src/code/z_actor.c
  src/code/z_collision_check.c
  src/code/z_construct.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/code/z_onepointdemo.c
  src/code/z_parameter.c
  src/code/z_room.c
  src/code/z_scene.c
  src/code/z_sram.c
Labels: Met Review Requirements
