Repository zeldaret/oot, pull requests merged in 2024-11, with the labels that each got.

#2267 libu64
  Makefile
  docs/libu64.md
  spec
  src/libu64/code_800FC620.c
  src/libu64/debug.c
  src/libu64/gfxprint.c
  src/libu64/load_gc.c
  src/libu64/loadfragment2_gc.c
  src/libu64/loadfragment2_n64.c
  src/libu64/logseverity_gc.c
  src/libu64/mtxuty-cvt.c
  src/libu64/pad.c
  src/libu64/padsetup.c
  src/libu64/rcp_utils.c
  src/libu64/relocation_gc.c
  src/libu64/stackcheck.c
Labels: Met Review Requirements

#2285 `ACTOR_FLAG_ENKUSA_CUT` -> `ACTOR_FLAG_GRASS_DESTROYED`
  include/z64actor.h
  src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
  src/overlays/actors/ovl_Obj_Mure/z_obj_mure.c
Labels: Met Review Requirements

#2293 [ntsc-1.0/1.1] Match audio and loose ends
  assets/audio/sequences/seq_0.prg.seq
  assets/audio/sequences/seq_109.prg.seq
  include/z64.h
  spec
  src/code/z_scene_table.c
  src/overlays/effects/ovl_Effect_Ss_En_Ice/z_eff_ss_en_ice.c
  src/overlays/effects/ovl_Effect_Ss_Kakera/z_eff_ss_kakera.c
Labels: Met Review Requirements

#2291 [Audio 9/?] Multiversion samplebank and soundfont extraction xmls, 1.0 and 1.1 audio extraction
  assets/xml/audio/samplebanks/SampleBank_0.xml
  assets/xml/audio/samplebanks/SampleBank_2.xml
  assets/xml/audio/samplebanks/SampleBank_3.xml
  assets/xml/audio/samplebanks/SampleBank_4.xml
  assets/xml/audio/samplebanks/SampleBank_5.xml
  assets/xml/audio/samplebanks/SampleBank_6.xml
  assets/xml/audio/soundfonts/Soundfont_10.xml
  tools/audio/extraction/audio_extract.py
  tools/audio/extraction/audiobank_file.py
  tools/audio/extraction/audiotable.py
  tools/audio/extraction/extraction_xml.py
  tools/audio_extraction.py
Labels: Met Review Requirements

#2273 Use the T macro in z_select
  src/overlays/gamestates/ovl_select/z_select.c
Labels: Met Review Requirements

#2283 Document `enum PauseState` game over parts
  include/z64pause.h
  src/code/z_game_over.c
  src/code/z_kaleido_scope_call.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_prompt.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Met Review Requirements

#2298 Use debug macros even in N64-only code
  include/unk.h
  src/boot/z_std_dma.c
  src/code/code_n64dd_800AD410.c
  src/code/z_kanfont.c
  src/code/z_map_exp.c
  src/code/z_message.c
  src/code/z_play.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Met Review Requirements

#2292 Fix VROM address handling in sym_info.py
  sym_info.py
Labels: Needs second approval

#2301 Player Docs: Begin "Start Mode" Documentation
  include/z64player.h
  src/boot/z_std_dma.c
  src/code/fault_n64.c
  src/code/graph.c
  src/code/main.c
  src/code/z_camera.c
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2302 Player: Name all Start Modes
  include/z64player.h
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2300 Document Hookshot Attachment
  include/z64actor.h
  src/code/z_actor.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.h
  src/overlays/actors/ovl_Bg_Spot06_Objects/z_bg_spot06_objects.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_En_Boom/z_en_boom.c
  src/overlays/actors/ovl_En_Fd/z_en_fd.c
  src/overlays/actors/ovl_En_Fw/z_en_fw.c
  src/overlays/actors/ovl_En_Si/z_en_si.c
Labels: Needs second approval

#2304 Add a PARAMS_PACK macro for building actor params setters
  include/z64actor.h
Labels: Needs second approval

#2306 Name Remaining Hookshot Actor Flags
  include/z64actor.h
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Bg_Spot06_Objects/z_bg_spot06_objects.c
  src/overlays/actors/ovl_Boss_Fd2/z_boss_fd2.c
  src/overlays/actors/ovl_Boss_Ganon/z_boss_ganon.c
  src/overlays/actors/ovl_Boss_Ganondrof/z_boss_ganondrof.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_En_Dh/z_en_dh.c
  src/overlays/actors/ovl_En_Fd/z_en_fd.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Fw/z_en_fw.c
  src/overlays/actors/ovl_En_Fz/z_en_fz.c
  src/overlays/actors/ovl_En_Ik/z_en_ik.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Kakasi2/z_en_kakasi2.c
  src/overlays/actors/ovl_En_Kakasi3/z_en_kakasi3.c
  src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_En_Rr/z_en_rr.c
  src/overlays/actors/ovl_En_Si/z_en_si.c
  src/overlays/actors/ovl_En_Skjneedle/z_en_skjneedle.c
  src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#2305 Player Docs: Document Some Start Mode Actions
  include/z64player.h
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs first approval, Needs second approval

#2310 Document time-specific textures for Deku Tree and Gerudo Fortress similar to other scenes
  assets/xml/scenes/dungeons/ydan.xml
  assets/xml/scenes/dungeons/ydan_mq.xml
  assets/xml/scenes/overworld/spot12.xml
  assets/xml/scenes/overworld/spot12_pal_n64.xml
  src/code/z_scene_table.c
Labels: Needs second approval
