Repository zeldaret/oot, pull requests merged in 2024-02, with the labels that each got.

#1675 Gamealloc, Graph, and Graphalloc retail OK
  include/functions.h
  spec
  src/code/flg_set.c
  src/code/game.c
  src/code/gamealloc.c
  src/code/gfxalloc.c
  src/code/graph.c
  src/code/z_debug.c
  src/code/z_demo.c
  src/code/z_kankyo.c
  src/code/z_message_PAL.c
  src/code/z_play.c
  src/code/z_rcp.c
  src/code/z_vismono.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_debug.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
  tools/disasm/gc-eu-mq/files_code.csv
  tools/disasm/gc-eu-mq/functions.txt
Labels: Met Review Requirements

#1678 Irqmgr and Sched Retail OK
  src/code/irqmgr.c
  src/code/sched.c
Labels: Met Review Requirements

#1681 z_view.c gc-eu-mq OK
  include/functions.h
  include/macros.h
  include/z64view.h
  src/code/z_actor.c
  src/code/z_view.c
  tools/m2ctx.py
  tools/permuter_settings.toml
Labels: Met Review Requirements

#1677 Retail z_scene matching
  include/variables.h
  include/z64scene.h
  src/code/z_scene.c
Labels: Met Review Requirements

#1682 Match retail sys_matrix.c
  include/functions.h
  src/code/sys_matrix.c
Labels: Met Review Requirements

#1685 Use IDO_PRINTF_WORKAROUND everywhere
  src/code/sched.c
  src/code/z_actor.c
Labels: Met Review Requirements

#1686 [Faster CI] Make CI not run CC_CHECK
  Jenkinsfile
  Makefile
Labels: Needs first approval, Needs second approval

#1688 z_play retail OK
  include/macros.h
  src/code/graph.c
  src/code/z_play.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_select/z_select.c
  src/overlays/gamestates/ovl_title/z_title.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Labels: Needs second approval

#1692 Match retail Title and Sample gamestates
  include/functions.h
  src/code/z_view.c
  src/overlays/gamestates/ovl_title/z_title.c
Labels: Needs second approval

#1679 Retail z_actor_dlftbls matched
  src/code/z_actor_dlftbls.c
Labels: Needs second approval

#1656 Match stackcheck.c and code_800FC620.c
  src/boot/stackcheck.c
  src/code/code_800FC620.c
Labels: Needs second approval

#1690 Match retail effects files in code
  src/code/z_eff_blure.c
  src/code/z_eff_shield_particle.c
  src/code/z_eff_spark.c
  src/code/z_effect_soft_sprite.c
Labels: Met Review Requirements

#1693 Match retail padmgr.c and sys_rumble.c
  include/macros.h
  include/ultra64/motor.h
  src/code/padmgr.c
  src/code/sys_rumble.c
  src/libultra/io/motor.c
Labels: Met Review Requirements

#1694 Match z_debug for retail
  include/functions.h
  src/code/z_debug.c
Labels: Met Review Requirements

#1695 Retail File Select OK
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset_PAL.c
Labels: Met Review Requirements

#1696 Misc Small Retail Files Part 2 OK
  src/code/code_800430A0.c
  src/code/code_80043480.c
  src/code/z_draw.c
  src/code/z_horse.c
Labels: Met Review Requirements

#1697 Match retail z_skin.c, z_skin_awb.c, z_skin_matrix.c
  include/macros.h
  src/code/z_skin.c
  src/code/z_skin_awb.c
  src/code/z_skin_matrix.c
Labels: Met Review Requirements

#1698 Match retail code_800D31A0.c
  include/variables.h
  src/code/code_800D31A0.c
Labels: Needs second approval

#1699 Match retail logutils.c and z_locale.c
  include/functions.h
  src/boot/logutils.c
  src/boot/z_locale.c
Labels: Met Review Requirements

#1671 `.clang-format`: break short enums, TypenameMacros
  .clang-format
  src/code/ucode_disas.c
  src/code/z_skelanime.c
Labels: Needs second approval

#1683 Match retail system_malloc.c and z_malloc.c
  include/functions.h
  src/code/system_malloc.c
  src/code/z_malloc.c
Labels: Met Review Requirements

#1651 Move roms to build folder
  Makefile
  README.md
  baseroms/gc-eu-mq-dbg/checksum-compressed.md5
  baseroms/gc-eu-mq-dbg/checksum.md5
  baseroms/gc-eu-mq/checksum-compressed.md5
  baseroms/gc-eu-mq/checksum.md5
  diff_settings.py
  docs/retail_versions.md
  first_diff.py
  progress.py
  sym_info.py
  tools/assist.py
Labels: Needs first approval, Needs second approval

#1684 Match retail __osMalloc.c
  include/functions.h
  include/z64.h
  src/code/__osMalloc.c
Labels: Met Review Requirements

#1700 Give debug_malloc.c the same treatment as system_malloc.c and z_malloc.c
  include/functions.h
  include/macros.h
  src/code/db_camera.c
  src/code/debug_malloc.c
Labels: Met Review Requirements

#1705 Match some overlay effects files
  src/overlays/effects/ovl_Effect_Ss_Bubble/z_eff_ss_bubble.c
  src/overlays/effects/ovl_Effect_Ss_Dead_Dd/z_eff_ss_dead_dd.c
  src/overlays/effects/ovl_Effect_Ss_Dust/z_eff_ss_dust.c
  src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
  src/overlays/effects/ovl_Effect_Ss_Fhg_Flash/z_eff_ss_fhg_flash.c
  src/overlays/effects/ovl_Effect_Ss_Ice_Smoke/z_eff_ss_ice_smoke.c
  src/overlays/effects/ovl_Effect_Ss_Kakera/z_eff_ss_kakera.c
  src/overlays/effects/ovl_Effect_Ss_Sibuki/z_eff_ss_sibuki.c
Labels: Met Review Requirements

#1704 Match compression for gc-eu-mq
  Makefile
  baseroms/gc-eu-mq-dbg/checksum-compressed.md5
  include/tables/dmadata_table.h
  include/tables/scene_table.h
  include/z64scene.h
  spec
  tools/compress.py
  tools/decompress_baserom.py
  tools/dmadata.py
  tools/dmadata_start.sh
  tools/mkdmadata.c
  tools/spec.c
  tools/spec.h
Labels: Met Review Requirements

#1711 Match more retail actors
  src/overlays/actors/ovl_Obj_Bean/z_obj_bean.c
  src/overlays/actors/ovl_Obj_Hsblock/z_obj_hsblock.c
  src/overlays/actors/ovl_Obj_Kibako2/z_obj_kibako2.c
  src/overlays/actors/ovl_Obj_Mure/z_obj_mure.c
  src/overlays/actors/ovl_Obj_Mure3/z_obj_mure3.c
  src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.c
  src/overlays/actors/ovl_Obj_Warp2block/z_obj_warp2block.c
  src/overlays/actors/ovl_Object_Kankyo/z_object_kankyo.c
  src/overlays/actors/ovl_Oceff_Wipe/z_oceff_wipe.c
  src/overlays/actors/ovl_Shot_Sun/z_shot_sun.c
Labels: Met Review Requirements

#1709 Extract ROM segments from gc-eu-mq (take 2)
  Makefile
  baseroms/gc-eu-mq-dbg/dmadata_names.txt
  baseroms/gc-eu-mq-dbg/dmadata_start.txt
  baseroms/gc-eu-mq/dmadata_names.txt
  baseroms/gc-eu-mq/dmadata_start.txt
  extract_baserom.py
  tools/compress.py
  tools/decompress_baserom.py
  tools/extract_baserom.py
Labels: Met Review Requirements

#1712 Retail Player Matches part 1
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#1710 PreRender.c retail 1 not matching
  src/code/PreRender.c
Labels: Met Review Requirements

#1717 Overlay Effects Retail OK
  src/overlays/effects/ovl_Effect_Ss_Bomb/z_eff_ss_bomb.c
  src/overlays/effects/ovl_Effect_Ss_Bomb2/z_eff_ss_bomb2.c
  src/overlays/effects/ovl_Effect_Ss_Stone1/z_eff_ss_stone1.c
Labels: Needs first approval, Needs second approval

#1716 z_construct.c retail OK
  src/code/z_construct.c
Labels: Needs second approval

#1713 rcp retail OK
  src/code/z_rcp.c
Labels: Met Review Requirements

#1718 Retail Player_Update/Noclip mode + some docs
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Met Review Requirements

#1723 Split msgdis from extract_assets
  Makefile
  extract_assets.py
  tools/msgdis.py
Labels: Needs first approval, Needs second approval

#1725 Retail Player matches part 2
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs second approval

#1667 Reorder boot/code spec includes for retail
  spec
  src/code/z_camera.c
Labels: Needs second approval

#1731 Don't link z_moji.o in retail
  spec
Labels: Needs first approval, Needs second approval

#1727 Match retail z_fbdemo.c and z_fbdemo_fade.c
  src/code/z_fbdemo.c
  src/code/z_fbdemo_fade.c
Labels: Met Review Requirements

#1722 Match retail z_sram.c
  include/functions.h
  src/code/z_sram.c
  src/code/z_ss_sram.c
Labels: Met Review Requirements

#1724 Match more small code files
  src/code/audio_thread_manager.c
  src/code/z_fcurve_data_skelanime.c
  src/code/z_map_mark.c
  src/code/z_viszbuf.c
Labels: Met Review Requirements

#1729 Skelanime + Kanfont Retail OK
  src/code/z_kanfont.c
  src/code/z_skelanime.c
Labels: Met Review Requirements

#1703 Misc 1: Retail Overlay Actors OK
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Bg_Bdan_Switch/z_bg_bdan_switch.c
  src/overlays/actors/ovl_Bg_Dy_Yoseizo/z_bg_dy_yoseizo.c
  src/overlays/actors/ovl_Bg_Ganon_Otyuka/z_bg_ganon_otyuka.c
  src/overlays/actors/ovl_Bg_Gnd_Soulmeiro/z_bg_gnd_soulmeiro.c
  src/overlays/actors/ovl_Bg_Haka_Gate/z_bg_haka_gate.c
  src/overlays/actors/ovl_Bg_Haka_Megane/z_bg_haka_megane.c
  src/overlays/actors/ovl_Bg_Haka_Ship/z_bg_haka_ship.c
  src/overlays/actors/ovl_Bg_Haka_Trap/z_bg_haka_trap.c
  src/overlays/actors/ovl_Bg_Heavy_Block/z_bg_heavy_block.c
  src/overlays/actors/ovl_Bg_Hidan_Curtain/z_bg_hidan_curtain.c
  src/overlays/actors/ovl_Bg_Hidan_Firewall/z_bg_hidan_firewall.c
Labels: Met Review Requirements

#1732 Convert spec indentation to spaces
  spec
Labels: Needs second approval

#1733 Match InitDynaPoly actors
  src/overlays/actors/ovl_Bg_Ice_Shelter/z_bg_ice_shelter.c
  src/overlays/actors/ovl_Bg_Jya_1flift/z_bg_jya_1flift.c
  src/overlays/actors/ovl_Bg_Jya_Amishutter/z_bg_jya_amishutter.c
  src/overlays/actors/ovl_Bg_Jya_Bombiwa/z_bg_jya_bombiwa.c
  src/overlays/actors/ovl_Bg_Jya_Cobra/z_bg_jya_cobra.c
  src/overlays/actors/ovl_Bg_Jya_Kanaami/z_bg_jya_kanaami.c
  src/overlays/actors/ovl_Bg_Jya_Zurerukabe/z_bg_jya_zurerukabe.c
  src/overlays/actors/ovl_Bg_Mori_Bigst/z_bg_mori_bigst.c
  src/overlays/actors/ovl_Bg_Mori_Hashigo/z_bg_mori_hashigo.c
  src/overlays/actors/ovl_Bg_Mori_Hashira4/z_bg_mori_hashira4.c
  src/overlays/actors/ovl_Bg_Spot08_Iceblock/z_bg_spot08_iceblock.c
  src/overlays/actors/ovl_Bg_Spot12_Gate/z_bg_spot12_gate.c
  src/overlays/actors/ovl_Bg_Spot12_Saku/z_bg_spot12_saku.c
  src/overlays/actors/ovl_Bg_Spot15_Rrbox/z_bg_spot15_rrbox.c
  src/overlays/actors/ovl_Obj_Bean/z_obj_bean.c
  src/overlays/actors/ovl_Obj_Elevator/z_obj_elevator.c
  src/overlays/actors/ovl_Obj_Hsblock/z_obj_hsblock.c
  src/overlays/actors/ovl_Obj_Lift/z_obj_lift.c
  src/overlays/actors/ovl_Obj_Oshihiki/z_obj_oshihiki.c
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.c
Labels: Needs second approval

#1702 Match Retail Kaleido Code Files
  src/code/z_kaleido_manager.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kaleido_setup.c
Labels: Met Review Requirements

#1734 Match Retail BgCheck
  src/code/z_bgcheck.c
Labels: Met Review Requirements

#1706 Diff .data size, .bss size, and .rodata contents in retail_progress.py
  Makefile
  retail_progress.py
Labels: Needs first approval, Needs second approval

#1736 Match retail z_message_PAL.c
  src/code/z_message_PAL.c
Labels: Met Review Requirements

#1738 Match OnePointCutscene_Init by inlining static data
  src/code/z_onepointdemo.c
  src/code/z_onepointdemo_data.inc.c
Labels: Met Review Requirements

#1739 Match the rest of z_onepointdemo.c
  src/code/z_onepointdemo.c
Labels: Met Review Requirements

#1708 Syms DMA Entries Extraction Support
  tools/compress.py
  tools/decompress_baserom.py
  tools/dmadata.py
  tools/extract_baserom.py
  tools/spec.c
  tools/spec.h
Labels: Met Review Requirements

#1728 Rework disassembly: out of makefile, separate sections, relocs
  Makefile
  include/macro.inc
  requirements.txt
  tools/disasm/disasm.py
  tools/disasm/do_disasm.sh
  tools/disasm/gc-eu-mq/files_boot.csv
  tools/disasm/gc-eu-mq/files_code.csv
  tools/disasm/gc-eu-mq/files_ovl_file_choose.csv
  tools/disasm/gc-eu-mq/files_ovl_kaleido_scope.csv
  tools/disasm/list_generated_files.py
Labels: Met Review Requirements

#1720 Match even more retail actors
  src/overlays/actors/ovl_En_Anubice_Tag/z_en_anubice_tag.c
  src/overlays/actors/ovl_En_Changer/z_en_changer.c
  src/overlays/actors/ovl_En_Dnt_Demo/z_en_dnt_demo.c
  src/overlays/actors/ovl_En_Encount1/z_en_encount1.c
  src/overlays/actors/ovl_En_Fire_Rock/z_en_fire_rock.c
  src/overlays/actors/ovl_En_Fr/z_en_fr.c
  src/overlays/actors/ovl_En_G_Switch/z_en_g_switch.c
  src/overlays/actors/ovl_En_Heishi1/z_en_heishi1.c
  src/overlays/actors/ovl_En_Kakasi2/z_en_kakasi2.c
  src/overlays/actors/ovl_En_Okarina_Effect/z_en_okarina_effect.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
  src/overlays/actors/ovl_En_Reeba/z_en_reeba.c
  src/overlays/actors/ovl_En_Skj/z_en_skj.c
  src/overlays/actors/ovl_En_Syateki_Itm/z_en_syateki_itm.c
  src/overlays/actors/ovl_En_Wall_Tubo/z_en_wall_tubo.c
  src/overlays/actors/ovl_En_Weather_Tag/z_en_weather_tag.c
  src/overlays/actors/ovl_En_Wonder_Item/z_en_wonder_item.c
  src/overlays/actors/ovl_En_Wonder_Item/z_en_wonder_item.h
  src/overlays/actors/ovl_En_Wonder_Talk/z_en_wonder_talk.c
  src/overlays/actors/ovl_En_Wonder_Talk2/z_en_wonder_talk2.c
  src/overlays/actors/ovl_En_Wood02/z_en_wood02.c
  src/overlays/actors/ovl_En_Yabusame_Mark/z_en_yabusame_mark.c
  src/overlays/actors/ovl_En_fHG/z_en_fhg.c
  src/overlays/actors/ovl_End_Title/z_end_title.c
  src/overlays/actors/ovl_Magic_Dark/z_magic_dark.c
  src/overlays/actors/ovl_Mir_Ray/z_mir_ray.c
Labels: Met Review Requirements

#1744 Update `mapfile_parser`
  requirements.txt
Labels: Met Review Requirements

#1743 Match the rest of retail BG actors
  src/overlays/actors/ovl_Bg_Hidan_Hamstep/z_bg_hidan_hamstep.c
  src/overlays/actors/ovl_Bg_Hidan_Hrock/z_bg_hidan_hrock.c
  src/overlays/actors/ovl_Bg_Hidan_Kousi/z_bg_hidan_kousi.c
  src/overlays/actors/ovl_Bg_Hidan_Sekizou/z_bg_hidan_sekizou.c
  src/overlays/actors/ovl_Bg_Ice_Shutter/z_bg_ice_shutter.c
  src/overlays/actors/ovl_Bg_Jya_Bigmirror/z_bg_jya_bigmirror.c
  src/overlays/actors/ovl_Bg_Jya_Ironobj/z_bg_jya_ironobj.c
  src/overlays/actors/ovl_Bg_Jya_Megami/z_bg_jya_megami.c
  src/overlays/actors/ovl_Bg_Mizu_Bwall/z_bg_mizu_bwall.c
  src/overlays/actors/ovl_Bg_Mizu_Water/z_bg_mizu_water.c
  src/overlays/actors/ovl_Bg_Mori_Elevator/z_bg_mori_elevator.c
  src/overlays/actors/ovl_Bg_Mori_Rakkatenjo/z_bg_mori_rakkatenjo.c
  src/overlays/actors/ovl_Bg_Spot00_Hanebasi/z_bg_spot00_hanebasi.c
  src/overlays/actors/ovl_Bg_Spot01_Idohashira/z_bg_spot01_idohashira.c
  src/overlays/actors/ovl_Bg_Spot02_Objects/z_bg_spot02_objects.c
  src/overlays/actors/ovl_Bg_Spot03_Taki/z_bg_spot03_taki.c
  src/overlays/actors/ovl_Bg_Spot06_Objects/z_bg_spot06_objects.c
  src/overlays/actors/ovl_Bg_Spot11_Oasis/z_bg_spot11_oasis.c
  src/overlays/actors/ovl_Bg_Spot16_Bombstone/z_bg_spot16_bombstone.c
  src/overlays/actors/ovl_Bg_Spot18_Basket/z_bg_spot18_basket.c
  src/overlays/actors/ovl_Bg_Spot18_Obj/z_bg_spot18_obj.c
  src/overlays/actors/ovl_Bg_Ydan_Hasi/z_bg_ydan_hasi.c
  src/overlays/actors/ovl_Bg_Ydan_Sp/z_bg_ydan_sp.c
Labels: Needs second approval

#1747 Suggest explorer.exe in README.md
  README.md
Labels: Needs second approval

#1746 Fixup permuter_settings
  include/macros.h
  tools/permuter_settings.toml
Labels: Needs second approval

#1893 Match more of player for retail
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs second approval

#1890 Match En actors A-C, and a few more actors
  src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
  src/overlays/actors/ovl_Eff_Dust/z_eff_dust.c
  src/overlays/actors/ovl_Elf_Msg/z_elf_msg.c
  src/overlays/actors/ovl_Elf_Msg2/z_elf_msg2.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Arrow/z_en_arrow.c
  src/overlays/actors/ovl_En_Attack_Niw/z_en_attack_niw.c
  src/overlays/actors/ovl_En_Ba/z_en_ba.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bdfire/z_en_bdfire.c
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Bili/z_en_bili.c
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.c
  src/overlays/actors/ovl_En_Boom/z_en_boom.c
  src/overlays/actors/ovl_En_Bubble/z_en_bubble.c
  src/overlays/actors/ovl_En_Bw/z_en_bw.c
  src/overlays/actors/ovl_En_Bx/z_en_bx.c
  src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.c
  src/overlays/actors/ovl_En_Crow/z_en_crow.c
  tools/disasm/gc-eu-mq/functions.txt
Labels: Met Review Requirements

#1895 Finish retail player
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Needs second approval

#1825 Match retail En actors V-Z
  src/overlays/actors/ovl_En_Vali/z_en_vali.c
  src/overlays/actors/ovl_En_Vm/z_en_vm.c
  src/overlays/actors/ovl_En_Wallmas/z_en_wallmas.c
  src/overlays/actors/ovl_En_Weiyer/z_en_weiyer.c
  src/overlays/actors/ovl_En_Wf/z_en_wf.c
  src/overlays/actors/ovl_En_Xc/z_en_xc.c
  src/overlays/actors/ovl_En_Zf/z_en_zf.c
  src/overlays/actors/ovl_En_Zl2/z_en_zl2.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
Labels: Needs second approval

#1826 Match En actors O-T
  src/overlays/actors/ovl_En_Okuta/z_en_okuta.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Peehat/z_en_peehat.c
  src/overlays/actors/ovl_En_Po_Field/z_en_po_field.c
  src/overlays/actors/ovl_En_Po_Relay/z_en_po_relay.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_En_Rl/z_en_rl.c
  src/overlays/actors/ovl_En_Rr/z_en_rr.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Sa/z_en_sa.c
  src/overlays/actors/ovl_En_Siofuki/z_en_siofuki.c
  src/overlays/actors/ovl_En_Skb/z_en_skb.c
  src/overlays/actors/ovl_En_Skj/z_en_skj.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
  src/overlays/actors/ovl_En_Syateki_Niw/z_en_syateki_niw.c
  src/overlays/actors/ovl_En_Tana/z_en_tana.c
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_En_Tite/z_en_tite.c
  src/overlays/actors/ovl_En_Torch2/z_en_torch2.c
  src/overlays/actors/ovl_En_Tr/z_en_tr.c
  src/overlays/actors/ovl_En_Trap/z_en_trap.c
Labels: Needs second approval

#1889 Match En actors D-G
  src/overlays/actors/ovl_En_Dh/z_en_dh.c
  src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.c
  src/overlays/actors/ovl_En_Dns/z_en_dns.c
  src/overlays/actors/ovl_En_Dnt_Nomal/z_en_dnt_nomal.c
  src/overlays/actors/ovl_En_Du/z_en_du.c
  src/overlays/actors/ovl_En_Dy_Extra/z_en_dy_extra.c
  src/overlays/actors/ovl_En_Eg/z_en_eg.c
  src/overlays/actors/ovl_En_Eiyer/z_en_eiyer.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Encount2/z_en_encount2.c
  src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.c
  src/overlays/actors/ovl_En_Fd/z_en_fd.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Fish/z_en_fish.c
  src/overlays/actors/ovl_En_Fz/z_en_fz.c
  src/overlays/actors/ovl_En_Ganon_Mant/z_en_ganon_mant.c
  src/overlays/actors/ovl_En_Gb/z_en_gb.c
  src/overlays/actors/ovl_En_Ge2/z_en_ge2.c
  src/overlays/actors/ovl_En_GeldB/z_en_geldb.c
  src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  src/overlays/actors/ovl_En_Goma/z_en_goma.c
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.c
  src/overlays/actors/ovl_En_Gs/z_en_gs.c
  tools/disasm/gc-eu-mq/functions.txt
Labels: Needs second approval

#1894 Mostly match retail bosses, part 2
  src/overlays/actors/ovl_Boss_Ganondrof/z_boss_ganondrof.c
  src/overlays/actors/ovl_Boss_Goma/z_boss_goma.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_Boss_Va/z_boss_va.c
  tools/disasm/disasm.py
Labels: Needs second approval

#1892 RNG doc
  Makefile
  spec
  src/code/code_800FD970.c
  src/code/rand.c
  tools/disasm/gc-eu-mq/files_code.csv
Labels: Met Review Requirements

#1668 Fix some retail `boot` data
  src/boot/is_debug.c
  src/boot/stackcheck.c
Labels: Needs second approval

#1741 Match retail code data sizes
  data/fault_drawer.bss.s
  include/terminal.h
  include/variables.h
  src/audio/data.c
  src/audio/general.c
  src/audio/sfx.c
  src/code/fault_drawer.c
  src/code/game.c
  src/code/graph.c
  src/code/sched.c
  src/code/z_actor_dlftbls.c
  src/code/z_debug.c
  src/code/z_play.c
Labels: Needs second approval

#1897 Match retail z_en_ds.c, z_en_horse.c, z_en_fhg_fire.c
  src/overlays/actors/ovl_En_Ds/z_en_ds.c
  src/overlays/actors/ovl_En_Fhg_Fire/z_en_fhg_fire.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
Labels: Needs second approval

#1891 Filename & line number args cleanup
  include/fault.h
  include/functions.h
  include/z64.h
  include/z64dma.h
  src/boot/is_debug.c
  src/boot/logutils.c
  src/boot/z_std_dma.c
  src/code/__osMalloc.c
  src/code/debug_malloc.c
  src/code/fault.c
  src/code/game.c
  src/code/gamealloc.c
  src/code/graph.c
  src/code/sys_matrix.c
  src/code/system_malloc.c
  src/code/z_bgcheck.c
  src/code/z_malloc.c
Labels: Met Review Requirements

#1899 Restore terminal colors in retail, except in __osMalloc.c
  include/terminal.h
  src/code/__osMalloc.c
Labels: Met Review Requirements

#1900 Add proper bug comment for gSaveContext.save.dayTime getting cleared as s32 when it is u16
  src/code/z_sram.c
Labels: Met Review Requirements

#1901 Remove gSystemHeap and use _buffersSegmentEnd instead, make buffer alignments explicit for gcc
  .clang-format
  include/alignment.h
  include/ultra64/controller.h
  include/variables.h
  include/z64.h
  spec
  src/audio/lib/data.c
  src/boot/idle.c
  src/boot/yaz0.c
  src/buffers/audio_heap.c
  src/buffers/gfxbuffers.c
  src/buffers/heaps.c
  src/buffers/zbuffer.c
  src/code/main.c
  src/code/z_common_data.c
  tools/disasm/gc-eu-mq/variables.txt
Labels: Met Review Requirements

#1902 AVOID_UB for out-of-bounds access in AudioLoad_Init
  src/audio/lib/load.c
Labels: Met Review Requirements

#1903 Some GCC flags improvements
  Makefile
  include/ultra64/libc.h
  src/gcc_fix/missing_gcc_functions.c
Labels: Met Review Requirements
