Repository zeldaret/oot, pull requests merged in 2025-06, with the labels that each got.

#2561 csdis.py: write `CS_CMD_ACTOR_CUE_` names in actor cue list header
  tools/csdis.py
Labels: Needs second approval

#2569 Child Ruto Part 2: Rename resurfacing animation
  assets/xml/objects/object_ru1.xml
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
Labels: Approved

#2563 T() macro loose ends 1
  src/code/debug_malloc.c
  src/code/graph.c
  src/code/z_actor.c
  src/libc64/malloc.c
  src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.c
  src/overlays/actors/ovl_En_Fire_Rock/z_en_fire_rock.c
  src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  src/overlays/actors/ovl_En_Heishi1/z_en_heishi1.c
  src/overlays/actors/ovl_En_Heishi2/z_en_heishi2.c
  src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
  src/overlays/actors/ovl_En_Hs2/z_en_hs2.c
  src/overlays/actors/ovl_En_Kakasi2/z_en_kakasi2.c
  src/overlays/actors/ovl_En_Ru2/z_en_ru2.c
  src/overlays/actors/ovl_En_Takara_Man/z_en_takara_man.c
  src/overlays/actors/ovl_En_Zl2/z_en_zl2.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
Labels: One approval

#2576 Child Ruto Part 8: Init branches
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
Labels: Approved

#2565 Add Vtx[] resources in xmls for (partially) documented assets 2
  assets/xml/objects/gameplay_keep.xml
  assets/xml/objects/gameplay_keep_pal.xml
  assets/xml/objects/object_ahg.xml
  assets/xml/objects/object_bba.xml
  assets/xml/objects/object_bdoor.xml
  assets/xml/objects/object_bird.xml
  assets/xml/objects/object_bji.xml
  assets/xml/objects/object_bl.xml
  assets/xml/objects/object_bob.xml
  assets/xml/objects/object_boj.xml
  assets/xml/objects/object_bw.xml
  assets/xml/objects/object_cne.xml
  assets/xml/objects/object_cob.xml
  assets/xml/objects/object_dekubaba.xml
  assets/xml/objects/object_fish.xml
  assets/xml/objects/object_ganon.xml
  assets/xml/objects/object_ganon2.xml
  assets/xml/objects/object_ganon2_pal.xml
  assets/xml/objects/object_ganon_pal.xml
  assets/xml/objects/object_gndd.xml
  assets/xml/objects/object_haka_door.xml
  assets/xml/objects/object_human.xml
  assets/xml/objects/object_ice_objects.xml
  assets/xml/objects/object_jya_iron.xml
  assets/xml/objects/object_km1.xml
  assets/xml/objects/object_os.xml
  assets/xml/objects/object_po_composer.xml
  assets/xml/objects/object_po_field.xml
  assets/xml/objects/object_po_sisters.xml
  assets/xml/objects/object_poh.xml
  assets/xml/objects/object_ps.xml
  assets/xml/objects/object_rd.xml
  assets/xml/objects/object_st.xml
  assets/xml/objects/object_tk.xml
  assets/xml/objects/object_tp.xml
  assets/xml/objects/object_vali.xml
  assets/xml/objects/object_warp1.xml
  src/code/z_kankyo.c
Labels: One approval, Merge soon

#2566 Add Vtx[] resources in xmls for (partially) documented assets 3
  assets/xml/objects/object_am.xml
  assets/xml/objects/object_ane.xml
  assets/xml/objects/object_ani.xml
  assets/xml/objects/object_anubice.xml
  assets/xml/objects/object_aob.xml
  assets/xml/objects/object_bdan_objects.xml
  assets/xml/objects/object_bg.xml
  assets/xml/objects/object_blkobj.xml
  assets/xml/objects/object_bowl.xml
  assets/xml/objects/object_box.xml
  assets/xml/objects/object_cow.xml
  assets/xml/objects/object_crow.xml
  assets/xml/objects/object_cs.xml
  assets/xml/objects/object_d_hsblock.xml
  assets/xml/objects/object_ddan_objects.xml
  assets/xml/objects/object_dekunuts.xml
Labels: One approval, Merge soon

#2578 Child Ruto Part 10: Head rotation
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.h
Labels: Approved, Merge soon

#2579 Child Ruto Part 11: Idle Carry Timer
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.h
Labels: Approved, Merge soon

#2577 Child Ruto Part 9: Camera setting
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.h
Labels: Approved

#2570 Child Ruto Part 3: Water states
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.h
Labels: Approved, Merge soon

#2592 T() macro loose ends 3
  src/boot/z_std_dma.c
  src/overlays/actors/ovl_Bg_Bdan_Switch/z_bg_bdan_switch.c
  src/overlays/actors/ovl_Bg_Bom_Guard/z_bg_bom_guard.c
  src/overlays/actors/ovl_Bg_Bombwall/z_bg_bombwall.c
  src/overlays/actors/ovl_Bg_Bowl_Wall/z_bg_bowl_wall.c
  src/overlays/actors/ovl_Bg_Dy_Yoseizo/z_bg_dy_yoseizo.c
  src/overlays/actors/ovl_Bg_Gate_Shutter/z_bg_gate_shutter.c
  src/overlays/actors/ovl_Bg_Hidan_Curtain/z_bg_hidan_curtain.c
  src/overlays/actors/ovl_Bg_Hidan_Kowarerukabe/z_bg_hidan_kowarerukabe.c
  src/overlays/actors/ovl_Bg_Ice_Shelter/z_bg_ice_shelter.c
  src/overlays/actors/ovl_Bg_Jya_1flift/z_bg_jya_1flift.c
  src/overlays/actors/ovl_Bg_Jya_Amishutter/z_bg_jya_amishutter.c
  src/overlays/actors/ovl_Bg_Jya_Bigmirror/z_bg_jya_bigmirror.c
  src/overlays/actors/ovl_Bg_Jya_Bombchuiwa/z_bg_jya_bombchuiwa.c
  src/overlays/actors/ovl_Bg_Jya_Bombiwa/z_bg_jya_bombiwa.c
  src/overlays/actors/ovl_Bg_Jya_Cobra/z_bg_jya_cobra.c
  src/overlays/actors/ovl_Bg_Jya_Kanaami/z_bg_jya_kanaami.c
  src/overlays/actors/ovl_Bg_Jya_Zurerukabe/z_bg_jya_zurerukabe.c
  src/overlays/actors/ovl_Bg_Mizu_Bwall/z_bg_mizu_bwall.c
  src/overlays/actors/ovl_Bg_Mizu_Water/z_bg_mizu_water.c
  src/overlays/actors/ovl_Bg_Mori_Bigst/z_bg_mori_bigst.c
  src/overlays/actors/ovl_Bg_Mori_Hashigo/z_bg_mori_hashigo.c
  src/overlays/actors/ovl_Bg_Mori_Hashira4/z_bg_mori_hashira4.c
  src/overlays/actors/ovl_Bg_Mori_Idomizu/z_bg_mori_idomizu.c
  src/overlays/actors/ovl_Bg_Mori_Rakkatenjo/z_bg_mori_rakkatenjo.c
  src/overlays/actors/ovl_Bg_Spot08_Iceblock/z_bg_spot08_iceblock.c
  src/overlays/actors/ovl_Bg_Spot09_Obj/z_bg_spot09_obj.c
  src/overlays/actors/ovl_Bg_Spot11_Bakudankabe/z_bg_spot11_bakudankabe.c
  src/overlays/actors/ovl_Bg_Spot12_Gate/z_bg_spot12_gate.c
  src/overlays/actors/ovl_Bg_Spot12_Saku/z_bg_spot12_saku.c
  src/overlays/actors/ovl_Bg_Spot15_Rrbox/z_bg_spot15_rrbox.c
  src/overlays/actors/ovl_Bg_Spot16_Bombstone/z_bg_spot16_bombstone.c
  src/overlays/actors/ovl_Bg_Spot16_Doughnut/z_bg_spot16_doughnut.c
  src/overlays/actors/ovl_Bg_Spot17_Funen/z_bg_spot17_funen.c
  src/overlays/actors/ovl_Bg_Spot18_Basket/z_bg_spot18_basket.c
  src/overlays/actors/ovl_Bg_Spot18_Obj/z_bg_spot18_obj.c
  src/overlays/actors/ovl_En_Anubice/z_en_anubice.c
  src/overlays/actors/ovl_En_Anubice_Tag/z_en_anubice_tag.c
  src/overlays/actors/ovl_En_Changer/z_en_changer.c
  src/overlays/actors/ovl_En_Dnt_Demo/z_en_dnt_demo.c
  src/overlays/actors/ovl_En_Encount2/z_en_encount2.c
  src/overlays/actors/ovl_En_Heishi1/z_en_heishi1.c
  src/overlays/actors/ovl_En_Kakasi3/z_en_kakasi3.c
  src/overlays/actors/ovl_En_Niw/z_en_niw.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
  src/overlays/actors/ovl_En_Tite/z_en_tite.c
  src/overlays/actors/ovl_En_Wf/z_en_wf.c
  src/overlays/actors/ovl_Mir_Ray/z_mir_ray.c
  src/overlays/actors/ovl_Obj_Bean/z_obj_bean.c
  src/overlays/actors/ovl_Obj_Elevator/z_obj_elevator.c
  src/overlays/actors/ovl_Obj_Hsblock/z_obj_hsblock.c
  src/overlays/actors/ovl_Obj_Lift/z_obj_lift.c
  src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
  src/overlays/actors/ovl_Obj_Makeoshihiki/z_obj_makeoshihiki.c
  src/overlays/actors/ovl_Obj_Mure/z_obj_mure.c
  src/overlays/actors/ovl_Obj_Oshihiki/z_obj_oshihiki.c
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.c
  src/overlays/actors/ovl_Shot_Sun/z_shot_sun.c
Labels: Approved, Merge soon

#2572 Child Ruto Part 5: Colliders
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.h
Labels: Approved, Merge soon

#2588 Add Vtx[] resources in xmls for (partially) documented assets 6
  assets/xml/objects/object_peehat.xml
  assets/xml/objects/object_relay_objects.xml
  assets/xml/objects/object_ru1.xml
  assets/xml/objects/object_ru2.xml
  assets/xml/objects/object_sa.xml
  assets/xml/objects/object_sd.xml
  assets/xml/objects/object_shopnuts.xml
  assets/xml/objects/object_sk2.xml
  assets/xml/objects/object_skb.xml
  assets/xml/objects/object_skj.xml
  assets/xml/objects/object_spot00_break.xml
  assets/xml/objects/object_spot00_objects.xml
  assets/xml/objects/object_spot01_matoya.xml
  assets/xml/objects/object_spot04_objects.xml
  assets/xml/objects/object_ta.xml
  assets/xml/objects/object_vm.xml
  assets/xml/objects/object_zl1.xml
  assets/xml/objects/object_zo.xml
Labels: One approval

#2587 Add Vtx[] resources in xmls for (partially) documented assets 5
  assets/xml/objects/object_demo_kekkai.xml
  assets/xml/objects/object_gj.xml
  assets/xml/objects/object_goroiwa.xml
  assets/xml/objects/object_gt.xml
  assets/xml/objects/object_haka.xml
  assets/xml/objects/object_hakach_objects.xml
  assets/xml/objects/object_hata.xml
  assets/xml/objects/object_heavy_object.xml
  assets/xml/objects/object_hidan_objects.xml
  assets/xml/objects/object_im.xml
  assets/xml/objects/object_in.xml
  assets/xml/objects/object_jj.xml
  assets/xml/objects/object_js.xml
  assets/xml/objects/object_kibako2.xml
  assets/xml/objects/object_ma1.xml
  assets/xml/objects/object_ma2.xml
  assets/xml/objects/object_mamenoki.xml
  assets/xml/objects/object_masterkokirihead.xml
  assets/xml/objects/object_md.xml
  assets/xml/objects/object_menkuri_objects.xml
  assets/xml/objects/object_mir_ray.xml
  assets/xml/objects/object_mori_objects.xml
  assets/xml/objects/object_ms.xml
  assets/xml/objects/object_nb.xml
  assets/xml/objects/object_niw.xml
  assets/xml/objects/object_nwc.xml
Labels: One approval

#2590 Better automatic names for Limbs and JointKeys, and implement more get_as_xml
  tools/assets/extract/extase/__init__.py
  tools/assets/extract/extase_oot64/dlist_resources.py
  tools/assets/extract/extase_oot64/skelanime_legacy_resources.py
  tools/assets/extract/extase_oot64/skeleton_resources.py
Labels: One approval

#2591 [assets] Fix too long filenames for windows/wsl
  tools/assets/extract/extase_oot64/dlist_resources.py
Labels: One approval

#2594 Add various undocumented resources in xmls 2
  assets/xml/objects/gameplay_field_keep.xml
  assets/xml/objects/object_am.xml
  assets/xml/objects/object_ani.xml
  assets/xml/objects/object_anubice.xml
  assets/xml/objects/object_bdan_objects.xml
  assets/xml/objects/object_blkobj.xml
  assets/xml/objects/object_crow.xml
  assets/xml/objects/object_ddan_objects.xml
  assets/xml/objects/object_dekunuts.xml
  assets/xml/objects/object_demo_kekkai.xml
  assets/xml/objects/object_dnk.xml
  assets/xml/objects/object_dns.xml
  assets/xml/objects/object_dodongo.xml
  assets/xml/objects/object_fd2.xml
  assets/xml/objects/object_firefly.xml
  assets/xml/objects/object_fw.xml
  assets/xml/objects/object_geldb.xml
  assets/xml/objects/object_gj.xml
  assets/xml/objects/object_gnd.xml
  assets/xml/objects/object_gr.xml
  assets/xml/objects/object_hakach_objects.xml
  assets/xml/objects/object_hidan_objects.xml
Labels: One approval

#2595 Add various undocumented resources in xmls 3
  assets/xml/objects/object_hintnuts.xml
  assets/xml/objects/object_ik.xml
  assets/xml/objects/object_jj.xml
  assets/xml/objects/object_jya_obj.xml
  assets/xml/objects/object_masterkokirihead.xml
  assets/xml/objects/object_mb.xml
  assets/xml/objects/object_mizu_objects.xml
  assets/xml/objects/object_mm.xml
  assets/xml/objects/object_oF1d_map.xml
  assets/xml/objects/object_okuta.xml
  assets/xml/objects/object_owl.xml
  assets/xml/objects/object_ru2.xml
  assets/xml/objects/object_sa.xml
  assets/xml/objects/object_skj.xml
  assets/xml/objects/object_spot01_matoya.xml
  assets/xml/objects/object_spot01_matoyab.xml
  assets/xml/objects/object_spot09_obj.xml
  assets/xml/objects/object_torch2.xml
  assets/xml/objects/object_wallmaster.xml
  assets/xml/objects/object_ydan_objects.xml
  assets/xml/objects/object_zl1.xml
  assets/xml/objects/object_zl2.xml
  assets/xml/objects/object_zl4.xml
Labels: One approval

#2494 Add additional Bazaar display list definitions
  assets/xml/scenes/shops/shop1.xml
Labels: One approval

#2593 Doc Actor: En_Ma2 (Adult Malon)
  include/save.h
  src/overlays/actors/ovl_En_Ma2/z_en_ma2.c
  src/overlays/actors/ovl_En_Ma2/z_en_ma2.h
Labels: One approval, Merge soon

#1265 Update docs/Documenting.md
  docs/Documenting.md
  src/code/z_actor.c
  src/code/z_camera.c
Labels: One approval

#2597 Commit `do_action_static`
  assets/textures/do_action_static/do_action_static.c
  assets/textures/do_action_static/do_action_static.h
  include/interface.h
  src/code/z_construct.c
  tools/assets/extract/write_source.txt
Labels: One approval

#1922 Document fog functions Gfx_SetFog(2) and Play_SetFog
  src/code/z_play.c
  src/code/z_rcp.c
Labels: wait, Approved

#1596 `WeaponInfo` docs
  include/player.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.h
  src/overlays/actors/ovl_Bg_Ydan_Sp/z_bg_ydan_sp.c
  src/overlays/actors/ovl_En_Arrow/z_en_arrow.c
  src/overlays/actors/ovl_En_Boom/z_en_boom.c
  src/overlays/actors/ovl_En_Boom/z_en_boom.h
  src/overlays/actors/ovl_En_Butte/z_en_butte.c
  src/overlays/actors/ovl_En_Mb/z_en_mb.c
  src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Approved

#2603 Child Ruto Actions: Enums
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.h
Labels: One approval

#2611 Commit `object_ganon_anime3`
  assets/objects/object_ganon_anime3/gGanonRoarAnim.c
  assets/objects/object_ganon_anime3/gGanonUncurlAndFlailAnim.c
  assets/objects/object_ganon_anime3/gGanondorfBurstOutAnim.c
  assets/objects/object_ganon_anime3/gGanondorfFloatingHeavyBreathingAnim.c
  assets/objects/object_ganon_anime3/gGanondorfShowTriforceLoopAnim.c
  assets/objects/object_ganon_anime3/gGanondorfShowTriforceStartAnim.c
  assets/objects/object_ganon_anime3/gGanondorfTransformEndAnim.c
  assets/objects/object_ganon_anime3/gGanondorfTransformLoopAnim.c
  assets/objects/object_ganon_anime3/gGanondorfTransformStartAnim.c
  assets/objects/object_ganon_anime3/object_ganon_anime3.h
  spec/spec
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  tools/assets/extract/write_source.txt
Labels: Approved, Merge soon

#2616 Remove `Static` from xmls
  assets/xml/objects/object_link_boy.xml
  assets/xml/objects/object_link_child.xml
  assets/xml/overlays/ovl_Arrow_Fire.xml
  assets/xml/overlays/ovl_Arrow_Ice.xml
  assets/xml/overlays/ovl_Arrow_Light.xml
  assets/xml/overlays/ovl_Boss_Ganon.xml
  assets/xml/overlays/ovl_Boss_Ganon2.xml
  assets/xml/overlays/ovl_file_choose.xml
  assets/xml/overlays/ovl_file_choose_pal_gc.xml
  assets/xml/overlays/ovl_file_choose_pal_n64.xml
Labels: One approval

#2608 Introduce `CAM_DATA_SET_`, `CAM_ITEM_TYPE_` and name `Player_SetTurnAroundCamera`, `Player_RequestCameraSetting`
  include/camera.h
  src/code/game.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_onepointdemo.c
  src/overlays/actors/ovl_Bg_Mori_Rakkatenjo/z_bg_mori_rakkatenjo.c
  src/overlays/actors/ovl_Boss_Sst/z_boss_sst.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: One approval

#2625 Assets: Move limb enums into xmls 1
  assets/xml/objects/object_anubice.xml
  assets/xml/objects/object_bl.xml
  assets/xml/objects/object_bw.xml
  assets/xml/objects/object_gndd.xml
  assets/xml/objects/object_im.xml
  src/overlays/actors/ovl_Demo_Im/z_demo_im.h
  src/overlays/actors/ovl_En_Anubice/z_en_anubice.h
  src/overlays/actors/ovl_En_Bili/z_en_bili.c
  src/overlays/actors/ovl_En_Bili/z_en_bili.h
  src/overlays/actors/ovl_En_Bw/z_en_bw.h
  src/overlays/actors/ovl_En_Viewer/z_en_viewer.h
Labels: One approval

#2626 Assets: Move limb enums into xmls 2
  assets/xml/objects/object_fu.xml
  assets/xml/objects/object_ge1.xml
  assets/xml/objects/object_geldb.xml
  assets/xml/objects/object_hata.xml
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.h
  src/overlays/actors/ovl_En_Ge1/z_en_ge1.c
  src/overlays/actors/ovl_En_Ge1/z_en_ge1.h
  src/overlays/actors/ovl_En_Ge3/z_en_ge3.c
  src/overlays/actors/ovl_En_Ge3/z_en_ge3.h
  src/overlays/actors/ovl_En_GeldB/z_en_geldb.c
  src/overlays/actors/ovl_En_GeldB/z_en_geldb.h
  src/overlays/actors/ovl_En_Hata/z_en_hata.h
Labels: One approval

#2627 `Camera_KeepOn4` docs 1
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
Labels: One approval

#2629 Name most `object_gi_*` textures
  assets/xml/objects/object_gi_boots_2.xml
  assets/xml/objects/object_gi_butterfly.xml
  assets/xml/objects/object_gi_clothes.xml
  assets/xml/objects/object_gi_dekupouch.xml
  assets/xml/objects/object_gi_fire.xml
  assets/xml/objects/object_gi_frog.xml
  assets/xml/objects/object_gi_gerudo.xml
  assets/xml/objects/object_gi_gerudomask.xml
  assets/xml/objects/object_gi_ghost.xml
  assets/xml/objects/object_gi_gloves.xml
  assets/xml/objects/object_gi_golonmask.xml
  assets/xml/objects/object_gi_hoverboots.xml
  assets/xml/objects/object_gi_ki_tan_mask.xml
  assets/xml/objects/object_gi_letter.xml
  assets/xml/objects/object_gi_liquid.xml
  assets/xml/objects/object_gi_milk.xml
  assets/xml/objects/object_gi_niwatori.xml
  assets/xml/objects/object_gi_ocarina.xml
  assets/xml/objects/object_gi_ocarina_0.xml
  assets/xml/objects/object_gi_prescription.xml
  assets/xml/objects/object_gi_rabit_mask.xml
  assets/xml/objects/object_gi_shield_3.xml
  assets/xml/objects/object_gi_soldout.xml
  assets/xml/objects/object_gi_soul.xml
  assets/xml/objects/object_gi_ticketstone.xml
  assets/xml/objects/object_gi_truth_mask.xml
  assets/xml/objects/object_gi_zoramask.xml
Labels: One approval

#2636 Pause docs: misc docs
  src/code/z_construct.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: One approval

#2555 Rename `acDmgInfo.effect` -> `hitBacklash`
  include/collision_check.h
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_kaleido_scope_call.c
  src/code/z_message.c
  src/code/z_play.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_En_Bili/z_en_bili.c
  src/overlays/actors/ovl_En_Vali/z_en_vali.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: One approval

#2637 Rename AT `effect` to `hitSpecialEffect`
  include/collision_check.h
  src/code/z_actor.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_message.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.c
  src/overlays/actors/ovl_Boss_Mo/z_boss_mo.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bubble/z_en_bubble.c
  src/overlays/actors/ovl_En_Bw/z_en_bw.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Reeba/z_en_reeba.c
  src/overlays/actors/ovl_En_Torch2/z_en_torch2.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: One approval

#2639 Name `HIT_BACKLASH_` and `HIT_SPECIAL_EFFECT_` values
  include/collision_check.h
  src/code/z_collision_check.c
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bili/z_en_bili.c
  src/overlays/actors/ovl_En_Bubble/z_en_bubble.c
  src/overlays/actors/ovl_En_Bw/z_en_bw.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Reeba/z_en_reeba.c
  src/overlays/actors/ovl_En_Vali/z_en_vali.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: One approval

#2634 Commit objects 1: `tp`, `triforce_spot`, `umajump`, `vase`, `yukabyun`, `zg`
  assets/objects/object_tp/object_tp.c
  assets/objects/object_tp/object_tp.h
  assets/objects/object_triforce_spot/object_triforce_spot.c
  assets/objects/object_triforce_spot/object_triforce_spot.h
  assets/objects/object_umajump/gJumpableHorseFenceCol.c
  assets/objects/object_umajump/gJumpableHorseFenceDL.c
  assets/objects/object_umajump/object_umajump.h
  assets/objects/object_vase/gUnusedVaseDL.c
  assets/objects/object_vase/object_vase.h
  assets/objects/object_yukabyun/gFloorTileEnemyDL.c
  assets/objects/object_yukabyun/gFloorTileEnemyFragmentDL.c
  assets/objects/object_yukabyun/object_yukabyun.h
  assets/objects/object_zg/gTowerCollapseBarsCol.c
  assets/objects/object_zg/gTowerCollapseBarsDL.c
  assets/objects/object_zg/object_zg.h
  spec/spec
  tools/assets/extract/write_source.txt
Labels: One approval

#2632 `Camera_KeepOn4` docs 2: RO and RW data
  include/camera.h
  src/code/z_camera.c
  src/code/z_camera_data.inc.c
Labels: One approval

#2640 Reevaluate player hit response names
  include/player.h
  src/overlays/actors/ovl_En_Fhg_Fire/z_en_fhg_fire.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: One approval

#2642 Fixup docker
  docker-compose.yml
  docs/BUILDING_DOCKER.md
Labels: One approval

#2644 Pause docs: UIOverlay quads dimensions
  assets/textures/icon_item_static/icon_item_static.c
  assets/textures/icon_item_static/icon_item_static.h
  include/regs.h
  src/code/z_construct.c
  src/code/z_kaleido_setup.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: One approval

#2600 Child Ruto Actions Part 1: Zora's Fountain
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.c
  src/overlays/actors/ovl_En_Ru1/z_en_ru1.h
Labels: One approval
