Repository zeldaret/oot, pull requests merged in 2025-01, with the labels that each got.

#2394 [iQue] Match remaining IDO files
  Makefile
  src/boot/driverominit.c
  src/code/z_skelanime.c
  tools/disasm/ique-cn/files_boot.csv
  tools/patch_ique_driverominit.py
Labels: Needs second approval

#2411 [iQue] Match remaining libultra/io files
  include/ultra64/controller.h
  include/variables.h
  spec
  src/boot/z_std_dma.c
  src/code/main.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_kankyo.c
  src/libultra/io/contquery.c
  src/libultra/io/contramread.c
  src/libultra/io/contramwrite.c
  src/libultra/io/contreaddata.c
  src/libultra/io/controller.c
  src/libultra/io/pfsgetstatus.c
  src/libultra/io/pfsisplug.c
  src/libultra/io/sirawdma.c
  src/libultra/io/sptaskyielded.c
  src/overlays/actors/ovl_En_Po_Field/z_en_po_field.c
Labels: Met Review Requirements

#2413 [iQue] Match handwritten asm files in libultra/os, match C replacements of osGetCount and __osSetCompare
  Makefile
  include/ultra64/asm.h
  src/libultra/os/invaldcache.s
  src/libultra/os/invalicache.s
  src/libultra/os/setintmask.s
  src/libultra/os/writebackdcache.s
  src/libultra/reg/_getcount.c
  src/libultra/reg/_setcompare.c
  tools/disasm/ique-cn/files_boot.csv
Labels: Met Review Requirements

#2410 Only build .o files listed in the spec
  Makefile
  src/code/db_camera.c
  src/code/fault_gc.c
  src/code/fault_gc_drawer.c
  src/code/fault_n64.c
  src/libc64/__osMalloc_gc.c
  src/libc64/__osMalloc_n64.c
  src/n64dd/n64dd_error_textures.c
Labels: Met Review Requirements

#2416 [iQue] Match gzip/zlib decompression
  Makefile
  include/functions.h
  spec
  src/boot/inflate.c
  src/boot/z_std_dma.c
  tools/disasm/ique-cn/files_boot.csv
  tools/disasm/ique-cn/functions.txt
Labels: Met Review Requirements

#2417 [iQue] Match remaining src/boot files
  Makefile
  include/functions.h
  include/line_numbers.h
  spec
  src/boot/is_debug_ique.c
  src/boot/z_locale.c
  src/boot/z_std_dma.c
  src/code/graph.c
  src/code/padmgr.c
  src/code/sys_cfb.c
  src/code/z_play.c
  tools/disasm/ique-cn/files_boot.csv
  undefined_syms.txt
Labels: Met Review Requirements

#2419 Fix circular Makefile dependency with assets/text/*.o
  Makefile
Labels: Met Review Requirements

#2402 [iQue] Match libultra/gu
  src/libultra/gu/rotate.c
  src/libultra/gu/sqrtf.c
  src/libultra/gu/sqrtf.s
  src/libultra/gu/us2dex.c
Labels: Met Review Requirements

#2412 [iQue] Match libgcc
  .clang-tidy
  spec
  src/libgcc/__cmpdi2.c
  src/libgcc/__cmpdi2.s
  src/libgcc/__divdi3.c
  src/libgcc/__divdi3.s
  src/libgcc/__fixdfdi.c
  src/libgcc/__fixdfdi.s
  src/libgcc/__fixsfdi.c
  src/libgcc/__fixsfdi.s
  src/libgcc/__fixunsdfdi.c
  src/libgcc/__fixunsdfdi.s
  src/libgcc/__fixunssfdi.c
  src/libgcc/__fixunssfdi.s
  src/libgcc/__floatdidf.c
  src/libgcc/__floatdidf.s
  src/libgcc/__floatdisf.c
  src/libgcc/__floatdisf.s
  src/libgcc/__moddi3.c
  src/libgcc/__moddi3.s
  src/libgcc/__udivdi3.c
  src/libgcc/__udivdi3.s
  src/libgcc/__umoddi3.c
  src/libgcc/__umoddi3.s
  src/libgcc/libgcc2.inc.c
  src/libgcc/longlong.h
  undefined_syms.txt
Labels: Met Review Requirements

#2415 [iQue] Update permuter/decompme import
  Makefile
  tools/permuter_settings.toml
Labels: Needs second approval

#2414 [iQue] Match remaining libultra/os files
  Makefile
  include/ultra64/bcp.h
  include/variables.h
  src/boot/z_std_dma.c
  src/code/fault_gc.c
  src/code/main.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_common_data.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/libultra/os/getmemsize.c
  src/libultra/os/gettime.c
  src/libultra/os/initialize.c
  src/libultra/os/recvmesg.c
  src/libultra/os/settimer.c
  src/libultra/os/stopthread.c
  src/libultra/os/thread.c
  src/libultra/os/timerintr.c
  src/libultra/os/virtualtophysical.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Met Review Requirements

#2408 [iQue] Match PI-related files in libultra/io
  include/ultra64/bcp.h
  src/libultra/io/devmgr.c
  src/libultra/io/epirawdma.c
  src/libultra/io/pimgr.c
Labels: Met Review Requirements

#2399 [iQue] Use CPP includes in spec and update for iQue
  Makefile
  include/libc64/os_malloc.h
  spec
  spec_includes/boot_libultra_gc.inc
  spec_includes/boot_libultra_ique.inc
  spec_includes/boot_libultra_n64.inc
  spec_includes/code_libultra_gc.inc
  spec_includes/code_libultra_ique.inc
  spec_includes/code_libultra_n64.inc
  spec_includes/overlays_gc.inc
  spec_includes/overlays_n64_ique.inc
  spec_includes/scenes_gc_ique.inc
  spec_includes/scenes_n64.inc
  src/boot/zlib.c
  src/libultra/bb/sa/common.c
  src/libultra/io/motor.c
  src/libultra/os/parameters.s
Labels: Needs second approval

#2420 Descriptions for Gohma Larva vs Boss Gohma
  src/overlays/actors/ovl_Boss_Goma/z_boss_goma.c
  src/overlays/actors/ovl_En_Goma/z_en_goma.c
Labels: Met Review Requirements, wait

#2423 [iQue] Define EGCS macro instead of relying on `__GNUC__`
  Makefile
  include/libc/stdarg.h
  include/macros.h
  src/audio/general.c
  src/code/sched.c
  src/code/z_actor.c
  src/libgcc/longlong.h
Labels: Needs second approval

#2421 [iQue] Match ovl_kaleido_scope
  Makefile
  include/z64save.h
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
  tools/disasm/ique-cn/files_ovl_kaleido_scope.csv
Labels: Met Review Requirements

#2426 [iQue] Match z_sram
  Makefile
  include/z64save.h
  include/z64sram.h
  src/boot/z_std_dma.c
  src/code/main.c
  src/code/z_camera.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kankyo.c
  src/code/z_sram.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  tools/disasm/ique-cn/functions.txt
Labels: Needs second approval

#2395 Restructure event flags in z64save.h (4/?): Haggling Townsfolk
  include/z64save.h
  src/overlays/actors/ovl_En_Mu/z_en_mu.c
Labels: Met Review Requirements

#2428 [iQue] Match z_kanfont
  Makefile
  include/functions.h
  include/message_data_static.h
  src/code/z_kanfont.c
  tools/disasm/ique-cn/functions.txt
Labels: Needs second approval

#2427 [iQue] Don't use -funsigned-char for z_std_dma
  Makefile
  src/boot/z_std_dma.c
Labels: Needs second approval

#2431 [iQue] Match z_actor
  Makefile
  include/z64actor.h
  include/z64play.h
  src/code/z_actor.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/overlays/gamestates/ovl_title/z_title.c
Labels: Met Review Requirements

#2432 Write about IDO and EGCS in compilers.md
  docs/compilers.md
  src/code/z_actor.c
  src/code/z_kanfont.c
  src/code/z_sram.c
Labels: Met Review Requirements

#2434 format.py: Allow empty files
  format.py
Labels: Met Review Requirements

#2435 [iQue] Match z_message
  Makefile
  include/z64interface.h
  include/z64message.h
  include/z64save.h
  src/code/z_message.c
Labels: Met Review Requirements

#2438 Reduce overlay dependencies on global.h (1)
  include/speed_meter.h
  include/z64.h
  src/code/z_env_flags.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.h
  src/overlays/actors/ovl_Arrow_Fire/z_arrow_fire.c
  src/overlays/actors/ovl_Arrow_Fire/z_arrow_fire.h
  src/overlays/actors/ovl_Arrow_Ice/z_arrow_ice.c
  src/overlays/actors/ovl_Arrow_Ice/z_arrow_ice.h
  src/overlays/actors/ovl_Arrow_Light/z_arrow_light.c
  src/overlays/actors/ovl_Arrow_Light/z_arrow_light.h
  src/overlays/actors/ovl_Bg_Bdan_Objects/z_bg_bdan_objects.c
  src/overlays/actors/ovl_Bg_Bdan_Objects/z_bg_bdan_objects.h
  src/overlays/actors/ovl_Bg_Bdan_Switch/z_bg_bdan_switch.c
  src/overlays/actors/ovl_Bg_Bdan_Switch/z_bg_bdan_switch.h
  src/overlays/actors/ovl_Bg_Bom_Guard/z_bg_bom_guard.c
  src/overlays/actors/ovl_Bg_Bom_Guard/z_bg_bom_guard.h
  src/overlays/actors/ovl_Bg_Bowl_Wall/z_bg_bowl_wall.c
  src/overlays/actors/ovl_Bg_Bowl_Wall/z_bg_bowl_wall.h
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.h
  src/overlays/actors/ovl_En_Bom_Bowl_Man/z_en_bom_bowl_man.c
  src/overlays/actors/ovl_En_Bom_Bowl_Man/z_en_bom_bowl_man.h
  src/overlays/actors/ovl_En_Bom_Bowl_Pit/z_en_bom_bowl_pit.c
  src/overlays/actors/ovl_En_Bom_Bowl_Pit/z_en_bom_bowl_pit.h
  src/overlays/actors/ovl_En_Bom_Chu/z_en_bom_chu.c
  src/overlays/actors/ovl_En_Bom_Chu/z_en_bom_chu.h
  src/overlays/actors/ovl_En_Ex_Item/z_en_ex_item.c
  src/overlays/actors/ovl_En_Ex_Item/z_en_ex_item.h
  src/overlays/actors/ovl_En_Syateki_Niw/z_en_syateki_niw.c
  src/overlays/actors/ovl_En_Syateki_Niw/z_en_syateki_niw.h
  src/overlays/actors/ovl_En_Wall_Tubo/z_en_wall_tubo.c
  src/overlays/actors/ovl_En_Wall_Tubo/z_en_wall_tubo.h
  src/overlays/effects/ovl_Effect_Ss_Dead_Sound/z_eff_ss_dead_sound.c
  src/overlays/effects/ovl_Effect_Ss_Dead_Sound/z_eff_ss_dead_sound.h
  src/overlays/effects/ovl_Effect_Ss_Hahen/z_eff_ss_hahen.c
  src/overlays/effects/ovl_Effect_Ss_Hahen/z_eff_ss_hahen.h
  src/overlays/misc/ovl_map_mark_data/z_map_mark_data.c
  src/overlays/misc/ovl_map_mark_data/z_map_mark_data_mq.c
Labels: Needs second approval

#2436 [iQue] Unify file select actionButtonAlpha and confirmButtonAlpha
  include/z64.h
  src/overlays/gamestates/ovl_file_choose/file_select.h
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_copy_erase.c
Labels: Needs second approval

#2439 [iQue] Match z_en_mag
  assets/xml/objects/object_mag_ique.xml
  assets/xml/overlays/ovl_En_Mag_ique.xml
  baseroms/ique-cn/config.yml
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
Labels: Needs second approval

#2443 Split z64debug_display.h, z64draw.h, z_en_item00.h
  include/functions.h
  include/z64.h
  include/z64actor.h
  include/z64debug_display.h
  include/z64draw.h
  include/z_en_item00.h
  src/boot/z_std_dma.c
  src/code/main.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_debug_display.c
  src/code/z_draw.c
  src/code/z_en_item00.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kankyo.c
  src/code/z_play.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_En_Ex_Item/z_en_ex_item.c
  src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  src/overlays/actors/ovl_En_Si/z_en_si.c
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_Item_Etcetera/z_item_etcetera.c
  src/overlays/actors/ovl_Item_Inbox/z_item_inbox.c
  src/overlays/actors/ovl_Item_Ocarina/z_item_ocarina.c
Labels: Met Review Requirements

#2446 [iQue] Fix audio library pad_text
  spec
Labels: Needs second approval

#2445 [iQue] Match z_fishing
  include/z64player.h
  src/overlays/actors/ovl_Fishing/z_fishing.c
  src/overlays/actors/ovl_Fishing/z_fishing.h
Labels: Met Review Requirements

#2422 spec_includes/ -> spec/, spec -> spec/spec
  Makefile
  spec/boot_libultra_gc.inc
  spec/boot_libultra_ique.inc
  spec/boot_libultra_n64.inc
  spec/code_libultra_gc.inc
  spec/code_libultra_ique.inc
  spec/code_libultra_n64.inc
  spec/overlays_gc.inc
  spec/overlays_n64_ique.inc
  spec/scenes_gc_ique.inc
  spec/scenes_n64.inc
  spec/spec
Labels: Met Review Requirements

#2447 [iQue] Match z_file_copy_erase
  Makefile
  baseroms/ique-cn/config.yml
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
  src/overlays/gamestates/ovl_file_choose/z_file_copy_erase.c
  tools/disasm/ique-cn/files_ovl_file_choose.csv
Labels: Met Review Requirements
