Repository zeldaret/oot, pull requests merged in 2025-05, with the labels that each got.

#2520 Restructure audio source files
  Makefile
  spec/spec
  src/audio/game/data.c
  src/audio/game/debug.inc.c
  src/audio/game/general.c
  src/audio/game/sequence.c
  src/audio/game/session_config.c
  src/audio/game/session_init.c
  src/audio/game/sfx.c
  src/audio/game/sfx_params.c
  src/audio/internal/aisetnextbuf.c
  src/audio/internal/data.c
  src/audio/internal/dcache.c
  src/audio/internal/effects.c
  src/audio/internal/heap.c
  src/audio/internal/load.c
  src/audio/internal/playback.c
  src/audio/internal/seqplayer.c
  src/audio/internal/synthesis.c
  src/audio/internal/thread.c
Labels: Needs first approval, Needs second approval

#2522 Audio internal lib: Merge dcache.c and aisetnextbuf.c into os.c
  spec/spec
  src/audio/internal/dcache.c
  src/audio/internal/os.c
Labels: Needs second approval

#2525 C23 Compatibility
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: Met Review Requirements

#2526 Fix fix_bss.py
  tools/ido_block_numbers.py
Labels: Needs second approval

#2527 `AVOID_UB`: `FileSelect_LoadGame` out of bounds `gBitFlags[-1]`
  src/overlays/gamestates/ovl_file_choose/z_file_choose.c
Labels: Needs first approval, Needs second approval

#2530 Format assets/
  format.py
Labels: Met Review Requirements

#2531 Add write_source.txt: list of files to write source for during assets extraction
  tools/assets/extract/extract_xml_z64.py
  tools/assets/extract/write_source.txt
Labels: Met Review Requirements

#2529 Assets system utilities
  tools/assets/extract/extase/__init__.py
  tools/assets/extract/extase_oot64/dlist_resources.py
Labels: Met Review Requirements

#2534 [assets] Explicit size for textures and dlists
  tools/assets/extract/extase_oot64/dlist_resources.py
Labels: Needs second approval

#2536 Some sequence 0 improvements
  assets/audio/sequences/seq_0.prg.seq
  include/audio/aseq.h
Labels: Met Review Requirements

#2538 Pause doc: Equipment page
  include/z64pause.h
  src/code/z_kaleido_setup.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.h
Labels: Met Review Requirements

#2528 Finalize and commit `object_link_boy`
  assets/objects/object_link_boy/object_link_boy.c
  assets/objects/object_link_boy/object_link_boy.h
  assets/xml/objects/object_link_boy.xml
  src/overlays/actors/ovl_Boss_Tw/z_boss_tw.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  tools/assets/extract/write_source.txt
Labels: Met Review Requirements

#2537 T() macro in overlays 5
  src/overlays/actors/ovl_En_Anubice/z_en_anubice.c
  src/overlays/actors/ovl_En_Anubice_Tag/z_en_anubice_tag.c
  src/overlays/actors/ovl_En_Bom_Bowl_Man/z_en_bom_bowl_man.c
  src/overlays/actors/ovl_En_Bom_Bowl_Pit/z_en_bom_bowl_pit.c
  src/overlays/actors/ovl_En_Butte/z_en_butte.c
  src/overlays/actors/ovl_En_Changer/z_en_changer.c
  src/overlays/actors/ovl_En_Diving_Game/z_en_diving_game.c
  src/overlays/actors/ovl_En_Ex_Item/z_en_ex_item.c
  src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
Labels: Met Review Requirements

#2542 Commit `object_link_child`
  assets/objects/object_link_boy/object_link_boy.c
  assets/objects/object_link_child/object_link_child.c
  assets/objects/object_link_child/object_link_child.h
  assets/xml/objects/object_link_child.xml
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/assets/extract/write_source.txt
Labels: Met Review Requirements

#2546 Commit `icon_item_static`
  assets/textures/icon_item_static/icon_item_static.c
  assets/textures/icon_item_static/icon_item_static.h
  src/code/z_parameter.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope.c
Labels: Met Review Requirements

#2550 [assets] Sort gkeep resources by offset
  assets/xml/objects/gameplay_keep.xml
  assets/xml/objects/gameplay_keep_pal.xml
Labels: Met Review Requirements

#2548 [assets system] Fix fusing resource buffer markers
  tools/assets/extract/extase/__init__.py
Labels: Met Review Requirements

#2557 Fix sym_info.py for older Python
  sym_info.py
Labels: Met Review Requirements

#2559 sPlayerFaces as array of structs instead of 2d array
  include/z64player.h
  src/code/z_player_lib.c
Labels: Met Review Requirements

#2562 Commit `icon_item_24_static`, `icon_item_{fra,ger,jpn,nes}_static`, `item_name_static`
  assets/textures/icon_item_24_static/icon_item_24_static.c
  assets/textures/icon_item_24_static/icon_item_24_static.h
  assets/textures/icon_item_fra_static/icon_item_fra_static.c
  assets/textures/icon_item_fra_static/icon_item_fra_static.h
  assets/textures/icon_item_ger_static/icon_item_ger_static.c
  assets/textures/icon_item_ger_static/icon_item_ger_static.h
  assets/textures/icon_item_jpn_static/icon_item_jpn_static.c
  assets/textures/icon_item_jpn_static/icon_item_jpn_static.h
  assets/textures/icon_item_nes_static/icon_item_nes_static.c
  assets/textures/icon_item_nes_static/icon_item_nes_static.h
  assets/textures/item_name_static/item_name_static.c
  assets/textures/item_name_static/item_name_static.h
  assets/xml/textures/item_name_static.xml
  assets/xml/textures/item_name_static_pal.xml
  tools/assets/extract/write_source.txt
Labels: Met Review Requirements

#2556 GetItem_Draw: giDrawId and comment GID_ values
  include/z64draw.h
  src/code/z_draw.c
Labels: Met Review Requirements

#2551 T() macro in overlays 8
  src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  src/overlays/actors/ovl_En_Guest/z_en_guest.c
  src/overlays/actors/ovl_En_Horse_Game_Check/z_en_horse_game_check.c
  src/overlays/actors/ovl_En_Hs/z_en_hs.c
  src/overlays/actors/ovl_En_Ice_Hono/z_en_ice_hono.c
  src/overlays/actors/ovl_En_Insect/z_en_insect.c
  src/overlays/actors/ovl_En_Ishi/z_en_ishi.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Kakasi2/z_en_kakasi2.c
  src/overlays/actors/ovl_En_Kakasi3/z_en_kakasi3.c
  src/overlays/actors/ovl_En_Ko/z_en_ko.c
  src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Ny/z_en_ny.c
  src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_En_Zl3/z_en_zl3.c
Labels: Met Review Requirements
